### ISSUE TITLE
Paratrooper unit icon is not shown when embarked

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#100]
Hi

While playing the "Student" scenario from the Das Reich campaign, I faced one annoying problem with paratroopers. When they are in the ground/disembarked mode, everything is fine. However, once you turn them into the air/embarked mode, no icon is shown, i.e. a unit becomes invisible. You still can find it through the list of units, activate, control, move, etc. 

I cannot confirm whether it happens all the time or not (I will do more testing). However, I am attaching a saved game in which this problem can re-produced. There is a paratrooper unit in the right top side of the map, next to two tanks. Once you ask it to embark to the air transport, it just disappears.

I will check whether the same issue can be reproduced with other browsers.

**Comment by salexgit** [comment]
Here is the saved game file: 
[(Campaign) Student Turn 17 Sat Dec 24 2016 12_08_35 PM.json.zip](https://github.com/nicupavel/openpanzer/files/672101/Campaign.Student.Turn.17.Sat.Dec.24.2016.12_08_35.PM.json.zip)

I was playing the beta 2.9.6 version.

**Comment by salexgit** [comment]
I test the attached saved game (see previous email) in different browsers, under Linux and Windows, and was able to reproduce the bug in all the cases.

**Comment by nicupavel** [comment]
#102

**Comment by salexgit** [comment]
Hi

I checked this issue with the latest 2.9.7 beta and it is still there. At least I can reproduce this bug with the same saved game which I attached to this thread.
