### ISSUE TITLE
Available prestige for the next scenario in a campaign

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#101]
Hi

I am not sure whether it is a bug or a feature, but I observed the following issue. If you start a new scenario, then usually there is quite a high prestige (around 2000 in most scenarios). However, if you move from one scenario to another as a part of a campaign, then additional prestige is much smaller. 

While playing the "Fall Weiss" campaign I did not have much complains about additional prestige added for every next scenario (less than 2000, but still around 1000). However, as for the "Das Reich" campaign, only around 100 is provided for the "Student" and "7th French Army Rush North" scenarios, which is literally nothing. Is it intentional by design or is there some bug that prevents the game engine from assigning correctly additional prestige?

**Comment by nicupavel** [comment]
Yes, the prestige on stand alone scenarios is much bigger so you can try things. 
In campaign Student for example had 500 for Brilliant Victory, 200 for Victory and 100 for tactical victory.

**Comment by salexgit** [comment]
Hi again

I played several more scenarios from the "Das Reich" campaign, and I have to admit that there is an imbalance in how much prestige you get while moving to the next scenario, versus how much you get when you start the same scenario as a standalone game.

As an example, if you start any of the 4 first scenarios of the "Das Reich" campaign, you will be assigned 2000 prestige, which you can fully spend on units without caring too much whether they would die in combat or not, because you play just one game. However, if you play the campaign, you will be assigned 2000 only once in the beginning, and you do have to care about your units (and some of them indeed die). 

My point is that in the "Das Reich" campaign you get too little prestige for every next scenario, as for me 200 for Victory is really nothing. You can afford buying just one basic unit and you cannot dream of anything more sophisticated as a tank. I would suggest the following numbers:
1000 - Brilliant Victory
500 - Victory
100/250 - Tactical

In fact, these number can vary a bit from a scenario to the scenario. In the beginning, Germany had much more resources and thus available prestige can be higher. At the end of the game, when Germany economy was almost collapsed, additional prestige could be lower.

**Comment by nicupavel** [comment]
All stand alone scenarios get 2000 prestige no matter what. The prestige for campaign scenarios were set by campaign designer. This doesn't mean we can't change it if it's too annoying.

**Comment by salexgit** [comment]
Thanks for a quick response. Do you have contact information of the "Das Reich" campaign designers? Maybe we should contact them first asking about the motivation behind setting such low prestige values.

**Comment by salexgit** [comment]
Hi again

Back to this issue. Can you send or let me know where "Das Reich" campaign description files are so that I can check prestige values for scenarios and suggest changes? In fact we can initiate this discussion on the forum so that people can express their views on how it should be changed.
