### ISSUE TITLE
A unit on the victory tile does not claim the tile

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#102]
Hi

While playing the Student scenario from the "Das Reich" campaign, I faced the following weird bug. There is my unit on the victory tile, but the tile is not claimed i.e. it still belongs to the enemy. 

I am attaching the saved game illustrating it. There is a top most victory tile, a city called Valkenburg, in which there is my unit, but the tile still belongs to the enemy (according to the strategic map and the number of objectives left).
[(Campaign) Student Turn 2 Sun Jan 01 2017 11_23_37 AM.json.zip](https://github.com/nicupavel/openpanzer/files/680685/Campaign.Student.Turn.2.Sun.Jan.01.2017.11_23_37.AM.json.zip)

This bug can be reproduced by performing the following actions:
- start the Student scenario;
- there is a paratrooper unit over Valkenburg, so it is possible drop them directly into the city, whereupon the city will be captured (everything is fine);
- after pressing "next turn", a weird thing happens - the unit in the city somehow changes its ownership and the game shows that the city is again captured by the enemy;
- saving and loading the game restores unit ownership, but the city still belongs to the enemy;

It seems that there is some bug in the game engine, which for some reason causes unit ownership change.

**Comment by nicupavel** [comment]
When you disembark and don't move the unit, the unit remains in a dangling state I will fix this by re-embarking the unit. Also you can't paradrop directly over a city.

**Comment by salexgit** [comment]
Hi

Just out of curiosity, why is not it possible to paradrop directly into the city? Well, current game engine allows doing it, so do you plan to prohibit this functionality? As for me this is quite a neat feature :)

Anyway, do please let me know when "beta" will contain the fix so that I can test it further.

**Comment by nicupavel** [comment]
It was never possible, neither on the original game. When you think you paradrop directly into the city, you actually only take out the unit from carrier leaving it "hanging" in the air. You could easily go over this unit with another air or ground unit (depending on the state).

**Comment by nicupavel** [comment]
The beta 2.9.7 has this fix

**Comment by salexgit** [comment]
Hi

Ok, I checked quickly beta 2.9.7 and now I see the logic of how it works. To really disembark the unit, you have to press the disembark button and move it. If it is the way it was done in the original game, fine, but it is really counter-intuitive :)

**Comment by salexgit** [comment]
Just for information, I played several scenarios with paratroopers, now they work fine.
