### ISSUE TITLE
To be deployed units do not show valid combat experience in the "inspect unit" window

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#105]
Hi

When you start  a new scenario, you typically have a set of units to be deployed, which are showed in the top most window. While selecting a unit on the list, you can also inspect it, of course if the "inspect unit" window is activated. However, for some reason, the combat experience value for any unit on the list is always zero, even though it is not zero, which you can check when the unit is actually deployed.

It is not a big issue, but if you want to deploy first most/least experience unit, then it matters.

Regards, Alex

**Comment by salexgit** [comment]
Hi

For the sake of clarity I am attaching a saved game at the 1st turn. Most of the units I already have non-zero combat experience, but the "inspect unit" window always shows 0 before a unit is deployed.
[(Campaign) 7th French Army rush North Turn 1 Sat Jan 07 2017 3_32_47 PM.json.zip](https://github.com/nicupavel/openpanzer/files/703895/Campaign.7th.French.Army.rush.North.Turn.1.Sat.Jan.07.2017.3_32_47.PM.json.zip)

**Comment by nicupavel** [comment]
I know about this issue, there is no easy way for me to show experience while units are not deployed.

**Comment by salexgit** [comment]
Ok, thanks for explanations.

If it is not easy to show combat experience for a unit (for whatever architectural reason), then can we make a temporary hack by sorting unit on the deployment list on the order of e.g. descending experience? If I remember right, you already group them based on the unit type, so we can add additional sorting within a group based on experience. Then, even though we do not know how experienced a particular unit is, we can still know that it is the most experienced one.

**Comment by salexgit** [comment]
Hi 

Yet another way to introduce a quick solution is to implement an enhancement discussed in #65. If there is a way to assign a specific name to the unit, then it will be possible to identify a leader by its name.
