### ISSUE TITLE
List with the to be depoyed units overlaps with the deployment tiles 

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#106]
Hi

Not a bug, just a usability issue. There are scenarios in which deployment tiles are at the top of the map, which can partially or fully overlap with the list of to be deployed units. The most eloquent example is "Crossing the Schelde" scenario. If you play it as a standalone game, then it is not so critical as most of the units are already deployed. However, if it is played as a campaign, then it becomes very tricky to deploy units.

I am attaching the saved game that illustrates the problem:
[(Campaign) Crossing the Schelde Turn 1 Sat Jan 14 2017 6_44_03 AM.json.zip](https://github.com/nicupavel/openpanzer/files/705776/Campaign.Crossing.the.Schelde.Turn.1.Sat.Jan.14.2017.6_44_03.AM.json.zip)

I do not know the easiest way to solve the problem. If possible, the window with units can be made as "floating" so that you can move it to the left or to the right (of the game engine can do it automatically). In fact, it would be nice to make both "list of units" and "inspect unit" windows floating, because sometimes "inspect unit" overlaps with deployment hexes which are at the bottom.

**Comment by salexgit** [comment]
Same problem is in the "Unternehemen Seelowe training" scenario, top most deployment hexes can overlap with the unit window (but it is not as bad as in "Crossing the Schelde").

**Comment by nicupavel** [comment]
I was annoyed by this too, can't seem to find a better UI to deal with this. The quickest fix would be to make extra deployment tiles in the scenario. I must check if the panzer general 2 engine allowed owned victory hexes to be used as deployment.
