### ISSUE TITLE
Offline package for the desktop computers

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#110]
Hi

I noticed that the OpenPanzer game can be played in the completely off-line mode on Android or Apple. However, it is not really playable in the off-line mode on the desktop. There is an ugly hack to ask your browser to load and cache something, but you never know whether the game has cached all the information it needs, which may cause some problems later. 

Is there any reason why there is no package for desktops?

**Comment by lexnekr** [comment]
Hello!
Using git, you can download the entire repository.
Then switch to the gh-pages branch.
Its contents are identical to the site http://openpanzer.net/

**Comment by salexgit** [comment]
Hi

I saw this option in some posts, but it is not end user friendly. You need to know how to fetch the repository and in addition you need to configure your browser accordingly to allow for the local file access. 

Since there is a standalone package for iPhone and Android mobile phones, I thought that it should be more or less straightforward to make the same package for desktop PCs.

**Comment by lexnekr** [comment]
I agree, I also think so.
And I would also like a distr for Ubuntu.
And more campaigns.

**Comment by salexgit** [comment]
I tried to fetch a package for the offline usage, and have realized that it is not really usable because essential data is simply missing. Having browsed a bit existing issue, I came across #63, in which it is explained that it is intentional, i.e. there is no way you can generate the offline package from GitHub.

I do not fully follow line of argumentation why essential information is excluded. At the end, if somebody wants to abuse data and use it unfairly, there is no way you can stop a person from doing that :/ The downside is that if other people want to test the game and do some improvements, there is no way they can contribute to the project.
