### ISSUE TITLE
Differentiating between the core and auxiliary units

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#111]
Hi

Does Open Panzer allow for differentiating between the core and auxiliary units? At least Open General game differentiates between them by displaying units with a different color. 

What about showing the corresponding information (at least) in the inspect unit window? As a quick and dirty enhancement, the inspect window can just show C(ore) and A(uxialiary) labels.

**Comment by nicupavel** [comment]
Yes the core units have a border around strength and also display (Core Unit) when inspecting.

**Comment by salexgit** [comment]
Thanks. I have to note that the border around the strength bar is very thin :)
