### ISSUE TITLE
Air mode map ehancement

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#115]
Hi

It is not a bug, but just a small proposal to enhance the map "air mode". 

The way it works now is that when you switch the map into the air mode, it just shows an air unit icon on top of the ground unit if they are stacked. However, since air units icons are sometimes quite small, it is sometimes challenging to find an air unit. Quite many times I resort for opening the unit list to find air units.

The enhancement would be so that once you switch into "air mode", the game engine would somehow highlight/emphasize all the air units. As an examle, it can be done by drawing some border around the corresponding tiles, similar to the red border that is shown around potential targets for the artillery units.

In fact, this idea can be generalized a bit to allow for switching the map into the infantry/tank/artillery/.../air mode, but this is the next step.

**Comment by nicupavel** [comment]
I usually use air mode + tactical map to find my air units but it's a good idea.

**Comment by nicupavel** [comment]
Done in 2.9.8. Clicking selected unit deselects unless a attackable target is below.
