### ISSUE TITLE
Is it intended that a range 2 direct fire unit (non-artillery) can fire over an enemy held hex onto another unit?

### ISSUE THREAD

**Issue by JohnZ622** [nicupavel/openpanzer#116]

**Comment by salexgit** [comment]
That is an interesting point. In other words, an anti-tank artillery unit should not be able to fire at range 2 if there is another unit (enemy or not) in between. I cannot say whether it is indeed the case in the reality for e.g. anti-tank artillery units, but the game allows it.

**Comment by marcofango** [comment]
Well, we are talking about range for guns.
If the gun can manage a long range (and we know that german tanks, russian guns and some allied were able) you could aim at long distance.
Maybe can be imagined a sort of precision modifier, as per russian tanks were powerful in close combat but not in long range.
Or still, modification for terrain: bush, woods or plains can be passed through, but not cities.

Anyway interesting point of view.

**Comment by salexgit** [comment]
I suppose that the point is not only about range but how you actually fire, i.e. whether it is a mortire-like unit or not. Most of anti-tank guns need a direct and clear line of sight to shoot the target, so if there is an obstacle (another unit, wood, etc), then maybe you should not be able to fire.

I agree that it would make game more realistic, but if something like that is introduced then you will need to redesign quite many aspects including balance of units.

**Comment by marcofango** [comment]
I do not agree.
Any unit can be used as a support gun fire, also heavy tanks and any ranged weapon.
Anti tank can reach long distances also in indirect fire; and probably they were doing this in reality, having infantry units in between line of fire to targeted tanks.
By my means, only cocnrete obstacles should be considered, as per cities cannot be passed through (and as said before, woods could lower precision or effects).

**Comment by salexgit** [comment]
Just for information, this feature has already been supported in OpenGeneral. I did not delve into the details but there are some top level scenario settings that allow to control whether 2-3 line of fire range can be obstructed by e.g. forest, city, etc.

**Comment by salexgit** [comment]
A few cents more on this topic.... The way it is implemented in OpenGeneral is that every units has "Allow line of fire" ability that controls whether you can fire "through" it or not. As an example, you might fire through infantry but not through a tank.

However, I suppose that it should also depend on the attacking unit: while artillery can ignore this flag, the anti-tank like units should account for it.
