### ISSUE TITLE
Recon aircraft

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#117]
Hi

While playing the "Maginot line garrison" scenario, I noticed one fancy unit, recon balloon. I am attaching the screen snapshot which also shows this unit characteristics. The most interesting thing is that this unit has spotting range of 6! 

![snapshot1](https://cloud.githubusercontent.com/assets/22852936/26721307/150035f0-4794-11e7-8352-4e4a594cdef0.png)

I started to investigate whether OpenPanzer has similar air units that would allow to perform airborne recon,  and it came to me as a bit of surprise that there is no well developed concept of recon air units. There are a lot of different ground recon units, but air units are literally missing despite the fact that have been playing quite an important role in WWII. In fact, OpenPanzer set of units offers something, but...

GERMANY
There is a unit called "FW-189 UHU", which is according to Wikipedia is exactly the recon unit. However, its spotting range is only 2! So, it is very obscure that a ground recon unit has a range of 3, while the air unit has a range of 2. 
Should not we increase it to 3-4?

US
There is one unit called "F-4". Based on its icon, it seems that it is Lockheed F-4 Lightning. Its spotting range is 3, which makes it a good recon unit. It seems that the unit intention is indeed to serve recon purposes because it does not have strong attack strength. However, the price is ridiculously high, 900! As a comparison, "FW-189 UHU" price is 372.
As for me, either we should lower the price to make it more attractive or increase the spotting range to 4-5, or both. As for me, price of 400-500 is a good deal for the air unit that has the spotting range of 4-5, but which does not have a strong attack strength.

SOVIETS
There is nothing which would look like an air recon unit. In fact, Soviets were making a lot cheap multi-purpose aircraft, some of which were also used for recon purposes. In fact, one of those airplanes is Yak-9R, which is a tactical reconnaissance aircraft. 
The simplest way would be to add a new unit by reusing existing Yak-9 icon from OpenPanzer, lower attack strength, and increase the spotting range to 3 (to be comparable with FW-189 UHU). The price should be also lower, as the existing Yak-9 price of 948 looks very high.

Comments are welcome...

**Comment by marcofango** [comment]
I do agree, some units should be dedicated to air recon, also without adding a special cathegory (or recomprising them in recon also if flying).
Storch was one of them but many american fighters were partially reconverted.

**Comment by LaughtersGrave** [comment]
Best air recon you can get is bf110D but you have to buy it before 1943 otherwise it dissapears. It is kinda bad at everything except movement and spotting given it's movement of 20 and spotting of 3,with experience of around 1200 they can bomb most units even heavily entrenched, for 6 damage and they can handle themselves in the air (just about) 

however

Because they are described as bombers they have a massive draw back, they can never get recon veteran. Not only this they are stuck with the bombers nearly useless "cannot be surprised" ability (nearly useless as enemy Air is extremely rare with most maps having either 4 enemy air units or none, exceptionally maps having up to 10 which is dwarved by any sensible players 20 + air units).

**Comment by salexgit** [comment]
Hi

I do not have any big issue with modelling air recon units as "fighters" or "bombers" because that it is eventually what they are; most air recon units are effectively redesigned bombers. The only downside is that OpenPanzer recon units have a special set of leader attributes, but I am not entirely sure how critical it is. As an interesting remark, recon unit class is orthogonal to air/ground unit type, so in principle recon aircrafts can be even modelled as recon units.

As another interesting point, there is a separate "phased movement" attribute which some ground recon units use. So, it can be applied also to the air recon units so that you have a possibility to visit several places in one turn.

**Comment by LaughtersGrave** [comment]
Which is what I just said comrade. If they're bombers they cannot get the leader ability, recon veteran.

It would be a great idea, I think, to put the Bf110D into the recon section
