### ISSUE TITLE
Air Transport

### ISSUE THREAD

**Issue by marcofango** [nicupavel/openpanzer#120]
Any system to get them during the game (except my unlawful editing of json saves)?

;)

**Comment by salexgit** [comment]
This has been implemented and supported in OpenGeneral. I doubt this is going to be implemented in this game as it would require noticeable changes in the game engine.

No offense to developers, but even trivial things are not fixed :/

**Comment by marcofango** [comment]
Salexgit, 
why do you imagine a requirement for deep changes?
In any save file (json format) you can edit the number of air transports available, and you use them in that scenario, but you need to redo the process in the next scenario of the campaign.
I thought it was possible to just carry the transports from one scenario to the other, having a determined number already in the beginning of the campaign.

**Comment by salexgit** [comment]
The way it is implemented in OpenGeneral is that some units have "airmobile" property, and thus they can be transported under certain conditions. In other words, it is orthogonal to the unit type itself.

For OpenPanzer, maybe the game engine already supports something, which is just cannot be fully utilized. I thought (maybe mistakenly) that the game engine only supports paratroopers as the corresponding independent unit type, i.e. it cannot be applied and mixed with a light tank or a light cannon.

**Comment by nicupavel** [comment]
I think there is a similar trait on OpenPanzer too it's inherited from Panzer General 2:
`Non-organic transport
      00=Cannot be transported 
      01=Can be Naval transported
      02=Can be Airmobile & naval
      03=can be Airborne & naval & Airmobile`
http://luis-guzman.com/links/PG2_FilesSpec.html#(EQP) file

As for providing AirTransports this could be implemented by purchasing them with prestige.

**Comment by marcofango** [comment]
Sincerely, I didn't tried any other unit except infantry.
Paratroopers can be loaded, and also some type of mechanized infantry, without losing the land transport (and this may be opinable).

**Comment by salexgit** [comment]
The way it is implemented in OpenGeneral is that you can buy air transports at the airport, and then you can load units on it. If it is an airborne unit, you can unload it anywhere; otherwise you can unload it only in another airport. If I got it right, once you deploy/transport the unit, the air transport disappears (but it is relatively cheap, so no problem), which as for me makes logical sense.   

Maybe it is indeed worth experimenting with what the game engine offers by editing the .json file :)

**Comment by nicupavel** [comment]
Currently air transports are defined in scenario properties.
