### ISSUE TITLE
Selected unit frame is not visible in winter scenarios

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#121]
This is just a minor usability issue. When you a play a winter scenario and select a unit, its frame is not visible because it is also white, same as terrain. 

The most obvious way would be to use a different color for a selected unit. One option is to use light light blue color. It should be close to the white color we use at the moment, but it should be still visible on top of winter terrain.

**Comment by nicupavel** [comment]
Fixed in 2.9.9-2
