### ISSUE TITLE
Attack strength against bunkers and fortifications

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#122]
Hi all

Does OpenPanzer egine support a concept of the attack strength against bunkers and other fortication facilitities? The reason I am asking is that some infantry units have a specific name, which hints towards the fact that they have some bonuses against bunkers, but I was not able to find any explicit notion of that in a unit description.

**Comment by salexgit** [comment]
At least the OpenGeneral manual says that:
- every unit (including fortifications) have a certain base entrechment and entrechement speed that allows them to get additional defense strength against the attacker;
- at the same time, units with the "engineer" capability ignore the entrechment bonus of the defender;
- it seems that at least in OpenGeneral the "egineer" capability is the independent unit ability that can be attached to any unit, but I did not find either a clear explanation which units actually have them.

Any insight on how it works for OpenPanzer and whether it is possible to have the "engineer" capability (if the one exists of course) to be explicitly indicated in the unit inspect window?

**Comment by nicupavel** [comment]
It's not actually engineer ability (we have that too) it's a ignoresEntrenchment ability in the equipment which is implemented too.

Besides that we also check for a leader abilities that ignores entrenchments.

**Comment by salexgit** [comment]
Thanks a lot for response! There are several follow-up questions:
- as you do not share equipment files, is there any way you can add the corresponding information into the inspect unit window so that we know which unit has this ability?
- assuming that it will take you some time to add the aforementioned information into the inspect window, if it is not a big burden, can you indicate which units are immune to entrechment?
- what is the difference between "engineer" and "ignore_entrechment" ability in OpenPanzer?
