### ISSUE TITLE
Battle of the Hedgerows - :)

### ISSUE THREAD

**Issue by marcofango** [nicupavel/openpanzer#123]
Against all M16 Flaks????????? :)
[(Campaign) Battle of the hedgerows Turn 3 Tue Jun 20 2017 13_27_36.zip](https://github.com/nicupavel/openpanzer/files/1088010/Campaign.Battle.of.the.hedgerows.Turn.3.Tue.Jun.20.2017.13_27_36.zip)

**Comment by salexgit** [comment]
The issue is similar/identical to the problem discussed in #199, so it will be closed.
