### ISSUE TITLE
Missing files (maybe my fault?)

### ISSUE THREAD

**Issue by Flo1221** [nicupavel/openpanzer#126]
Hello, it seems to me that i am missing a lot of files when downloading the latest version. I do not know much about how github works, so maybe i am doing something wrong?

**Comment by salexgit** [comment]
Hi

It is not your fault. As discussed in #110 and #63, developers intentionally do not allow fetching all the files needed to play the game. So, it means that you cannot play the game in the offline mode, experiment with different settings, contribute to the game by developing new units, maps, and scenarios, etc.
