### ISSUE TITLE
Cannot deploy core units in Vyazma operación Typhoon

### ISSUE THREAD

**Issue by emilianono** [nicupavel/openpanzer#128]
Grey hexes to deploy core units do not appear in this scenario. I do not know What is wrong. 
Is it possible that From this scenario on old units are gone?

**Comment by salexgit** [comment]
Hi

Can you upload the saved game with this problem? I remember myself playing this scenario some time ago and everything was fine.

**Comment by emilianono** [comment]
Hello: I don't know how to upload files. If I select upload files from web page I get the following message: 
Uploads are disabled.
File uploads require push access to this repository.

How can I solve this?

Thanks

Enviado desde mi iPad

**Comment by salexgit** [comment]
Hi

Upload the saved game file to this email thread as an attachment. Note that github does not accept ".json" saved games, so you will need to compress it first.

**Comment by emilianono** [comment]
Thanks very much for your interest. I play this game in my ipad, and I save
files to disk (but I don´t know how to get the file from the game and
compress it). Clues about how I can do what you suggest would be highly
appreciated.
Best regards

2017-09-05 12:34 GMT+02:00 salexgit <notifications@github.com>:

**Comment by salexgit** [comment]
Hi

If you play the game on iPad, then you play the old version and you might have the same problem as reported in #79. Try the latest beta game here: http://openpanzer.net/beta.

Also note that the mobile phone version of the game has not been updated for a while (no clue why), so you might experience other problems as well.

**Comment by nicupavel** [comment]
Fixed in 2.9.8
