### ISSUE TITLE
Display iPhone 7 Plus iOS App

### ISSUE THREAD

**Issue by ghost** [nicupavel/openpanzer#132]
Since iOS 11, only half a display is displayed and rotated. The other half is black. The game can not be played like this.

**Comment by salexgit** [comment]
The game has not been supported for a while for mobile platforms, there are issues with the mobile version for Android as well.

You can try to use the offline package as discussed in #131, but this might work only for desktops.

**Comment by greengamerUSSR** [comment]
Yeah, it’s a huge problem for me, because I have a Mac, so I can’t play the PC version, so orties downloading the iPhone one and this happens, I really hope someone fixes this soon.

**Comment by greengamerUSSR** [comment]
Apparently a lot of people have noticed it and it’s starting to get 0 star ratings on the App Store.

**Comment by nicupavel** [comment]
@greengamerUSSR Doesn't matter if you have a Mac just using the http://openpanzer.net/beta should work regardless of the OS you are using.

**Comment by salexgit** [comment]
As nicupavel commented, you can use the online version which should work on MAC OS well. If you do not like the online version, you can use the offline package; see #131 or visit https://sites.google.com/site/openpanzeroffline.  
I tested offline package with a number of browsers on Linux and Windows, so I would be more than happy if you confirm which browsers should/can be used with MAC OS.

Regarding the mobile version of the app, as far as I understood it was almost consciously abandoned the app was updated neither for Android nor for iOS. Maybe developers can provide better insight on what the plans are.

**Comment by PMARC14** [comment]
Is there any plans for future support for mobile? I haven't followed this project in years and I am interested in participating.

**Comment by nicupavel** [comment]
Still works fine on iOS
