### ISSUE TITLE
Discrepancies in German AR-196 and FW-189 aircrafts

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#133]
While playing the German campaign, I noticed several discrepancies in German aircraft specifications, 
and more precisely FW-189 UHU and AR-196 Arado. So, referring to Wikipedia, AR-196 was a very simple aircraft. And even though it had some armament including machine guns and 2x50kg bombs, it was used mostly as the recon aircraft. For some funny reason, AR-196 is positioned as an expensive and powerful aircraft in OpenPanzer with characteristics better than JU-87C-1, which is a real dive bomber. As a comprasion, both JU-87C-1 and FW-189 could have 4x50kg bombs.

Here is the table providing more details on current charateristics of JU-87C-1, AR-196, and FW-189

Parameter | JU-87C-1  |  AR-196  |   FW-189 
------------|----------|-----------|--------------
Vision             |       2    |       2   |       2
Hard attack    |       3     |      4    |      1
Soft attack     |        3    |       5    |      1
Air attack        |       3     |      8     |     1
Air defense      |      5     |      7     |     7
Ground defense  |  8      |     6     |     7   
Price                    | 348    |     732  |      372

Based on the historical records and further information from Wikipedia, AR-196 and FW-189 parameters are suggested to be as summarized below in the table (using JU-87C-1 as a logical reference): 
- AR-196 hard and soft attack strength is reduced
- AR-196 air attack and defense are reduced
- AR-196 price is also noticeable reduced
- FW-189 parameters are slightly increased (except the air defense and price)
- FW-189 vision range is increased to 3 to reflect its recon capability, as also discussed here #117 

Parameter | JU-87C-1  |  AR-196  |   FW-189 
------------|----------|-----------|--------------
Vision                  |      2     |       2     |       3
Hard attack         |      3     |       1     |       2
Soft attack          |      3     |       2      |      3
Air attack             |     3      |      2      |      2
Air defense           |    5      |      4      |      7
Ground defense   |     8     |       6      |      8   
Price                     |  348     |     250    |    372

Lastly, the AR-196 introduction year should be 1938, and FW-189 introduction year should be 1941.

**Comment by salexgit** [comment]
I created a patch that fixes those issue with AR-196 and FW-189. The attached patch can be applied to the offline package (see #131) if developers do not take these corrections into the official online package.

[openpanzer-2.9.7-ar196fw189.patch.zip](https://github.com/nicupavel/openpanzer/files/1414442/openpanzer-2.9.7-ar196fw189.patch.zip)

I also attach a figure showing new parameters and price of AR-196 and FW-189, respectively, from the offline package with the applied patch.

![ar196](https://user-images.githubusercontent.com/22852936/31997399-883f7fa4-b994-11e7-9302-6ce2ea97b1b2.png)
![fw189](https://user-images.githubusercontent.com/22852936/31997408-8e76c92c-b994-11e7-90d9-10cea5171212.png)

**Comment by LaughtersGrave** [comment]
You're completely right
