### ISSUE TITLE
Lodz Warta River scenario wrong description

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#135]
Not a critical bug, but just a small inconsistency. It seems that the "Lodz Warta River" scenario description is exactly the same one as the "Warsaw" scenario from the same campaign. The fix is quite straightforward, but somebody needs to write a nice historical description :)

Here is the screenshot showing wrong scenario description.
![lodz_warta_river](https://user-images.githubusercontent.com/22852936/32945709-247cc79a-cb9d-11e7-81c7-2701ebe12bf3.png)

**Comment by salexgit** [comment]
I noticed that in addition to the "description" field, which shows the standalone scenario information, there is also a similar field in the campaign description file; and in most cases they are identical. So, the campaign file has a correct description for this scenario, which can be just copy/pasted.

"Lodz - Warta River\r\n\r\nThe first important obstacles in our advance into Poland have appeared; the Warta river, the bunkers built by the Polish along the river, and the army of Lodz. The objetive is basically cross the Warta and take the city of Lodz, but take care, the losses in the crossing of the river could be heavy for us. Reinforcements will arrive from the South-East of this area, as well as some Luftwaffe units.\r\n\r\nGood Luck".

**Comment by nicupavel** [comment]
Fixed in v2.9.8
