### ISSUE TITLE
Announcing Wacht Am Rhein campaign

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#136]
Hi all

Not really an issue... Having an offline package of the OpenPanzer game enabled me to port one of the PGII campaigns to the OpenPanzer format. As a starting point of my exercise I took a simple "Wacht am Rhein" campaign comprising 6 scenarios. It seems to work, but I did not perform thorough testing of the whole campaign. If somebody spots something strange, then do please let me know. I can check whether the same "issue" exists in the original campaign and whether it was intentional or not.

The offline package with the campaign file can be taken from the corresponding site.
https://sites.google.com/site/openpanzeroffline/downloads

I am also attaching a screenshot showing a new campaign and its scenario files.
![wachtamrhein](https://user-images.githubusercontent.com/22852936/33607057-54e17280-d9c8-11e7-951b-3f463187f019.png)

**Comment by marcofango** [comment]
Ok, gonna try It.

Il 05 dic 2017 1:28 PM, "salexgit" <notifications@github.com> ha scritto:

**Comment by salexgit** [comment]
I have not yet played the whole campaign, but I spotted the following "issues", which in fact could be intentional:
- there is no start prestige
- prestige for brilliant and normal victory is quite low

Well, maybe this is intentional to reflect the fact that German troops experienced lack of ammunition and support by the end of war. I will double check with the original designer of the campaign.

**Comment by salexgit** [comment]
This campaign is part of the main package now, so it can be closed.
