### ISSUE TITLE
Announcing Sovie Black Sea campaign

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#137]
In case somebody is interested in playing more campaigns, here is another campaign that I ported from PGII. I took the "Soviet Black Sea" campaign from the Adlerkorps site and converted it into format of the OpenPanzer game. 

The offline package with the corresponding campaign can be downloaded from the following address. Note that for testing purposes the corresponding package contains only this campaign. 
https://sites.google.com/site/openpanzeroffline/downloads

Post any feedback directly to this thread. While porting the campaign I noticed the following issues, which could be fixed at the next release:
- Starting prestige is a bit low, just 500
- Prestige for brilliant and normal victory is also a bit low
- For some reason (looks like a bug in the PGII files) you always get higher prestige if you lose
- Some scenarios do not have auxiliary units, e.g. the first scenario that opens the campaign.
- "Crimea choice" scenario does not work as expected

![blacksea](https://user-images.githubusercontent.com/22852936/36060327-5417a53a-0e3f-11e8-82d3-69b71873118b.png)

**Comment by sprinkler** [comment]
Great work. I'll try it. I also intent to update the conversion tools when I find some time to ease this process.

**Comment by salexgit** [comment]
Hi sprinkler

Speaking of conversion tools, while converting PGII campaigns I fixed a number of minor issues and problems in PY scripts to convert scenarios and maps. Some of those enhancements were introduced to circumvent around imperfections in PGII files. 

I am attaching here the latest versions of conversion tools with changes I did. It would be good if you or somebody upload them to the official repository so that others can use it in the future. If you need to more detailed explanations for changes I did (e.g. for the commit messages), I can provide them.

[campaign-convert.py.zip](https://github.com/nicupavel/openpanzer/files/1713239/campaign-convert.py.zip)
[mapconvert.py.zip](https://github.com/nicupavel/openpanzer/files/1713240/mapconvert.py.zip)

**Comment by sprinkler** [comment]
Might be better if you can provide a diff against current version. I also changed these scripts and have to check if I hadn't already fixed some issues.

**Comment by nicupavel** [comment]
Great work. I'll try it. I also intent to update the conversion tools when I find some time to ease this process. It might be better if you provide the diff against the current version of conversion tools so I can check if I hadn't yet fixed some of the issues in my version.

Thanks

**Comment by salexgit** [comment]
Hi

Here are the diff files against the versions that I took from the source repository. If needed I can provide more detailed comments for changes I did (most of which I assume are self explanatory).

[campaign-convert.py.diff.zip](https://github.com/nicupavel/openpanzer/files/1713262/campaign-convert.py.diff.zip)
[mapconvert.py.diff.zip](https://github.com/nicupavel/openpanzer/files/1713263/mapconvert.py.diff.zip)

**Comment by salexgit** [comment]
I decided to provide some further comments for the changes I did in the conversion tools.

campaign-convert.py
- The first block of changes aims to remove .txt info file name conversion to the lower case. I am not sure what the intention was, but in most cases PGII info file names have correct names with correct case. Sometimes it does not match, but converting everything into the lower case does not really help and makes it even worse.
- The second and the third block of changes just make output messages more informative.  

mapconvert.py
- The first and the second block of changes improve output messages.
- The third block of changes contain an important fix for .MAP file processing. I noticed that some .MAP files have a weird value for the number of columns and rows, e.g. (0,0) or (1,1). I am not sure whether it is a bug or feature, but these values are sometimes set for those maps that have the maximum size. To circumvent around the problem, the map size is reset to the maximum size.  
- The fourth block also contains an important correction. The way I spotted the problem is that some .SCN scenarios have deployment hexes, which were not ported properly by the conversion script. Again, I am not sure whether it is a bug of a feature, but the conversion script would not add a hex entry to the final .XML file if the corresponding hex does not have any associated info, such as terrain, road, flag, etc. That was also preventing the script from adding the deployment hex entry. As for me the whole piece of code could be revised and improved.

**Comment by salexgit** [comment]
Hi Pavel

It seems that this discussion thead ended up with two topics: a new campaign and conversion tool enhancements. Can you decouple them by e.g. removing conversion tool comments from this thread and linking or pasting them into another one?
