### ISSUE TITLE
Missing map information in some scenarios

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#138]
Hi

This is not a bug in the game engine, but rather incomplete map information...

So, in the "Prokhorovka" scenario from the "Das Reich" campaign, the corresponding map description file does not contain hex information for the 2-3 bottom rows. As can be seen from the attached file, it is simple not possible to move units into those tiles because the game engine does not know anything about them. I checked drprok21.xml file, and indeed it contains hex information only till row 26.  

![prokhorovka](https://user-images.githubusercontent.com/22852936/37253142-7680d9be-2525-11e8-907d-3a43c6e74b88.png)

I did not check yet whether the problem comes from the fact that the original .MAP file does not contain that data, or there is some bug preventing tile information to be converted into the .XML format. Anyway, even if the original .MAP information is flawed, it seems quite straightforward to add missing tiles into the .XML file.

**Comment by salexgit** [comment]
I did some minor fixing of the map information .xml file and now the two bottom rows can be used properly. I attached the screenshot showing that now a unit can be moved into the bottom hexes.

![prokhorovka_fixed](https://user-images.githubusercontent.com/22852936/37861471-733caff0-2f32-11e8-8ed8-e3f7c748b230.png)

I am attaching here the fixed drprok21.xml file and the patch file so that developers can see actual changes. Note that I spotted several minor errors in existing hex information, so that was fixed as well.

[drprok21.xml.zip](https://github.com/nicupavel/openpanzer/files/1844129/drprok21.xml.zip)
[openpanzer-2.9.7-drprok21.patch.zip](https://github.com/nicupavel/openpanzer/files/1844130/openpanzer-2.9.7-drprok21.patch.zip)

Since the same map  is used another Soviet campaign scenario, same changes are also applied in the corresponding scenario file.
[ruscam04.xml.zip](https://github.com/nicupavel/openpanzer/files/1844131/ruscam04.xml.zip)
[openpanzer-2.9.7-ruscam04.patch.zip](https://github.com/nicupavel/openpanzer/files/1844132/openpanzer-2.9.7-ruscam04.patch.zip)

So, developers just need to copy/paste fixed .xml files (or apply the patches) to fix these inconsistencies.

**Comment by nicupavel** [comment]
I appreciate your fixes, I would prefer these to be made directly in the PG2 filess so I can easily export them for all platform builds. Please send me a private message so I can add you to the repository.

**Comment by salexgit** [comment]
Hi

Yes, it seems that fixing the .MAP file is the right way to do it especially if the same map is used in different scenarios and we still use .MAP files to port the game into different platforms.

I will send the private message a bit later...

**Comment by salexgit** [comment]
Hi again

I am not sure I got the point where and how I should send the private message :) It seems that Github does not support it.

**Comment by nicupavel** [comment]
npavel@linuxconsulting.ro should be fine.

**Comment by salexgit** [comment]
Hi

I checked the scenario map file, PROK.MAP, and indeed terrain information was missing for last two rows. In fact, it seems that there is coincidence of two bugs/problems:
- The .MAP file does not have any terrain information for last two rows even though the map size is correct.
- The OpenPanzer conversion script does not generate any entry in the .XML file if a particular hex does not have any associated information. Such an approach effectively truncates two last rows from the final .XML file in this particular case.

Anyway, I am attaching fixed .MAP file. However, I have not tested yet whether it works properly after conversion into the OpenPanzer  .XML file.

[PROK.map.zip](https://github.com/nicupavel/openpanzer/files/1865981/PROK.map.zip)

**Comment by salexgit** [comment]
Hi again

The same problem exists also for "Operation Zitadelle" scenario from the same campaign. As one can see from the attached file, there are two bottom rows which are not utilized by the game engine because they are out of range.

![zitadelle_wrong_tiles](https://user-images.githubusercontent.com/22852936/39190631-8144dc94-47c4-11e8-8c2a-fb36d5fc8833.png)

The corresponding .MAP file can be fixed in the same way by applying correct map size. Then, all the bottom rows can be used properly.

![zitadelle_full_tiles](https://user-images.githubusercontent.com/22852936/39190692-a365f20e-47c4-11e8-98bd-e66502bfd3e2.png)

I am attaching below fixed .MAP file.

[DRPROK2.MAP.zip](https://github.com/nicupavel/openpanzer/files/1942946/DRPROK2.MAP.zip)

**Comment by nicupavel** [comment]
Fixed in 2,9.8
