### ISSUE TITLE
Missing deployment tiles in converted scenarios

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#140]
This problem was mentioned coarsely in discussion under #137, but only now I realized that there is a systematic problem in all the scenarios converted from .SCN files. 

To illustrate the problem, I am attaching a screenshot from Prokhorovka scenario showing deployment tiles.

![prokhorovka_wrong_tiles](https://user-images.githubusercontent.com/22852936/38416746-42f971f4-3985-11e8-9e01-b70447862ee4.png)

However, the full set of deployment tiles should be like in the picture below. As you can see, there are a lot of deployment tiles simply missing in the first figure, even though there are in the original .SCN file.

![prokhorovka_full_tiles](https://user-images.githubusercontent.com/22852936/38416763-518d4da8-3985-11e8-82c8-a13062607cc4.png)

The root cause is a bug in the conversion script that simply does not add a deployment tile in certain cases into the OpenPanzer .XML file. To be more precise, if a deployment tile is on a "clear" tile with no roads, cities, forests, etc, then this deployment tile will not appear in OpenPanzer. It seems that all scenarios have been affected by this problem, which also explains why some scenarios have only several deployment tiles available.

I am attaching below a patch that fixes the problem. In fact, the second picture was produced by regenerating the OpenPanzer scenario from the original .SCN file by a conversion tool with the applied patch.
[mapconvert.py.patch.zip](https://github.com/nicupavel/openpanzer/files/1883602/mapconvert.py.patch.zip)

**Comment by salexgit** [comment]
Hi Nicu

There is another error/problem that I spotted in mapconvert.py script. PanzerGeneral MAP file has two fields in header indicating map size, i.e. number of columns and rows. However, these fields do not always indicate the actual map size but rather are set to dummy values of [0,0] or [1,1]; I saw both variants. 
Ironically enough, mapconvert.py script follows indicated .MAP size and reads only the specified numbers of columns and rows, which obviously generates empty .XML file in some cases. 

To circumvent around the problem I made a small change in the script. As you can see from the attached patch, if we encounter [0,0] or [1,1] combination, we reset internal variables to the maximum size that the MAP can have. This approach works perfectly fine because the .MAP file anyway always contains the maximum number of hexes. 

[mapconvert.py.patch.zip](https://github.com/nicupavel/openpanzer/files/1894419/mapconvert.py.patch.zip)

As an alternative solution, mapconvert.py file can simply ignore map size in the header and read all the hexes from MAP file. Since mapconver.py does not put "empty" entries into the final .XML file, then hexes outside the MAP size will be effectively ignored. The only downside of this approach is that some .MAP files (I saw several cases) have non-zero garbage hexes outside the effective MAP area, which causes the same garbage to appear in the final .XML file.

If you want and/or prefer, I can open a new issue for this problem and provide screenshots with .MAP files to illustrate this problem.

**Comment by nicupavel** [comment]
I know about this issue but I always thought the fix should be done in the .MAP files(using the pg2 editor), at least this is how I've done it until now.

**Comment by salexgit** [comment]
Hi Nicu

I saw quite many .MAP files with "dummy" values for the number of rows and
columns. As for me this is not a bug in .MAP files, but rather a feature of
its format. Luis Gusman documentation on the .MAP fomat even says that
these field values should be ignored, which makes sense from the viewpoint
of the fact that .MAP file always has information for all the 40×45 hexes.

Suppose that mapconvert.py file does not account for the number of rows and
columns in the header and always reads information on all the hexes. Then,
since hexes outside the map area should be empty containing no information,
the corresponding output .XML file will have no entries either. That is the
reason why I thought we anyway need to fix mapconvert.py file, whereupon
possible fixes are:
- account for the number of rows and columns in the header only when
non-dummy values are provided, as my patch does; or
- just read and process all the hexes ignoring those header fields, as the
documentation suggests.

You can of course also "fix" source .MAP files, but I find this approach a
bit strange. As people use to update and enhance existing .MAP files, we
will resort for fixing .MAP files every time when new files are released.
