### ISSUE TITLE
CPU range is completely gone in Russia Campaign

### ISSUE THREAD

**Issue by hahnicity** [nicupavel/openpanzer#142]
My problem when I play the Russia Campaign is that the CPU basically can hit any one of my pieces from any tile location. I just had a recon unit at the enemy front lines shoot at my artillery which was located all the way behind my lines. This has happened a lot on this campaign, and normally it doesn't bother me too much, but since everything dies so quickly in the russia campaign its frustrating to lose all my units because of CPU hacks.

**Comment by salexgit** [comment]
Hi

Cann you please more specifc which unit and in which scenario hits your unit from any location? It sounds a bit weird...

**Comment by Lutarp** [comment]
I have had this problem occasionally on all sorts of missions. The unit type is not specific nor is the scenario, but I feel the problem has to be with a possible glitch in an AI instructing a unit to move then attack, but move not going through, as the range at which an attack hits seems to farther with mechanized units.

**Comment by nicupavel** [comment]
This happens after a player unit had retreated from an AI attack. The AI won't recalculate the path to reach the new unit location and will fire from current location as it had moved in the player unit range.
