### ISSUE TITLE
Redirect from Fall Weiss Campaign to Das Reich campaign following update

### ISSUE THREAD

**Issue by Lutarp** [nicupavel/openpanzer#143]
I am new to this community, and following the update to 2.9.8, a loaded save of the Bzura Counterattack when won redirected me for some reason to a mission in the Das Reich campaign, French Push North. I kind of shrugged in resignation and kept playing, but even after crushing the entire french force, including the hidden boat, the game still resulted in a loss and continued me on the campaign path of Das Reich to Closing in on Dunkirk. This was from a downloaded save.

**Comment by salexgit** [comment]
Hi

Can you upload here a saved game, Bzura Counterattack, just before you take the final victory hex? I want to double check whether it is a common problem. Obviously, this is a bug and should be fixed.

**Comment by Lutarp** [comment]
I do not have a save before the capture of the final victory hex, but I am playing through the save again to see if the issue repeats.

**Comment by Lutarp** [comment]
I uploaded the save to the other thread opened, please check it there

**Comment by salexgit** [comment]
Closed because the same issue is reported in #145.
