### ISSUE TITLE
Operation Uranus, and some following Russian scenarios glitched

### ISSUE THREAD

**Issue by Lutarp** [nicupavel/openpanzer#144]
Operation Uranus, both in campaign and in scenario experience seemingly a failure to load map information on only certain computers. This is not reflected in the network that the computer is connected to, but merely certain computers. The map loads a reflected image of the normal map, units cannot be selected, or selecting them causes them to disappear, or move to the reflected area on the map, but the background does not reflect with them

**Comment by salexgit** [comment]
Hi

Can you be more specific on what exactly happens and under which circumstances? I tried to load "Operation Uranus" scenario on both computer and a mobile phone, it works fine.

**Comment by Lutarp** [comment]
It wasn't an issue between mobile and computer, but computers in general, I
can send some images in

**Comment by Lutarp** [comment]
![screenshot 9](https://user-images.githubusercontent.com/16502495/45820394-adc05b80-bcb4-11e8-9f99-04746e664463.png)
![screenshot 8](https://user-images.githubusercontent.com/16502495/45820404-b6b12d00-bcb4-11e8-8c51-86a407bc3ff9.png)

**Comment by Lutarp** [comment]
Understood, thank you. This makes sense considering the computer I used
where it worked did not have ad block installed.

**Comment by Lutarp** [comment]
Just a question on the overall game, but what does one turn encompass in terms of timeframe?

**Comment by nicupavel** [comment]
Depends on the campaign being played. The date is written on turn details (click/tap on the top bar to check the date). For example on Fall Weiss 1 turn means 2 days.

**Comment by salexgit** [comment]
Hi Lutarp

As Nicu commented, each scenario has a parameter that specifies how many days every turn is. However, it does not have any impact on the game functionality, as far as I am aware of. This is merely for information and to make some scenarios as close as possible to real historical events.

Regards, Alex
