### ISSUE TITLE
Not all sound effects are played on the mobile app

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#150]
Hi

Not sure whether this problem existed in 2.9.7 mobile app, but it does for 2.9.8 Android mobile app version.

In short, suppose that there is the following sequence of events:
1. Unit A decides to attack enemy unit B
2. Enemy unit C provides support fire
3. After that unit A attacks B and B fights back

While the online browser version plays properly sounds for events 2 and 3, the mobile app version plays only 2. The same problem occurs when e.g. unit A attacks unit B, and the latter surrenders with no "death" sound played.

No idea whether the same problem occurs in iOS.

**Comment by nicupavel** [comment]
Looks like android webview doesn't like multiple sound files being queued

**Comment by salexgit** [comment]
Hi Nicu

I investigated a bit this issue... 
I installed the previous v2.9.0 APK on my mobile phone - and there are no issues with the sound at all. In other words, whatever the root cause of the problem is, it is not in the core libraries coming with the operating system, but rather in the application itself (or additional libraries it comes with).

**Comment by nicupavel** [comment]
Yes the 2.9.0 apk included a chrome version tailored for our needs which was difficult to maintain and was removed in 2.9.8 which uses the OS WebKit libraries.

**Comment by salexgit** [comment]
Hi

Thanks. I could not help but wonder whether it is a bug or a feature that Android Webview does not support queuing of multiple sound files. It should be quite basic functionality.

**Comment by nicupavel** [comment]
Fixed in next beta version but there might still be issues on certain Samsung phone/tablets.

**Comment by salexgit** [comment]
Hi Nicu

If you have beta apk, then I could test it on several different Samsung devices.
