### ISSUE TITLE
Weird save Game bullshit on app

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#151]
On Xiaomi MI Max 2 MIUI (android)

Got what ever reason I can't upload the video here
It's a zip but it's 96.5mb
Perhaps I could email it to someone?

**Comment by nicupavel** [comment]
Upload as private video on youtube and send us the link

**Comment by LaughtersGrave** [comment]
https://youtu.be/kCJL8NoivMU

Did this work?
