### ISSUE TITLE
Spontaneous range issue

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#153]
Ongoing issue with range

Sevral times a turn in finding it really fucking annoying when a 1 hex range unit suddenly develops a 3 hex range. Examples polish piechota shooting a retreated infantry unit from 2 hexes away, Belgian chassures shooting my artillery from 3 hexes away while remaing entrenched in a city.

**Comment by LaughtersGrave** [comment]
![screenshot_2018-10-27-20-49-44-288_com android chrome](https://user-images.githubusercontent.com/44041995/47608774-1bd20e00-da2b-11e8-90d1-b9945cbcae4c.png)

Yes, that's just a normal Belgian chassures unit.

**Comment by nicupavel** [comment]
Yes it can happen the order shown it's not always correct.
