### ISSUE TITLE
Outdated MAP file for "Student" and "7th French Army rush North" scenarios

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#154]
Hi Nicu

This issue was spotted during #148 discussion. For some strange reason (not sure how it is possible) the DasReich campaign was regenerated with outdated DR2SCHOLL.MAP file that holds terrain data for "Student" and "7th French Army rush North" scenarios. As a result, some terrain data is incorrect. The biggest problem however is that hex at (33.40) is marked as "impassable river" making it impossible to cross the river, even though there is a bridge. Note that 2.9.7 did not have this problem.

The way to fix is to take the latest DR2SCHOLL.MAP (ID 327) from Gilestiel's website. I regenerated Student scenario with the latest MAP file, and as you can see now it looks as it should be. You can cross the river where the bridge is.

![student](https://user-images.githubusercontent.com/22852936/47609946-9c0b6a00-da51-11e8-8e26-4284818d2944.png)

**Comment by nicupavel** [comment]
You can do it to the previous branch, but make sure it doesn't break anything else by generating the XML and inspecting the diff.

Thanks!

**Comment by nicupavel** [comment]
Fixed in 2.9.9-2
