### ISSUE TITLE
OP NAVY UNITS (Not sure if this is deliberate or not) 

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#157]
Ok so there are not many scenarios with naval units but they few I've faced so far have naval units being really over powered.

In each encounter my very highly skilled, leader upgraded (additional 2 damage) and numerous (I've got 8 bombers) have been only able to deliver 1 damage at a time. Only 1.

I've tried numerous different bombers, I even bought the ju87 - C as it has the biggest naval attack value, even that could only do one at a time. 

I attacked it with multiple different artillery units and they all only did 1 at a time

I used submarines, I used destroyers, I used embarked units (just to see) and they all did only 1 at a time

It seems to me that there's something wrong with the code, it shouldn't take 4 turns with 4 different attacks doing either 1 or 0 to bring down a single Italian destroyer.

I have found this issue is also with German artillery under 15cm, it nearly always does 1 or 0 damage, which makes no sense given how lethal artillery was historically. I'm not saying a 10.5cm is huge but it's still pretty big and should hammer infantry in the open. 

Anyways it must occurred to me this night be a value mistake embedded in the code so I thought I'd report it. 

Great work on this game nicu. It's getting better all the time.

**Comment by LaughtersGrave** [comment]
Additionally AT guns are seemingly OP vs artillery and infantry

**Comment by nicupavel** [comment]
Think I found the issue, naval units attack/defense were not correctly setup.
Thanks
