### ISSUE TITLE
Student Scenario - has anyone been able to get a Brilliant Victory?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#161]
In the Student Scenario (or Campaign), has anyone been able to get a Brilliant Victory?

**Comment by LaughtersGrave** [comment]
Yes

**Comment by LaughtersGrave** [comment]
What would you like to know?

**Comment by barsoom1717** [comment]
What did you do (in broad terms).  I can get a Victory, but not Brilliant Victory (as a Scenario).  It would seem even harder to get a BV in the Campaign, since you get a lot more prestige in the Scenario version.

**Comment by LaughtersGrave** [comment]
Land your large para in the major objectives that you can, nice spare para towards rotter dam.

Use your bombers. To eliminate the genie units as they move northwards towards coast. That coastal major objective is the hardest to hold. 

The way I did it was to move the spare strength 4 para from the far north to reinforce them, I landed them between my major objective and the Dutch mortars. 

I targeted his at gun on the coastal major objective first, that way it retreated into the major city with only 1 hp and it's a lot easier to get rid of than entrenched infantry in the city. Bomb it then attack it with your high strength paras on turn 1 then it will fall back into the city, you're set at that point. 

The fighters should move over the ocean to the north west of the farthest north major objective, I found a major group of air units there. The Dutch airforce is surprisingly good. Luckily I had 2 FW 190 A-3 which were helpful.

If you land all paras properly there should only be 2 uncaptured major objectives, don't worry about the middle one too much, support it with air power, there will be enough reinforcement there that if you do it right you won't need extra units there from turn 1.

The coastal major objective is by far the hardest, it took me every move of the four turns using bombers to eliminate his artillery first, then his mortars, then the infantry. 

The big problem is his AA around that area. 

If you did it right all enemy air should be dead by turn 2, use the spare fighters you have left to shoot at really entrenched units to lower their entrenchment. Also use them around the enemy AA to make it run out of ammo.

By turn four you should only have the coastal place to worry about, basically just be smart, when the at gun is low on hp from bombing it should retreat, at that point you capture the last major objective and boom, done.

You might have to direct some air power towards the two factories on the river to kill his recon there or the attacking infantry, be aware that there is a big AA gun there though.

You must be prepared to sacrifice your none core air units, particularly fighters. 

When I did it the map was set up wrong so none of my core units but air took any part, the rest were stuck in the marshes.

**Comment by LaughtersGrave** [comment]
Not sure if this helps

[(Campaign) Student Turn 3 Fri Oct 19 2018 02_14_46.zip](https://github.com/nicupavel/openpanzer/files/2550955/Campaign.Student.Turn.3.Fri.Oct.19.2018.02_14_46.zip)

**Comment by barsoom1717** [comment]
Thank you for the help.  Where were those fighters (the FW A-3's)?  I just flew an Me109 out to the fartherest NW point it could go but found no other fighters there.  Are they there in a later turn or turn 1 (which is where I looked for them).

Stephen

**Comment by LaughtersGrave** [comment]
They were there turn 1

You have some aircraft at (5,19)

Their air is at (3,13), (3,14), (4,14), (3,15)

The FW190 A-3 I got for a brilliant victory from the last scenario, once you have 1 you can buy more if you wish. 

I am currently at operation Typhoon and I have:
3 10.5 LeFH 18 
5 21 K38 (you get these as reward for brilliant victory) 
6 Sturmpioneer in H830B (buy landwher then upgrade its the fastest transport) 
3 SS Infanterie in blitz 1t (I'm reluctant to upgrade until there is something better, I was toying with kosaken or kradschutze but it's not really worth it until krads become all terrain or something better comes along) 
1 2 flak 38 still in its mule cart until I can upgrade the transport first I'm just using this to capture secondary objectives or hold majors) 
1 psw231 (8) (which I was thinking of upgrading into psw222 pak41 but its very ineffective against infantry if you do so I haven't yet, waiting for something better, it does its job anyway) 
4 Panzer VI (tiger 1)

Annnndd my air force, which is where I really concentrated most of my prestige:
8 HE-111-H-3 Bombers (until something with a much better soft and hard attack comes along these really are the best bombers, they have 18 movement and they're cheap for a bomber) 

7 FW190 A-3 Fighters I think I bought 2 of these and the rest were for brilliant victories.

**Comment by salexgit** [comment]
Hi all

I read some historical materials on the battle of Netherlands and Rotterdam, it seems that Dutch defences had pretty good AA guns as they were able to hit/damage quite many aircrafts with German paratroopers. Germans had some success around the Rotterdam bridges, but it was almost a complete failure around The Hague. In that sense the scenario is correct - taking The Hague and areas north to Rotterdam are quite challenging.
At the same time, I was not able to find any records of strong Dutch airforces, especially fighters. Dutch used several bombers during the battle of Rotterdam while trying to eliminate German bridgeheads, but no fighters. 

So, maybe the scenario indeed has to be readjusted a bit to remove Dutch fighters or make them weaker.

Regards, Alex

**Comment by barsoom1717** [comment]
Interesting points, especially about the AA.  I remember I looked up both of the Dutch fighters.  One type only had a couple of prototypes, while the other had a few more built, but still not like the swarm you get hit with in the game.




Get Outlook for Android







On Wed, Feb 6, 2019 at 8:49 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi all


I read some historical materials on the battle of Netherlands and Rotterdam, it seems that Dutch defences had pretty good AA guns as they were able to hit/damage quite many aircrafts with German paratroopers. Germans had some success around the Rotterdam bridges, but it was almost a complete failure around The Hague. In that sense the scenario is correct - taking The Hague and areas north to Rotterdam are quite challenging.

At the same time, I was not able to find any records of strong Dutch airforces, especially fighters. Dutch used several bombers during the battle of Rotterdam while trying to eliminate German bridgeheads, but no fighters.


So, maybe the scenario indeed has to be readjusted a bit to remove Dutch fighters or make them weaker.


Regards, Alex

**Comment by salexgit** [comment]
Hi

Here is the link to one of the articles on Wikiedia, which provides quite good details on losses. 
https://en.wikipedia.org/wiki/Battle_of_the_Netherlands

Referring to the aforementioned link, "Dutch anti-aircraft batteries shot down numerous Ju 52 transport planes of the Luftwaffe's Transportgruppen. German Ju 52 losses in the entire battle amounted to about 250, representing 50% of the fleet's strength".

**Comment by barsoom1717** [comment]
That is some very high losses.




Get Outlook for Android







On Wed, Feb 6, 2019 at 9:25 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


Here is the link to one of the articles on Wikiedia, which provides quite good details on losses.

https://en.wikipedia.org/wiki/Battle_of_the_Netherlands


Referring to the aforementioned link, "Dutch anti-aircraft batteries shot down numerous Ju 52 transport planes of the Luftwaffe's Transportgruppen. German Ju 52 losses in the entire battle amounted to about 250, representing 50% of the fleet's strength".

**Comment by barsoom1717** [comment]
I guess on the AA part the game id pretty accurate.




Get Outlook for Android







On Wed, Feb 6, 2019 at 9:25 PM -0600, "salexgit" <notifications@github.com> wrote:












Hi


Here is the link to one of the articles on Wikiedia, which provides quite good details on losses.

https://en.wikipedia.org/wiki/Battle_of_the_Netherlands


Referring to the aforementioned link, "Dutch anti-aircraft batteries shot down numerous Ju 52 transport planes of the Luftwaffe's Transportgruppen. German Ju 52 losses in the entire battle amounted to about 250, representing 50% of the fleet's strength".
