### ISSUE TITLE
First strike

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#162]
I'm not sure about this since what I understand might not be 100% since there is no wiki to check this against, but I'm not sure first strike is functioning properly.
It's the leader ability infantry can get. 
Perhaps someone could explain to me how it works so I can check it against what I know. For example where am I looking at the wrong symbol for initiative? 
How does experience effect initiative? 
Why is first strike better than aggressive attack. 

Understanding how they stack up I'll look on my game and compare it to what should be happening. 

But basically my ss infanterie with first strike leader should be attacking before his T34 based on my (potentially wrong) understanding.

Anyone help me here so I can double check

**Comment by LaughtersGrave** [comment]
@salexgit any thoughts?

**Comment by salexgit** [comment]
Hi

I need to check source code to answer your question :) 
I saw some explanations on other forums how it woks, but I am not sure whether OpenPanzer follows exactly the same model.

**Comment by LaughtersGrave** [comment]
@salexgit Did the source code reveal anything?

**Comment by salexgit** [comment]
Hi

I have been on a business trip and did not have time to check the code. Well, I glanced at the code but I did not get immediately what it does because there are a lot of things accounted for: leader capabilities such as first strike, units' entrenchment level,  terrain entrenchment bonus, etc.

**Comment by salexgit** [comment]
Hi

Even though the question was asked long time ago, I hope that the following page will provide an additional insight on how "initiative" works.
http://luis-guzman.com/OpenGen_Combat.html#EvalIni

However, I am not entirely sure whether OpenPanzer follows exactly the same calculations.
