### ISSUE TITLE
Minor issue with T. O. T Bunkers

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#165]
![screenshot_2018-11-11-02-09-40-778_com android chrome](https://user-images.githubusercontent.com/44041995/48308220-0db9dc80-e557-11e8-8095-92b8d0a2e643.png)

They've been incorrectly labelled D. O. T in the game. Also the bunker icon on the game map should have a T26 turret on it with an F-32 or other inferior gun on it.

Not a game breaking issue, but just something I thought you'd want to fix for historical reasons.

**Comment by salexgit** [comment]
Hi

Not really.... D.O.T is a rough transliteration from Russian Долговременная Огневая Точка, which generally refers to any kind of long-term fortification ranging from only machine guns to heavy guns. Take a look at the following link and you will see that the first picture looks similar to the icon in the game. 
https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BE%D0%B3%D0%BD%D0%B5%D0%B2%D0%B0%D1%8F_%D1%82%D0%BE%D1%87%D0%BA%D0%B0

There are of course other DOT types with e.g. T-26 turrets.

**Comment by LaughtersGrave** [comment]
It's the wrong translation though comrade.

Tankovaya ognievaya totshka T.O.T 

On the link you pasted there is this picture
![screenshot_2018-11-11-14-58-45-737_com android chrome 01](https://user-images.githubusercontent.com/44041995/48314539-e3056d80-e5c2-11e8-8f76-388761dbc974.png)
See where it says BOB That's Cyrillic for T.O.T

Here's a clear picture 
![screenshot_2018-11-11-14-55-02-847_com android chrome 01](https://user-images.githubusercontent.com/44041995/48314551-11834880-e5c3-11e8-9d1a-b7e0f022e4d9.png)

Here is a book about moltov and stalin line fortifications
https://books.google.ie/books?id=e0XjBAAAQBAJ&pg=PT59&lpg=PT59&dq=molotov+line+T.O.T+fortification&source=bl&ots=-daJWGhOpG&sig=nVnxI8ZOXeqUmJkZMvMfkWaCkio&hl=en&sa=X&ved=2ahUKEwjLgILGy8zeAhUiNOwKHdu6BegQ6AEwEHoECAcQAQ#v=onepage&q=molotov%20line%20T.O.T%20fortification&f=false

The bunker in the picture you linked is missing the T-26 turret, that's what makes a T.O.T (it has a tank turret) and a bunker (which is a stand alone hard point)

Not trying to be an arse hole here, just trying to help. 

I'm not an expert, but I have lived around WWII my whole life thus far (a detailed historical knowledge is necessary for my work)

**Comment by salexgit** [comment]
Hi again

I am afraid that the confusion comes from the fact that there are two abbreviations: DOT and TOT. The screenshot you shared shows clearly DOT (not TOT), which as I noted earlier stands for the general type of the long-term fortification. So, I cannot see any discrepancy here... am I still missing something?

I cannot recall whether OpenPanzer really uses TOT abbreviation for Soviet heavy artillery turrets; and there is no dedicated icon for that either. If I remember right, there is a generic "heavy artillery bunker" icon used for these purposes.

**Comment by LaughtersGrave** [comment]
Every picture I posted is tot and even labelled as such. 

Source material:

Book Osprey military histories, subject stalin and the molotov lines:
https://www.google.ie/url?sa=t&source=web&rct=j&url=https://the-eye.eu/public/WorldTracker.org/World%2520History/World%2520War%2520II/Osprey%2520-%2520Fortress%2520077%2520-%2520Stalin%2520and%2520his%2520Molotov%2520lines.pdf&ved=2ahUKEwjR3rOK7szeAhUB2KQKHaI3CQUQFjAYegQIBRAB&usg=AOvVaw3auXSJGga01aTENCJHLqk9

Neil Short and FSG are the foremost authorities on such structures.

Not once is there a mention of a DOT Bunker but there are at least 2 mentions of the TOT.

The bunker shown in my earlier screen shot in game is both a graphical and nomenclatural misrepresentation of the T.O.T type fortification. There is no such thing as a D.O.T comrade, promise.

![screenshot_2018-11-11-17-54-01-693_com google android apps docs](https://user-images.githubusercontent.com/44041995/48316478-07217880-e5dc-11e8-8231-dc2ef60ffc91.png)

A strandard type bunker of Russian design would be either a Masket or a Moskit

![screenshot_2018-11-11-17-41-04-574_com google android apps docs](https://user-images.githubusercontent.com/44041995/48316431-6b900800-e5db-11e8-893b-823aac2c9853.png)

**Comment by salexgit** [comment]
Hi

Hm, I am not sure which nomenclature English sources use but if you refer to Russian sources, then you will see that most of them use DOT (ДОТ in Cyrillic alphabet), which is a generic term that stands for the "long-term fortification". Take a look at the following link (in Russian) and you will see a lot of ДОТ abbreviations.
https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BE%D0%B3%D0%BD%D0%B5%D0%B2%D0%B0%D1%8F_%D1%82%D0%BE%D1%87%D0%BA%D0%B0
And sometimes Russian sources use TOT (spelled in the same way in Cyrillic alphabet) to refer specifically to the long-term fortification equipped with tank turrets. 
I wonder why English sources do not mention DOT, maybe they got lost in translation :)

So, the screenshot from the game is absolutely correct showing DOT and a basic bunker without any tank turret.

**Comment by salexgit** [comment]
Hi

Speaking specifically of TOTs, OpenPanzer does not have a nice icon for Soviet bunkers with T-26 tank turrets. This definitely should be added at some point.

**Comment by nicupavel** [comment]
If you find a nice icon on open general icon DB let me know and I'll include.

**Comment by salexgit** [comment]
Hi

Here is the list of "fortification" icons from the OpenGeneral DB. 
http://www.open-general.com/icons.php?oii=&oid=bunker&oic=&oit=&oin=&oih=&ois=&oia=

I did not have time to scan all of them, but some of them look similar to Soviet TOT bunkers.
