### ISSUE TITLE
How to upgrade units?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#166]
Is it possible to upgrade units (like upgrade a PZII to a PZIV)?  If so how do you do it.  When i use the Wrench button, it just seems like I can purchase but not upgrade.

**Comment by LaughtersGrave** [comment]
When you have selected the unit the list of the same type of unit pops up, for example if you select a bomber at the top the list of other bombers comes up. You can then select the type you want to upgrade it to and you'll see a button with cogs on it pop up, that's the upgrade button, press that and you pay the prestige and your unit is upgraded.

![screenshot_2018-11-11-15-26-02-077_com android chrome](https://user-images.githubusercontent.com/44041995/48314783-62e10700-e5c6-11e8-832c-62ab45746465.png)
The round button on the left at the bottom is the purchase and deploy icon, the round button on the right at the bottom, next to the purchase and deploy icon, is the upgrade icon.

**Comment by nicupavel** [comment]
Thanks for helping out ! On your screenshot I notice that there is a lot of unused space, you can enlarge the equipment windows from Settings > Interface width.

**Comment by LaughtersGrave** [comment]
Yes, I have a big phone though, so it is easy enough for me :)

**Comment by barsoom1717** [comment]
OK, I understand now.  However for some reason it won't let me "upgrade" a He-111 to a Ju87C-1 (which I guess would be technically a downgrade) even though the Ju87 has a must higher attack value for ships - which is what I need for the Untermehmen scenario/game.

**Comment by LaughtersGrave** [comment]
I understand I have/had the same issue.

Is your fighters combined with fighting within range of your land based artillery. If you get their ships right up to the coast attack with infantry. I did not damage in 1 shot from infantry to one of his three cruisers. 

Then close in behind with your uboats. 

Or ignore his navy all together. Up to you.

**Comment by LaughtersGrave** [comment]
Salexgit did say that they're going to try to fix this issue in the next update

**Comment by salexgit** [comment]
Even though the game does not support "downgrade" functionality, it is possible to sell a particular unit and buy a new one. This issue is closed.
