### ISSUE TITLE
Game unplayable

### ISSUE THREAD

**Issue by nel750** [nicupavel/openpanzer#167]
I’m on iOS 12.1 on an iPhone 7, but this also replied to iOS 12. Every time I open the game, it shows up in landscape mode but acts like it’s in portrait mode. Half of the screen is completely black, and the other half is only half of the game. This renders the game completely unplayable. I used to play this and loved it, and decided to redownload it a few days ago. Please help?

**Comment by nicupavel** [comment]
Until I make a iOS update you need to open app (it will show broken), press home button, then open app again while holding phone in landscape mode.

**Comment by nel750** [comment]
Thanks.
