### ISSUE TITLE
Experimental reward units

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#168]
Hello
Is there a list of experimental units as rewards for brilliant Victories? 

I'm getting the same unit for maadi after map for a while then it changes.

I'd really like to see the list of the is one. 

Cheers and thanks. 

It might just be luck and not an issue so I'll check it if you can post the list.

**Comment by salexgit** [comment]
Hi

I think it is just a "luck" that you get the same unit. Unless there is a weird flaw in the random number generator, you should be getting different units. You can experiment by having a saved game right before capturing the last victory hex.

**Comment by LaughtersGrave** [comment]
I've tried that and found I got some different stuff with some items coming up more often than others.

Is there a list of these reward units?

**Comment by salexgit** [comment]
Hi

I do not know details of how the game engine selects the reward unit. I got an impression that it simply compiles a list of "experimental units", i.e. the ones which you cannot buy yet, and then chooses randomly the one from the list.

**Comment by LaughtersGrave** [comment]
There must be serval lists because it changes by year.

Do you know where these lists are? Can you screen shot maybe?

**Comment by salexgit** [comment]
Hi

The list is not hard coded but is rather compiled dynamically depending on the year when the scenario ends.

**Comment by LaughtersGrave** [comment]
Ok cool, let's work with that, can you tell me what's on it? I mean that's got to be interesting.

**Comment by salexgit** [comment]
Hi

I am not sure I got the question.... Without having looked at the actual code, my understanding is that once a scenario ends with a brilliant victory, the game engine compiles a list with "experimental" units (i.e. all the units of a particular nation that you cannot buy yet) and picks randomly a unit from that list.

**Comment by LaughtersGrave** [comment]
It isn't quite that, because the list definitely changes.

So far I've been through three distinct lists. 

I imagine each year has its own list of experimental units, so I'm theory there are 6 lists. 

What I'm asking, is can you find these lists and the units on them? It must be referencing a unit file somewhere so if there is a code for it then you'd just have to screen shot the code.

**Comment by salexgit** [comment]
Hi

The best I can do (at the moment) is to share the internal JSON file that contains all the German units. There are fields determining year/month when a unit becomes available and when it expires. So the game engine uses this equipment file to compile dynamically a list of reward units depending on when you have a brilliant victory.

[equipment-country-8.zip](https://github.com/nicupavel/openpanzer/files/2583294/equipment-country-8.zip)

**Comment by LaughtersGrave** [comment]
Thank you.

There are definitely experimental units that you can never buy though, certain recon units come to mind, Italian units (i) it's not important of course but it's just very very helpful. Particularly when it can be referenced.

Thanks again

**Comment by LaughtersGrave** [comment]
Ok So I'm in 43 in the Das Reich campaign, there are only 2 missions in 42

And one of the weird units you get in 43 ties in with what we were talking about in regards to flak weapons.

![screenshot_2018-11-15-02-50-22-322_com ecosia android](https://user-images.githubusercontent.com/44041995/48527154-1590be00-e882-11e8-9bbc-993a57fd6242.png)

I tested it and it CANNOT attack ground units

![screenshot_2018-11-15-02-51-26-107_com ecosia android](https://user-images.githubusercontent.com/44041995/48527192-43760280-e882-11e8-921a-e3dd12385473.png)

**Comment by salexgit** [comment]
Hi

I am not sure what the issue. The fact the 12.8 Flak 40 cannot attack ground units was discussed in #147, where I indicated that the game engine and the equipment files have to be polished because not all the Flak units are modelled internally as "flak". That problem has nothing to do with the fact that the same  unit can be provided as a reward :)

**Comment by nicupavel** [comment]
The prototype award "algorithm" is quite simple:
1.  a list of units is generated that contain units from classes that can be purchased by player (no forts, naval units etc)
2. units must have available date between 1 and 11 months from the date  of the *next* scenario (not the one just won)
3. units must cost more than 200 prestige
4. a random unit is returned to player.

**Comment by salexgit** [comment]
Hi

According to the following link, 12.8 Flak 40 were in service 1942-1945. So you are partially right that the equipment file is not correct.

**Comment by LaughtersGrave** [comment]
I don't see the link but I checked my reverence book and you're right, they only started production in 1940 but no units were completed until 42, there were 6 mobile 12.8 flak 40 produced in the whole war.

**Comment by salexgit** [comment]
Hi

It seems I forgot to post the link, here it is:
https://en.wikipedia.org/wiki/12.8_cm_FlaK_40

Did you source mention how the mobile units were designed? I only heard about rail cars for 12.8 Flak 40 due to its large weight.

**Comment by LaughtersGrave** [comment]
These are the same flak that was mounted on the flak towers in Berlin in twin flakzweiling mounts when the 50cm took so long to develop they abandoned it and decided on two 12.8 instead, famously they're said to have "blasted Russian tanks to dust, especially when they were hitting the side".

**Comment by LaughtersGrave** [comment]
Unfortunately the book doesn't say, it just said that 6 mobile units were made. I'll see if I can find some more information for you.

**Comment by LaughtersGrave** [comment]
![img_20181129_010335_hht 01](https://user-images.githubusercontent.com/44041995/49192399-c7e07f00-f372-11e8-80d7-dd90ccc34b6f.jpg)

**Comment by LaughtersGrave** [comment]
Railway mounts are static mounts.

For the mobile version in game just limit it to the biggest half track.
