### ISSUE TITLE
Smolensk - Crossing the Dnepr: some units can't move after being deployed

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#170]
I am having an issue where some of my units can't be moved, even after the next turns, after they are deployed.  It seems right now that it is mainly some of my FW 190s, although there is also a tank and possibly some He-111s that are also having this issue.  I am playing this scenario in Firefox.

**Comment by marcofango** [comment]
Empty gasoline at the beginning of the scenario?

Il giorno ven 16 nov 2018, 08:15 barsoom1717 <notifications@github.com> ha
scritto:

**Comment by salexgit** [comment]
Hi

Can you upload the saved game here?
