### ISSUE TITLE
Panzer grenadiers 

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#171]
When a unit is upgraded to panzer grenadiers they have no fuel. Even though they are upgraded before being deployed.

![screenshot_2018-11-17-00-05-58-259_com ecosia android](https://user-images.githubusercontent.com/44041995/48653385-b30ffd00-e9fc-11e8-993b-b64d77a8ed8e.png)

![screenshot_2018-11-17-00-06-04-144_com ecosia android](https://user-images.githubusercontent.com/44041995/48653400-d470e900-e9fc-11e8-9423-934413c2c08f.png)

**Comment by salexgit** [comment]
Hi

I noticed the same issue, but I did not have time to check whether it is a bug or a feature. If I recall right, I observed same behavior in several other cases while upgrading units.

**Comment by LaughtersGrave** [comment]
I found it happened when ever a unit with no fuel, like a leg unit, is upgraded to a unit that requires fuel, such as a half track.

**Comment by salexgit** [comment]
Hi

Yes, that is also an impression I got: it happens in those cases when you upgrade to something requiring fuel. So, maybe it is a feature, but @nicupavel can clarify.
