### ISSUE TITLE
Operation Zitadelle dissappearing units

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#174]
No idea why but every time I select a unit certain sections of my forces and the ussr forces simply dissappear off the map, if I select a different unit and things come back the numbers underneath appear backwards. I've tried to play through it by just remembering the hexes, it doesn't work, I've tried playing around it by moving one unit from each side of the map to see if one cancels the other (spoiler, it doesn't) so now is the end of my campaign. I can go no further. I am a bit disappointed having done all that only to be stopped by a stupid glitch. 

![screenshot_2018-11-19-19-15-31-052_com ecosia android](https://user-images.githubusercontent.com/44041995/48729546-be973a00-ec2f-11e8-85f3-d59dd285faa9.png)
![screenshot_2018-11-19-19-15-36-859_com ecosia android](https://user-images.githubusercontent.com/44041995/48729762-4da45200-ec30-11e8-83ab-067ea95ebc2f.png)
![screenshot_2018-11-19-19-15-41-820_com ecosia android](https://user-images.githubusercontent.com/44041995/48729808-762c4c00-ec30-11e8-8ecf-fc7cb93f3e92.png)
![screenshot_2018-11-19-19-16-11-371_com ecosia android](https://user-images.githubusercontent.com/44041995/48729855-9f4cdc80-ec30-11e8-8f18-af53ecbb3c4e.png)
![screenshot_2018-11-19-19-16-21-943_com ecosia android](https://user-images.githubusercontent.com/44041995/48729906-c73c4000-ec30-11e8-8223-39a6e8d64f4a.png)
![screenshot_2018-11-19-19-16-30-748_com ecosia android](https://user-images.githubusercontent.com/44041995/48729987-f5218480-ec30-11e8-9056-f32c0f78560d.png)

**Comment by LaughtersGrave** [comment]
If so why not on any other mission?

I don't think it is based on the fact I have no ad blocker installed that I'm aware of. This is on android miui system

**Comment by LaughtersGrave** [comment]
I used the cloud and ran it in the app, works now

**Comment by nicupavel** [comment]
Only soviet campaign have some units named with adXX.png.

**Comment by LaughtersGrave** [comment]
Ok. I'll keep an eye out for that.

For now I just have to play it in the app as it DOES NOT work at all on the browser or beta

**Comment by barsoom1717** [comment]
I just had the same thing happen to me, although haven't tried it in the app yet.

**Comment by LaughtersGrave** [comment]
It's an issue with the beta and browser versions.

The app works fine. Save to cloud and load it into your app
