### ISSUE TITLE
Openpanzer for iOS?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#175]
Just got an iPad mini 4, and am having some save game options and the "undo" button on unit moves.  Is there s version for iOS or some trick (like a specific browser)?

**Comment by barsoom1717** [comment]
Anyone?

**Comment by nicupavel** [comment]
iOS version is now live.

**Comment by barsoom1717** [comment]
How do I get it?  Is there a link to it?

**Comment by nicupavel** [comment]
Should show in App Store updates list
