### ISSUE TITLE
Me 163 halftrack? Lol

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#179]
So I'm all for the realistic depiction of units have the "wrong" historic transport as in reality there was an awful lot of mend and make do/improvisation (like the turning of French 75mm field guns into at guns by the Germans for use in Russia) but... I don't think a rocket fighter is meant to have a half track transport... 

![screenshot_2018-12-02-00-25-15-272_com ecosia android](https://user-images.githubusercontent.com/44041995/49334242-15562980-f5c9-11e8-9a42-eaea8264676d.png)

**Comment by salexgit** [comment]
Hi

This is clearly a bug - thanks for spotting it :)) I did not even know that the game engine would display transport options for air units.
I plan to make a number of small cleanups and corrections in the equipment file, so I will fix it.

**Comment by marcofango** [comment]
It is probably meant to simulate the aircraft characteristics to be
launched, hit and fall somewhere.
From that point it has to be recovered.

Il giorno dom 2 dic 2018, 04:33 salexgit <notifications@github.com> ha
scritto:

**Comment by salexgit** [comment]
Hi all

Based on the technical data, even though Me-163 is a rocket-powered aircraft, it is still aircraft which needs airfields for take-off and landing. So it seems that those transport options are a bug.
