### ISSUE TITLE
New version, new problems

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#180]
I was so delighted that the new version came out, but my happiness was short-lived! With the new version came out new bugs as well, the most annoying  one is that now in campaign mode when you end a scenario the screen goes black and there’s nothing you can do about it, you can’t proceed or go back.
The old version did something similar to share the results but at least it had a button to continue.
Again, a VERY good game limited by this  errors, please correct it asap!
![a1f7ab81-4ffc-4373-8276-b48f371e682a](https://user-images.githubusercontent.com/45533789/49339499-05732f80-f633-11e8-86b9-30036778f286.png)

**Comment by nicupavel** [comment]
Please save to cloud and share the id here. I can't replicate this behavior.

**Comment by campaignbuff** [comment]
Mobile, Newest version of iOS on IPad Air

**Comment by campaignbuff** [comment]
2589a5bb4e8386dc2c3d3d62e4da7f9a This is a new game but the result is the same
Thanks for the attention

**Comment by nicupavel** [comment]
Thank you I have replicated, I will need to issue a fix and send it to Apple for review

**Comment by nicupavel** [comment]
Fixed and it's now under Apple review, probably it will be available in a few days. Thanks for reporting this.

**Comment by krjjrk** [comment]
Yes, I am playing on an iPad Pro and this describes the problem perfectly. Hope the apple fix is for my machine since I love your game.

**Comment by barsoom1717** [comment]
Yep, ditto.

**Comment by nicupavel** [comment]
The iOS app should be live now.

**Comment by campaignbuff** [comment]
Tank you! Now I’m very delighted 😀

**Comment by krjjrk** [comment]
Not fixed on my iPad Pro. Just played to dark end.

**Comment by nicupavel** [comment]
I could update fine to 3.0.1.
