### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by krjjrk** [nicupavel/openpanzer#181]
New update after first scenario in German campaign as soon as win the screen has pop up about victory on a dark screen that is frozen. Does not respond to move to the second scenario. Similar to old screen that had question on bottom right that you hit, but this has nothing but unit data across the bottom.

**Comment by nicupavel** [comment]
Probably related to #180

**Comment by barsoom1717** [comment]
Same thing happened to me earlier tonight.  I was playing the iOS version on an iPad.

**Comment by nicupavel** [comment]
Fixed in 3.0.1 iOS

**Comment by krjjrk** [comment]
Do you update from ap store as a regular update. It shows the right update number on the site 3.0.1 but just says open, not update and it is not listed as an update in my update list. My game is still 3.0. Thanks for all your help and hard work.

**Comment by nicupavel** [comment]
Since I also had the developer version I had to completely delete the app and reinstall. 
IMPORTANT: the game itself will still show 3.0.0 on main screen.

**Comment by krjjrk** [comment]
Thanks, I will try that.

**Comment by barsoom1717** [comment]
What is the difference between reg and developer version? Or are you referring to the beta version?

**Comment by nicupavel** [comment]
Developer version = the version that I directly install on iPhone/iPad from Apple XCode without going through App Store
