### ISSUE TITLE
Equipment file?

### ISSUE THREAD

**Issue by barsoom1717** [nicupavel/openpanzer#182]
Head someone mention working on the equipment file the other day.  Is there a way for us to view the file?

**Comment by salexgit** [comment]
Hi

In short, this is the binary file which encodes information on all the units, which can be edited with the corresponding tool provided from e.g. OpenGeneral project. OpenPanzer engine uses XML/JSON based formats, so we convert those binary files.

If you explain quickly what you would need the equipment file for, I can share JSON/XML or binary files (assuming that main developers do not have any concerns with that).

**Comment by barsoom1717** [comment]
I'll be honest it would be si I could edit strength and experience on certain units.  Are you saying the editor for Open General would work on OpenPanzer?  If this is a OG equipment file, I can look at the correct OG equip file to find what info I want.  So which OG equip file did this start out as?

**Comment by barsoom1717** [comment]
Oh, and the reason I want to edit some of the units is because in some scenarios (Student I think is the worse) "the fix is in" when it comes to enemy combat power.  As a more specific example, the enemy AA in the Student scenario are way more powerful than history tells of yhe battles.

**Comment by salexgit** [comment]
Hi

To be able to edit and experiment with unit characteristics, you need a "local" package. And the easiest way would be to do that on a desktop computer. As far as I know, this project does not release official local/offline packages for dekstops, so I prepared a set of offline packages to experiment with equipment files, test new campaigns, etc. You can visit the following website: https://sites.google.com/site/openpanzeroffline/

Once you download the package, go to "resources/equipment/" folder where you will see a number of files, each for every country, containing information on every unit. The equipment file follows the JSON format so you can modify it with any editor you like.

Regards, Alex

**Comment by barsoom1717** [comment]
Thanks so much Alex.  That is awesome.

**Comment by salexgit** [comment]
Hi

You are welcome. 
By the way, can you elaborate on the AA issue you have in the Student scenario? That scenario is challenging, but it is possible to get a brilliant victory there.

**Comment by barsoom1717** [comment]
Yes, there is numerous issues with that scenario.  I ran one little part 15-20 times, and no matter what takes place before, the computer is determined and does destroy one specific para unit.  This pap unit withstands, in good order a lot of tiimes, attacks from 3 infantry units.  When those are done an AA unit attacks (yeah, like that ever really happened, and wipes the unit out.  I've already mentioned the aircraft issue.  One small example is the D.XXIII had greater combat power than a Me109 in the game.  Historically, the D.XXIII had an advantage if you were in a mid altitude dogfight because of its turning capability.  But the 109 was far superior in armament, speed, altitude, and overall performance.  i.e. there was really no comparison between the two, yet the D.XXIII has an air attack of 13, whereas the 109 has 12.  Totally ridiculous and inaccurate.  Another fighter example is the G.1b which appears in several instances.  However history tells us there was only a single aircraft, and it was a prototype, that left the ground before the German invasion.  Finally, there is way too much enemy AA, and it is way too powerful.  Yes, I agree the scenario is winnable with a BV, but not without losing a lot of units, particularly air and paras.  It gets infuriating when the projected casualty counts show 4 losses on each side, however if you carry out the attack you lose 4 and the enemy only loses 1.  Again, this happens way too often for the AI not be rigging the result.

**Comment by salexgit** [comment]
Hi

Ok, let me segregate a bit issues...

1. AI engine is not perfect and sometimes lacks randomness. I also observed that in some cases AI would always attack a particular unit. For instance I noticed that AI aircraft would always attack bridge engineers when possible, which results in very stupid behavior especially if your bridge engineers are protected with AA guns or another aircraft. As usually, AI is the most challenging part of any game.

2. Projected casualty count is just an estimation, whereas actual outcome may vary. 

3. I did not compare D.XXIII attack power to other German airplanes, so this can be fixed.

4. Regarding too powerful AA guns, I remember that while playing this scenario you just should deploy your paratroops wisely avoiding places where they would be hit by AA guns. Historically, there were only several more or less successful German paratroop operations, most of them were failures with high losses. 

Regards, Alex

**Comment by barsoom1717** [comment]
Regarding point #4, do you try to attack enemy units or even the AA units themselves?  Or just drop the paras and move your bombers and fighters out of range, cause they are getting massacred from the AA?

**Comment by salexgit** [comment]
Hi Barsoom

What I can remember vaguely is that I tried to deploy my paratroops immediately so that they do not catch any fire from enemy AA guns. As for bombers, I did not try to attack any AA protected targets or AA units themselves, but rather moved them immediately south for easier targets. Once I advanced further with main units, I moved my bombers back to north. 

Regarding your last post on the core and auxiliary units, can you elaborate more on your question? I did not get it.

**Comment by barsoom1717** [comment]
When I say pathway I mean in the code.  Like if you looking for prestige, you go scenario>map>current player.  As I said I found the code for the core units, but not for the auxillary units you get for a particular scenario.

**Comment by salexgit** [comment]
Hi

I am still not sure whether I got the question... Auxiliary units are scenario specific in a sense that they are solely governed by the scenario  description file and do not depend on the previous scenario and/or any prestige value.

**Comment by barsoom1717** [comment]
So I would look in the scenario pathway?  Also, which of the equipment files in the offline package the ones for Germany?

**Comment by salexgit** [comment]
Hi

equipment-country-8.json is the equipment file for Germany

**Comment by salexgit** [comment]
Hi again

I forgot to mention that if you want to experiment with the Student scenario game balance, then you should consider editing the corresponding XML file, not the JSON equipment file. The easiest way to make enemy units weaker would be just to decrease the unit size, just change "str" parameter of the corresponding unit in the XML file.

Regards, Alex
