### ISSUE TITLE
Cant deploy units by defence 

### ISSUE THREAD

**Issue by PhantomBoys** [nicupavel/openpanzer#183]
Hi! I want to ask about deploying units. When i play by defence deployment hexes missing. I checked all operations, i was trying to wait, but without result.Is it bug or in this game i cant buy units by defenders? What should i do to fix this problem?

**Comment by nicupavel** [comment]
You mean you play a single scenario ? What scenario and which side ?

**Comment by PhantomBoys** [comment]
New scenario mode. Defence ( All countries). I can only upgrade units, but not deploy new, cause deployment hexes isnt showing up. I tryed all scenarios in this mode and only attack side can deploy units. Maybe i do something wrong.
P.s sorry for mistakes, i ise google translate.

**Comment by nicupavel** [comment]
You also need to press the buy button to get new units otherwise you just upgrade existing ones.

**Comment by PhantomBoys** [comment]
Of course, I bought them. When I buy units for the defense side in any scenario, I write that they can be put on the field, but the hexes themselves do not appear. The only operation where I was able to put the purchased units was a training mission.

**Comment by PhantomBoys** [comment]
For example, Huertgen Forest. Attack side:
![fi_se0ybbq8](https://user-images.githubusercontent.com/45696789/49698628-65d81300-fbd7-11e8-9131-0de426cf216e.jpg)
I bought tank and can deploy it.
Defence:
![au_kywn07tm](https://user-images.githubusercontent.com/45696789/49698667-e72fa580-fbd7-11e8-8a50-fd4dbf04ef5b.jpg)
similarly, BUT! On phone version, which I often play, this hex missed
![urf7xsznswe](https://user-images.githubusercontent.com/45696789/49698688-2eb63180-fbd8-11e8-9c5f-917a38ebea27.jpg)
And this problem in each operation at phone version.

**Comment by nicupavel** [comment]
You need to click on those grey hexes with the arrow symbol to deploy your force.

**Comment by PhantomBoys** [comment]
I can take more screenshots of another operations, if you need. Thank you, i hope this will be fixed by time

**Comment by salexgit** [comment]
Hi PhantomBoys

This a common "problem" for quite many scenarios. 
In short, most scenarios are developed for a certain campaign for a certain country assuming you will play it accordingly. In your case, the "Huertgen Forest" scenario is assumed to be played for US. There is also a way to play a particular scenario in a "standalone" mode, whereupon you can specify which side you want to take. However, not so many people test whether the scenario will work smoothly in this case. As an example, deployment hexes could be missing....

So, I would conclude that this is indeed a bug/inconsistency in the SCN file, but as I noted before this is a common issue that you might face in other scenarios.    

@nicupavel I assume that we can rename this discussion thread title to something like "Missing deployment hexes for Germans in the Huertgen Forest scenario" and label it accordingly. I would not be surprised if other scenarios in this campaign have a similar problem, so either you or me can revise them. 

Regards, Alex

**Comment by nicupavel** [comment]
Fixed in 3.1.0
