### ISSUE TITLE
Counter fire during ranged attack

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#187]
Hi

I do not remember exact PGII behaviour, but at least Open Panzer game engine will not provide any artillery support during so-called ranged attack, i.e. when the attacking unit is at distance more than 1. I find it a bit strange, especially when a tank attacks infantry and the artillery remains silent. 

I assume that the game engine has a very simple rule - no artillery support during the ranged attack. However, my view is that the rule should be as follows: if the attacking unit is within the visibility range of the unit which is being attacked, i.e. the latter can "see" the attacker, then it should be supported by artillery. 
Here are some examples: 
- Most infantry units have visiblity range of 2, so when a tank performs ranged attack at distance 2, there should be artillery support.
- Most tank units have visibility range of 1, so when another tank performs ranged attack, there will be no artillery support.
- Such an approach will automatically enable so-called counter-battery fire concept. If, as an example, a recon unit is attacked at range 3 by some enemy artillery unit and it is within the range of support artillery, then the latter will automatically perform counter-fire.

**Comment by nicupavel** [comment]
The behaviour is the same as in PG2 only close combat triggers artillery support
