### ISSUE TITLE
Missing unit images

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#190]
Hi Nicu

While converting and testing campaigns, I faced a weird problem that some unit image files are just missing in resources/units/images folder. The funniest thing is that if you open the SCN file with the EQP file from the repository, then everything works fine. However, the converted XML scenario does not work properly because the game cannot load the image file.

This problem exists at least for Slovakia country (equipment-country-1.json) - not sure whether other countries equipment files have the same issue. I made a small test script that just enumerates all the images in the Slovakia JSON equipment file and fetches them from the server. As you can see from the attached ' dump' file, quite many images are missing.

[dump.txt](https://github.com/nicupavel/openpanzer/files/2706325/dump.txt)

I am not sure about the root cause. It is really weird that there is an entry in the JSON equipment file, which means that at least it was generated properly from the EQP file, but the actual image is not there.

Regards, Alex

**Comment by salexgit** [comment]
Hi Nicu

It seems that the missing icons (at least for Slovakia) can be found at the open general searchable database in the PNG format. However, I am not entirely sure whether icons are really compatible because OpenGeneral PNG file is effectively 3x3 image file, while OpenPanzer PNG files follow 1x9 format. Do you use some script to convert them? 

Regards, Alex

**Comment by nicupavel** [comment]
Icons should be 1x9 from opengeneral svn @ sourceforge. I'm playtesting campaigns atm so I will probably find this issue soon.

**Comment by salexgit** [comment]
Hi Nicu

I have experienced this problem with Slovakia units which are in the "Rostov defense" scenario of the LSSAH campaign. Just open the corresponding scenario.

**Comment by salexgit** [comment]
Hi Nicu

Thanks for fixing the problem, at least "Rostov defense" scenario now works fine. 

As a minor related problem, did you notice that for some reason different "Slovakian" flags are displayed in the inspect window? There is a small flag displayed right next to the unit name, and it is not same flag as the main flag at right hand side. Not sure where this discrepancy comes from - original PG2 files or our side.

Regards, Alex
