### ISSUE TITLE
Basic and current unit strength

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#193]
Hi Nicu

While modifying SCN files, I noticed that each unit has two "strength" parameters: original/basic strength and current strength. Most units have basic/original strength of 10, which can be further enforced to a larger value or which can become smaller if a unit takes losses. In some scenarios units' basic/original strength is higher or lower reflecting certain historical aspects.

According to the PG2 document, basic/original strength is the value, up to which a unit strength will be reinforced when a new scenario starts. As an example, if the unit basic/original strength is 6, and it takes some losses, then in the beginning of the next scenario it will be 6 again, not 10.

Does OpenPanzer behave according to the aforementioned descriptions? I experimented a bit, and it seems that OpenPanzer just uses "current" strength parameter automatically resetting unit strength to 10 in the beginning of the next scenario. It works fine as long as all the units have a strength of 10. However, if there is a core unit, basic/original strength of which for any reason was intentionally set to e.g. 5, it will be reset to 10. I suspect that OpenPanzer does not support this concept as there is only one "strength" parameter in the XML file. Can you please clarify?

Regards, Alex

**Comment by barsoom1717** [comment]
Its also been my experience that in PG you could "overstrength" units, up to 15, however OP doesn't let you do this.  Just FYI.
    On Wednesday, January 23, 2019, 12:49:55 AM CST, salexgit <notifications@github.com> wrote:  
 
 
Hi Nicu

While modifying SCN files, I noticed that each unit has two "strength" parameters: original/basic strength and current strength. Most units have basic/original strength of 10, which can be further enforced to a larger value or which can become smaller if a unit takes losses. In some scenarios units' basic/original strength is higher or lower reflecting certain historical aspects.

According to the PG2 document, basic/original strength is the value, up to which a unit strength will be reinforced when a new scenario starts. As an example, if the unit basic/original strength is 6, and it takes some losses, then in the beginning of the next scenario it will be 6 again, not 10.

Does OpenPanzer behave according to the aforementioned descriptions? I experimented a bit, and it seems that OpenPanzer just uses "current" strength parameter automatically resetting unit strength to 10 in the beginning of the next scenario. It works fine as long as all the units have a strength of 10. However, if there is a core unit, basic/original strength of which for any reason was intentionally set to e.g. 5, it will be reset to 10. I suspect that OpenPanzer does not support this concept as there is only one "strength" parameter in the XML file. Can you please clarify?

Regards, Alex

**Comment by salexgit** [comment]
Hi

Ok, the issue is indeed more multifold than I was expecting. So:

- OpenPanzer does not support enforcing units beyond their basic/original strength. I wonder why because interface-wise it should be quite simple.
- OpenPanzer does not really support the concept of basic/original strength less than 10. All the units are assumed to have basic/original strength of 10, and thus they will be re-inforced always up to 10, even though the basic strength could be e.g. 5.

Regards, Alex

**Comment by nicupavel** [comment]
Yes basic strength is 10. I had no good reason to use the original strength, was one of the features that add more questions that actually it's worth it. 
Overstrength will be in the next beta but in a simplified form (you can always overstrength depending on unit experience). If you have a 100 experience unit you will reinforce to 11 not 10. For now it's for testing.

**Comment by barsoom1717** [comment]
That was how the overstrength worked in PG too.  If you had a unit with 500+ experience, you could overstrength them to 15.

    On Sunday, January 27, 2019, 4:06:42 AM CST, Nicu Pavel <notifications@github.com> wrote:  
 
 
Yes basic strength is 10. I had no good reason to use the original strength, was one of the features that add more questions that actually it's worth it.
Overstrength will be in the next beta but in a simplified form (you can always overstrength depending on unit experience). If you have a 100 experience unit you will reinforce to 11 not 10. For now it's for testing.

**Comment by salexgit** [comment]
Hi Nicu

The use case for keeping and accounting separately basic and current strength is as follows:

- There are some historical scenarios in which unit strength was not 10. It is especially the case for some recon units and heavy tank/artillery units, where the historical unit size was not even a battalion but rather a company. So, if you provide the core unit of say size 5, then in the next scenario it will become 10, instead of keeping it 5.

- I suspect that the similar situation can occur with overstrength units. If the overstrength unit size is 12 and it takes losses resulting in the current strength of 8, then in the next scenario the unit size will be recovered up to 10 (to be honest I am not sure what PG2 behaviour would be in this case).

As a somewhat related enhancement, if the game engine supports the concept of the basic strength, then we can allow for buying understrength units, e.g. 5. As an example, I would prefer to buy two understrength recon units instead of one full strength unit.

Regards, Alex

**Comment by nicupavel** [comment]
PG2 would always set unit strength to basic strength (usually 10) between campaign scenarios unless unit strength > basic strength.

PG2 didn't allow buying under-strength units. Concept is interesting though but I don't see a way now to add it to UI cleanly.

**Comment by salexgit** [comment]
Hi Nicu

Regarding buying under-strength units, the whole concept was inspired by reading historical documents on the structure of SS divisions. While infantry units were one or more regiments, recon units were at the level of just one battalion. Same is for some engineer and pioneer units, which were even smaller, just several companies. It would make perfect sense even in the game - I do not always need to have full-strength bridge engineers or recon units.

The way it can be implemented in UI is as follows. For the sake of simplicity, we can allow for buying just 10- and 5-strength units, so there can be two buttons for buying 10 and 5 size units.

Anyway, this enhancement will be possible only after we introduce the concept of the basic and current strength :)

Regards, Alex
