### ISSUE TITLE
Units on deployment hexes

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#194]
Hi Nicu

While designing/changing scenarios for the LSSAH campaign, I noticed one weird thing with regards to how game engine handles units which are on the deplpyment tiles.

1. If there is a unit on the deployment hex in the _first_ scenario of the campaign, then everything is fine and this unit, as expected, becomes the core unit.

2. If you just open a particular scenario, in which there is a unit on a deployment hex, then everything is also fine. The only difference is that the game engine does not really show that this unit is a core unit because it is not relevant for the non-campaign game.

3. However, if there is a unit on a deployment hex and the scenario is not the first one, the unit just vanishes. The game engine just logically erases it from the unit list, even though it does exist in the XML file.  What is the reason to have this game behaviour?

As a related comment/suggestion. Will it be possible to change game engine so that:
- units on the deployment hex are shown regardless of the fact whether it is the first scenario or not;
- if there is a unit on the deployment hex, it is added to the core unit list, irrespective of the fact whether it is the first scenario or not.

Regards. Alex

**Comment by nicupavel** [comment]
3. This is the PG2 behavior. The core army are the units on first campaign scenario on the deploy hexes.  On next scenarios you have to remove units standing in deployment hexes. 


>  If a unit stands, at start, on a hex with the deployment flag set it becomes a core unit. This is only true if the scenario is played thug a campaign, not if its played as a single scenario. And again this is only true if the scenario is the first in the campaign. All units standing on deployment hex in ALL other scenarios in the campaign, are ignored. The are not displayed and the do NOT become part of the game.

From: http://luis-guzman.com/links/PG2_FilesSpec.html#(SCN)%20file

This behavior can be used to make both sides available in a campaign.

**Comment by salexgit** [comment]
Hi Nicu

Well, you are right, that is what PG2 documentation says: "If a unit stands, at start, on a hex with the deployment flag set it becomes a core unit. This is only true if the scenario is played thug a campaign, not if its played as a single scenario. And again this is only true if the scenario is the first in the campaign. All units standing on deployment hex in ALL other scenarios in the campaign, are ignored. The are not displayed and the do NOT become part of the game."

However, I could not help but wonder about the reason for such a behavior. There is a separate "unit deployment status" parameter that control units' appearence in scenarios: 
   0 = Vanish if campaign
   1 = Not deployed (still at HQ pool)
   2 = Deployed on map
Value 0 is set by the game when scenario is played in a campaign, for all units standing on deployment hexes at start of the scenario (except the very first scenario in the campaign) and make those units vanish from the game. This is how you can use scenarios as single and in campaigns where some units are in the single version and not when play in the campaign. 

My concern is that with the current game model there is no way to assign more core units in a particular scenario reflecting historical changes to a particular division or army when e,g, more battalions are added.

Regards, Alex

**Comment by nicupavel** [comment]
Yes indeed that how PG2 worked, it would set 0 (vanish) when scenario was in campaign. The "core" army concept is about what you buy and what you start with. PG2 didn't make choices what to offer player as core units except the "awarded" random units and that was with a low probability (OpenPanzer we always award prototype with Brilliant victory). This is mostly because you don't really know what kind of core force player likes to play with.

The current system allows balancing single scenario play vs campaign play. Most of current scenarios aren't balanced in non campaign mode. This can be solved by adding units in deployment hexes.

**Comment by salexgit** [comment]
Hi Nicu

Well, if the game engine allows adding core units through explicit purchasing and random awards, then why not to allow adding core units by means of explicit assignment? For a campaign mode, it is often the case that you start with a small regiment, and by the end of campaign you might have a division or an army. It would be nice if the game engine allows for adding explicitly new core units to reflect actual historical changes. Just my thoughts...

Regards, Alex

**Comment by salexgit** [comment]
Hi again

As a somewhat related comment, it might be also useful to implement same behaviour as in PGII when a deployment hexe "disappears" after a unit is deployed. I realized that this behaviour allows to balance scenarios so that a player has a natrual limitation on how many units can be deployed. In OpenPanzer, you can deploy as many units as you can, even within the same turn, and that is why quite many scenarios in the campaign mode become very unbalanced favouring the human player.

Of course, the concept of the supply hex should be also supported so that in some scenarios you still can deploy more units, if needed.

**Comment by nicupavel** [comment]
In 3.1.0 the supply hex was added and it's used as deployment. What I think PG2 had and we don't atm is that supply hex also included the 6 adjacent hexes. I need to confirm this first before implementing.
And indeed the game favors the human player by allowing more deployment hexes. Some scenarios are a real pain if we would limit the deploy hexes to just start. I get a lot of hate emails over the difficulty and truth be said the current campaigns were done for old players that had a lot of experience and were replaying scenarios 10 times to get it better (less common on new players). 
In contrast original PG2 campaigns were much easier, I'm trying to do a  a few easy mode campaigns for axis/allies for beginners with smaller battle fields.

**Comment by salexgit** [comment]
Hi

I had an impression that 6 hexes around the supply hex are used to define the area where a unit can be deployed if the supply hex is blocked. I could be wrong though...

Anyway, regardless of the fact whether it is just one supply hex or 6 hexes around it, it would nice to implement this concept. I played several campaigns and noticed that my army becomes so big by the middle of the campaign, that it is not interesting to play. 

So, there must be some bottleneck/limitation to prevent a player from deploying the whole army from one hex in one turn. And in some cases there should be no supply hexes at all so that you can deploy only N units.
