### ISSUE TITLE
Corrections for the German equipment file

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#200]
Hi all

Here are some suggestions/ideas on what can be improved in the German equipment file

7.5 leIG 18 cannon
---------------------
So, there is the 7.5 leIG18 light infantry cannon in the German equipment file, which is absolutely fine. However, exactly the same cannon appears on the list of anti-tank guns with a suprisingly high  performance. I was not able to find any historical records confirming that this gun was capable of the anti-tank role.
https://en.wikipedia.org/wiki/7.5_cm_leichtes_Infanteriegesch%C3%BCtz_18
Proposal: Deprecate/disable this cannon on the anti-tank gun list.

2.8 lePak41
------------
Somewhat referring back to the anti-tank gun topic, Germans have been using a light anti-tank gun in 1940-1945, which for some reason appears only in 1941 in the game.
https://en.wikipedia.org/wiki/2.8_cm_sPzB_41
Proposal: Correct the service year to 1940; make it weaker and cheaper

Panzer IIL "Luchs"
--------------------
I personally like a lot Pz IIxx series tanks for their high speed, so I was happy to see PzIIL tank to which I wanted to upgrade my older Pz IIxx models. However, Pz IIL is modelled as a "recon" unit, so there is no way to upgrade older Pz IIxx tanks to Pz IIL. It is true that PzIIL was mostly used for re-con purposes, but it was still a tank.  Furthermore, its spotting range is 2, so it is close to normal non-recon units, e.g. infantry.
https://en.wikipedia.org/wiki/Panzer_II
Proposal: Change the unit class to "tank"; change its starting service year to 1943 and end service year to 1944.

**Comment by nicupavel** [comment]
Great job investigating these. I agree with first 2 but not sure about Luchs, I was always going for this tank as recon. Don't think anyone will look for this on tank section since very few players actually look at units statistics and choose. But the year of service start is a good change but not sure about end year. End year is more like a unit becoming obsolete versus the production IMO.

**Comment by salexgit** [comment]
Hi Nicu

Thanks for your feedback.

I will make one more attempt to defend Pz IIL as a tank instead of recon unit type. Since OpenPanzer does not support upgrading units across different unit types, neither does it support disbanding units, you may get stuck with older Pz II models. At least that is what happended to me during several campaigns. Buying a new Pz IIL does not always look attractive, and upgrading older Pz II to e.g. Pz IV is not sometimes reasonable either because Pz IV is slower. By the way, I wonder why one would buy Pz IIL as a recon unit type with speed 6 and spotting range of 2, if you can buy cheaper Psw 234/1 with speed of 10 and spotting range of 3. 

---------------------------------------

As another issue, I recalled reporting some time ago an issue with StuIG 33B self-propelled artillery in #124. I checked the corresponding units one more time and found an interesting article on Wikipedia that gives a nice summary
https://en.wikipedia.org/wiki/SIG_33_Self-Propelled_Artillery

In short, there is a common 15cm infantry gun that was mounted on different platforms, such as Pz I, II and III; but the corresponding OpenPanzer units have a bit messy names and parameters. Here are the proposed changes:

- Introduce the same name pattern, e.g. 15 sIG Pz I/II/III
- sIG 33B Pz III speed is very small in OpenPanzer. We can increase speed by one step as originally reported by me in #124. So, sIG Pz I and Pz II speed will be 5, and sIG Pz III speed will be 4, which is in line with their technical descriptions.
- sIG Pz I attack strength is same as the corresponding infantry gun, which makes perfect sense. However, sIG Pz II and III have been also equipped with the machine gun. To account for it, we can increase the soft attack strength of sIG Pz II and III by one step. 
- I will spend more time on checking "Grille" and its parameters as it was effectively same 15cm infantry gun mounted on the Pz 38(t) chassis, which makes it faster than sIG Pz III. 

Regards, Alex

**Comment by widgetdog** [comment]
7.5leFK16nA Artillery
In game, the German artillery unit **7.5leFK16nA** only has the Opel Blitz truck and SdKfz 251/1 half-track. According to the Wikipedia article, "It was not modernized for motor towing and retained its original wooden spoked tires and two crew seats on the face of the gun shield."
https://en.wikipedia.org/wiki/7.5_cm_FK_16_nA
Additionally, the German Wikimedia page includes an image of an FK 16 nA being towed by horses:
![image](https://user-images.githubusercontent.com/49043163/55191418-54ebe700-515f-11e9-8e3b-9c1ceb972b05.png)
I am suggesting making a horse transport available for this unit as a replacement for or in addition to the currently available transports.

**Comment by salexgit** [comment]
Hi Widgetdog

Thanks a lot for spotting this problem. In fact, the same issue exists for a number of German artillery units, so I plan to update them as well. As an examle, 15 sIG 33 was also towed by horses or low speed vehicles as its suspension was not designed for high speeds.

**Comment by widgetdog** [comment]
SdKfz 250/1 Recon
The SdKfz 250/1 currently has the antenna assembly found on the 250/3 command variant.
https://en.wikipedia.org/wiki/Sd.Kfz._250
http://www.tanks-encyclopedia.com/ww2/nazi_germany/Sdkfz-250.php
![image](https://user-images.githubusercontent.com/49043163/55417925-774a7f80-5526-11e9-823f-329bcb607bff.png)
SdKfz 250/1
![image](https://user-images.githubusercontent.com/49043163/55418031-afea5900-5526-11e9-9cda-f65f40da4cd3.png)
SdKfz 250/3
![image](https://user-images.githubusercontent.com/49043163/55418144-e32ce800-5526-11e9-8c30-59c3403d96e9.png)

**Comment by salexgit** [comment]
Hi

Can you please make a summary of the proposed change? Do you suggest renaming the unit to "SdKfz 250/3" or changing the icon? Renaming the unit is of course much easier...

**Comment by widgetdog** [comment]
Either, though since it would require less work to change the name, I suppose that is what I am proposing.
