### ISSUE TITLE
Samsung Note 8 does not use the full screen

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#201]
Hi Nicu

I tried recently the OpenPanzer mobile app version on the Samsung Note 8 phone and have noticed that the game does not use the full screen. It is not a big issue, but it of course would be nice if the whole screen is utilized. 
In case if you need help with customizing the mobile version to Note 8, do please let me know. 

P.S.: While starting mobile app version, it still shows v2.9.8 on the main screen even though the Google Play Store shows v3.1.

**Comment by nicupavel** [comment]
Think I've seen this issues with some newer Huawei phones. The right part where their popup buttons are is not rendered, not sure how to fix this from Android, might be something new on Android 8+. As for the version I will need to double check.

**Comment by salexgit** [comment]
Hi Nicu

In fact both left and right parts are unused, not only the right part where the pop-up buttons are rendered. 

I will check tonight with Note 9 and will confirm whether it has the same issue.

Regards, Alex

**Comment by nicupavel** [comment]
Could you send a screenshot and tell me what Android OS version the phones use ?

**Comment by salexgit** [comment]
![Screenshot_20190311-163321_Open Panzer](https://user-images.githubusercontent.com/22852936/54107316-1d213780-441c-11e9-8cba-af14cc11c96b.jpg)

Here is the screenshot taken from my Note8. It seems that the game engine and/or running environment did not detect correctly the available screen size.
Android version is 8.0.0.

**Comment by salexgit** [comment]
Hi

I tested today with Samsung Note 9 - same issue. If I have a possibility to test with other latest Samsung mobile phones, I will let you know what the outcome is.

**Comment by nicupavel** [comment]
Thanks, I'll have to try in on simulator and see what I can do. In the mean time I googled and looks like samsumg has a full screen apps settings in Android Settings.

**Comment by salexgit** [comment]
Hi Nicu

I checked Android settings - indeed, there is an option to swtich applications into the full screen mode. I enabled it for OpenPanzer, and the game utilized the whole screen.

I assume that we can close this issue.

Regards, Alex
