### ISSUE TITLE
save/load doesnt work

### ISSUE THREAD

**Issue by glasszero** [nicupavel/openpanzer#205]
Hello, I am playing 3.2.1 version on Android phone. I save game from time to time, saves are available, or at least visible, but cannot be loaded, although it writes "game loaded". E.g. I make a wrong move and want to load older save, but after loading I still get the screen after my wrong move. This happens with saves to disk. Saves to cloud works without a problem, however, one wrong save could ruin whole campain, so I intend to use it only at beginning of a new map.
Any ideas how to get saving to disk working?

**Comment by salexgit** [comment]
Hi

It sounds a bit strange because I have been playing on a computer saving games locally. I never experienced such a problem. 
Can you please upload here "corrupted" saved game file?

Regards, Alex

**Comment by glasszero** [comment]
Hello, 
I am sorry, I searched my phone disk through, I looked into every folder, but couldnt find the game folder nor where saves are stored. Any suggestion? 
I will just amend my previous post: I am not having this issue in campain "Fall Weiss" and first map of "Das Reich". Other campains and starting with second map of "Das Reich" I cannot load saved game. I tested this on another phone and there was the same issue. I have got this issue already with previous version of the game. I tried also uninstall and install the game several times, but no help.

**Comment by salexgit** [comment]
Hi

I tried the Student scenario - I was able to save it but for some reason I was not able to load it. Well, the game says that it was loaded, but nothing happens after that. That is very strange.
I will check other scenarios and will confirm whether I have the same issue with them.

Regards, Alex

**Comment by glasszero** [comment]
Yes, this is exactly what I meant, some scenarios cannot be loaded, although it shows "game loaded". 

On the other hand "could save" works in every scenario which I have tried so far. Unfortunatelly, cloud has only one saving position. I dont intend to save game after every move but it is a bit dangerous to go for a long campain with just one position.

**Comment by salexgit** [comment]
Hi

I experimented a bit and I confirm that I experienced the same problem, at least with Android. Unlike your case, I was able to save all the games, but some of the failed to load. And I was not able to figure out what was the logic behind some scenarios failing to load. I will spend more time investigating it..

Regards, Alex

**Comment by glasszero** [comment]
Perhaps I explained it wrongly, I also could save all scenarios, but loading failed for many of them. I was also searching for some logic behind, e.g. long titles of saves, special characters in scenario names...but no success

**Comment by salexgit** [comment]
Hi

As I am a bit busy at the moment, can you try saved games, which failed to load in Android, to load on the desktop or online? If it works, it means that saved games are not corrupted and the issue is purely due to the Android environment and/or code that handles game loading.

**Comment by Philip799** [comment]
Will be good when do a profile. Im plaing on smartfon on web page and on Pc app. I must copy saves beetwen

**Comment by nicupavel** [comment]
I can't replicate but I only have android tablets atm. Can you tell me size differences between saves that work ok and those who don't ?

**Comment by salexgit** [comment]
Hi Nicu

I was able to replicate the problem at my Samsung Note 8 device. I should have saved games that were failing to load, so I can send them to you later today.

Regards, Alex

**Comment by salexgit** [comment]
Hi Nicu

Where does the application store saved files? I was not able to find them in a folder where I thought they should be.

**Comment by nicupavel** [comment]
Hi,
That would be great, but I'm not sure where they go. Many ask me the same question but it differs from phone to phone, os, manufacturer. On my tablet they were on the sdcard. What I can suggest is to get a file manager like ES File Explorer and search for *.json or (Campaign)*.json

**Comment by salexgit** [comment]
Hi

For some reason I was not able to find saved games even when I search for son files. Can you please let me know the full path to the saved games in your case? 

Regards, Alex

**Comment by barsoom1717** [comment]
Try ES File Manager and look in  "Downloads". 




Get Outlook for Android







On Tue, May 14, 2019 at 4:52 PM -0500, "salexgit" <notifications@github.com> wrote:












Hi


For some reason I was not able to find saved games even when I search for son files. Can you please let me know the full path to the saved games in your case?


Regards, Alex

**Comment by salexgit** [comment]
Hi Barsoom

So, are the saved games in the Downloads folder on your phone? I checked my Downloads folder, there are no json files there, at least in my case. Still cannot figure out where my phone hides them :)

**Comment by barsoom1717** [comment]
I too have had issues on my phone, but always figured the phone wasn't downloading the files.  However, on my Android tablet, I can always find the files in Downloads.
Stephen
    On Thursday, May 16, 2019, 6:22:04 PM CDT, salexgit <notifications@github.com> wrote:  
 
 
Hi Barsoom

So, are the saved games in the Downloads folder on your phone? I checked my Downloads folder, there are no json files there, at least in my case. Still cannot figure out where my phone hides them :)
