### ISSUE TITLE
Artilery range 

### ISSUE THREAD

**Issue by Philip799** [nicupavel/openpanzer#206]
In some of the russian Campaign scenario (orel, or krivoi) I have strange things with artilery range. All types of arty has very short range of fire. 
At the beginning, I think that is not a bug, and range of arty are caused by weather or the type of terrain, or some else. But this problem was in every conditions and only in russian scenario. Please explain.

**Comment by salexgit** [comment]
Hi

Can you please upload a saved game here indicating which unit(s), with exact coordinates, has the problem? 

Regards, Alex

**Comment by Philip799** [comment]
Link to save: http://tinyurl.com/y5srj4p5

Look at the arty units with long range of fire(5 hexes+). And i think that shorten range depends of positions, maybe terrain type.

By the way: Obstacles, like Mountain, city, or Forest will be a good idea when units direct fire at 2 hexes (AA, AT and tank units) 

Ps. Sry for my poor English, im from Poland.
