### ISSUE TITLE
Das Reich campaign issue/question

### ISSUE THREAD

**Issue by Krovar** [nicupavel/openpanzer#207]
I am trying to go thru the Das Reich campaign on historical difficulty and after completing the first 4 maps it takes me to the Kiev encirclement.  There are several maps skipped  I have tried now three different times and each time after getting a BV on River Schelde map, it skips the Maginot line map and as stated above goes straight to the Konotp (Kiev) encirclement map  Why is this happening?

**Comment by salexgit** [comment]
Hi Krovar

Oh, this is a bug, which was unintentionally introduced by us when we deprecated recently one of the scenarios from the DasReich campaign. Thanks a lot for spotting this - we will fix it asap!

Regards, Alex

**Comment by salexgit** [comment]
Hi Krovar

We fixed the issue with wrong scenario index values in the DasReich campaign, which should be available now in v3.2.2 beta, http://openpanzer.net/beta. Can you please check it? If you  upload here saved games, I can also double check that transitions work properly. 

Regards, Alex
