### ISSUE TITLE
why are the campaigns "Leibstandarte" and "Wacht Am Rhein" not available in Android

### ISSUE THREAD

**Issue by GavinLiam** [nicupavel/openpanzer#208]
I have a question about why the campaigns "Leibstandarte" and "Wacht Am Rhein" unavailable in my android Oppo A3S device but when i used it in the iPad and the computer the campaigns were there. Thanks.

**Comment by salexgit** [comment]
Hi

Good question indeed, I will check with the main developer why they were not included into Android.

**Comment by GavinLiam** [comment]
Thank you very much

**Comment by GavinLiam** [comment]
any updates

**Comment by salexgit** [comment]
Hi

I spoke to the main developer and here are some explanations: "This needs to use expansion files that will be downloaded after app install. I had the code written but when I got the time to release the SDK had some changes which required another debug/code session that I didn't have time.
Would be easier for me to just release separate apps."

So I assume that the next version of the mobile application will have those campaigns.

**Comment by GavinLiam** [comment]
thank you very much i appreciate it!

**Comment by Philip799** [comment]
I think, better play on webpage. There is updated ver.

**Comment by nicupavel** [comment]
They are now available as Panzer Marshal: Second Front / Turning Tides
