### ISSUE TITLE
Bzura pocket question

### ISSUE THREAD

**Issue by Krovar** [nicupavel/openpanzer#209]
I am playing the Bzura pocket scenario and so far 75% of the Polish units have leaders.  It seems that after they attack the white star in a green circle appears.  I understand making a scenario difficult but that high of a ratio of leaders is unheard of at least in my experience.  Playing on historical (naturally) but for once must admit that I will not be able to win this round due to everyone's defense value is either 4 or 6 points higher.  Is this a fluke, one off?  or has something changed? Thank you

**Comment by salexgit** [comment]
Hi

Every unit has a certain probability of getting a "leader", including AI controlled units, but this of course should not happen after every attack. Can you experiment a bit more? I have not noticed anything strange in the latest code, so maybe it was a weird co-incidence of facts.

Regards, Alex

**Comment by Krovar** [comment]
Thank you Alex, I did try go back and rerunning from an earlier save point and it did not happen again. I guess it was just one of those strange coincidences.  Thank you for checking

**Comment by salexgit** [comment]
Hi

Thanks a lot for checking. I will close the issue.
