### ISSUE TITLE
Animation and results

### ISSUE THREAD

**Issue by Philip799** [nicupavel/openpanzer#211]
Sry 4 my eng, im from Poland. 

Can you do a Little think, that results of combat will be shown after animation, not before?
Why fighters do a bigger damage (2-3) on soft targets, when they has only 1-2 attack on soft targets? This is diferent when units like arty, or others has a bigger attack points on soft targets and do a less damage?

I will be write more questions, beacouse pg2 is the game of my young times. 

Why panzer marshal from open panzer? :)

**Comment by salexgit** [comment]
Hi

With regards to the game name, maybe main developers can elaborate more on why the game was re-branded to Panzer Marshal :)

Concerning fighter versus artillery damage, each unit has separate defensive bonuses against the ranged attack and air attack, so maybe a particular unit was too vulnerable to the air attack. If you suspect that something is definitely wrong, then a saved game might also help.

I am not entirely sure I got your question on the "animation" and "result of combat". The "result of combat" shown before is just an approximation, while the actual outcome is influenced by other random factors.

**Comment by Philip799** [comment]
I,m sry, about question of fighter ground attack. My faul. I furgot about factor: air defense. But... 
What determines this factor, and long range defense factor,  etc, of all towed guns (all types: air def. AT, field guns, arty, maybe mortars too) I think its the same types of targets. The same way of construction dig in, etc.
This is a profile size? 

About "animation" and "result of combat", im not mean the The planned result of combat. 
I mean the think, about: showing final losses, and then playing animation. Dont u think that can be a deferent order? Firtsth Fight, then result? 

Sry 4 my eng, i know its horrible :)

**Comment by nicupavel** [comment]
The combat damage popups are done after animation but the unit strength is updated before, maybe I can improve this.
As for name change, search open panzer on google, there is another project using that name now and I was getting emails about rc models.
