### ISSUE TITLE
43 Combat Engineers?

### ISSUE THREAD

**Issue by ImperialCheese** [nicupavel/openpanzer#212]
Is there a reason why the US 43 Combat Engineers have 0 movement on foot? Is this intended or an oversight? It seems to me that giving them the same 2 movement as other engineers and pioneers would be more sensible.

**Comment by salexgit** [comment]
Hi

Good question, maybe this is just an oversight. I will check the equipment file. Sometimes those engineers unit have movement of 1, but 0 movement is strange indeed.

**Comment by Matimbo** [comment]
This is a problem but you can workaround for now by using 42 combat engineers.

**Comment by salexgit** [comment]
Hi

I checked the equipment file, I agree that "43 combat engineers" movement 0 is a bug. A similar unit "42 combat engineers" has movement 2.
I have several fixes in our pipeline for the German units, so I can consider making this fix as well.

Regards, Alex

**Comment by salexgit** [comment]
ImperialCheese 

It has been fixed in v3.2.2, beta for which is available online. We would be grateful if you double check it.

**Comment by Matimbo** [comment]
3.2.1 is still showing online and in the App Store.

**Comment by ImperialCheese** [comment]
The issue appears fixed in the 3.2.2 beta.

**Comment by salexgit** [comment]
Yes, online 3.2.2 beta has the fix which will be included into the official release.
