### ISSUE TITLE
Campaign ideas

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#213]
A question for the future, Is it possible to develop a nord African campaign? The struggle of the German-Italian army there is well documented, furthermore I’m pretty sure it would be simpler to make in contrast to some other campaigns... if it is possible it would be great to have an Italian campaign... sorry I’m Italian 😅

**Comment by salexgit** [comment]
Hi

Since we have limited resources, we do not usually develop new campaigns, but rather port/adopt existing ones developed for PGII and OpenGeneral. You might be interested in checking the following website, the campaign section: http://www.adlerkorps.com/.

If there is a particular campaign you are interested in, we can consider porting it. 

Regards, Alex

**Comment by salexgit** [comment]
Hi again

Referring to the link I posted earlier, there is one German North African campaign:
Libya, Africa, June 15, 1942.
11 Scenarios
Germany
Axis: Germany
Ah, Herr General, good to see you. I am sure you are eager to meet the men of your new command, the 21. Panzer Division of the Deutsche Afrika Korps. I'll take you to the men in a moment, but first we should take a look at these maps. Rommel want us to capture Tobruk to ensure it is not a thorn in our side when we advance into Egypt, like it was last year. 

There is also one Italian campaign, which looks like what you have been asking for:
Libya, Africa, June 11, 1940.
30 Scenarios
Axis: Italy
Allies: UK
Ah, General! Do you want some sparkling water? As you know, Il Duce has ordered us to advance from Cyrenaica into Egypt. Our forces in East Africa will strike north at the same time, allowing us to catch the British forces in a giant pinces. Your division will spearhead the advance and then fortity as we await reinforcements and the construction of a viable supply route.
Good luck, General! 

Regards, Alex

**Comment by campaignbuff** [comment]
Thanks for the clarification, I checked the link you provided under the historical campaign section http://www.adlerkorps.com/ and I found two noteworthy campaigns:
(For some reason I wasn’t able to save nor to copy the campaign’s data so I have to show you just the screenshots)
![6DA5E44C-D582-4CED-824D-1E8222F11696](https://user-images.githubusercontent.com/45533789/55741750-4db1bc80-5a2e-11e9-8207-1b4f5edf20c4.jpeg)
![B02BE7DD-236E-4B29-B32C-C18B931B03CC](https://user-images.githubusercontent.com/45533789/55741752-4e4a5300-5a2e-11e9-8aaf-8c5a588ca91a.jpeg)
In regard to the Afrika corps campaign I think that it should be absolutely included, even if , I admit, it’s quite difficult to tell, looking at the scenarios’ titles, if the campaign is effectively historical. Nonetheless I think it should be added as it would portray a totally different tactical situation and a totally new experience. After all the marshal hat in the logo of the game is the one Rommel had in that place and time.
The second campaign ,the Italian one, i admit its just a whim 😂 but if something could be made about it it would be great.
Thank you for the assistance

**Comment by campaignbuff** [comment]
Ahahaha you proceeded me, those were exactly the ones I looked at!

**Comment by salexgit** [comment]
Hi again

Do you have any preference? If we add campaigns into our pipeline, we should know which campaign to start with :)

**Comment by campaignbuff** [comment]
The Italian campaign would be great, but I it’s probably better to go first with the German African campaign as it is more relevant and having just 11 scenarios it’s probably quicker to implement.
Thanks for your time

**Comment by salexgit** [comment]
Hi

I will discuss it further with the main developer. We already have several German campaigns, so Italian campaign could be a better choice.
I will keep you updated.

Regards, Alex

**Comment by barsoom1717** [comment]
I would also enjoy the http://privat.bahnhof.se/wb103156/campaigns/germanworld.zip German World Campaign.
Stephen
    On Monday, April 8, 2019, 3:49:29 PM CDT, salexgit <notifications@github.com> wrote:  
 
 
Hi

I will discuss it further with the main developer. We already have several German campaigns, so Italian campaign could be a better choice.
I will keep you updated.

Regards, Alex

**Comment by campaignbuff** [comment]
Perfect alex, il’ll be looking foward to hear from you
Thanks again

**Comment by salexgit** [comment]
Hi

As a small status update, I ported the North Italian campaign to OpenPanzer. I will check with the main developers whether it will be possible to add this campaign to online beta for further campaign testing. 

Regards, Alex

**Comment by campaignbuff** [comment]
I’ll wait happily and patiently
Thanks again for your time and assistance

**Comment by nicupavel** [comment]
German World Campaign coming up soon.

**Comment by barsoom1717** [comment]
Awesome!
Stephen
    On Monday, May 13, 2019, 4:56:11 AM CDT, Nicu Pavel <notifications@github.com> wrote:  
 
 
German World Campaign coming up soon.
