### ISSUE TITLE
M15 AA truck

### ISSUE THREAD

**Issue by Themaginotlineww2** [nicupavel/openpanzer#214]
A problem I have encountered Is that the M15 AA truck very frequently does little to no damage. This wouldn't have been a problem but since the enemy seems to have numerous planes per mission( that statement was only barely a exaggeration) this has become a very large problem. Also, my opinion is that the german campaigns could use more starting prestige.

**Comment by Philip799** [comment]
Historically in my opinion
1. Allies units has a very weak training at beginning on West front. 
 
2. M15 its a halftrack/transporter for infantry. When added some diferent weapons has only 12mm twin machine guns on not stabilised lawete, or one 37mm gun. That was not specially acurate AA weapon, that was little or minor chance to hit low Flying fighters.
