### ISSUE TITLE
Kiev encirclement and Das Riech Campaign order VS scenario order

### ISSUE THREAD

**Issue by Themaginotlineww2** [nicupavel/openpanzer#217]
I have been having a problem with the das riech campaign that started with Kiev encirclement, it might be a bug but there is no evidence supporting that as it as never happened to me before. In that mission I was underequipt with troops due to there being only 2 missions before so I had too few troops and they had little experience. This was a problem on this mission due to the russians having a absurd amount of artillery, infantry and tanks( 67 infantry units in total, 19 mortars,10+ larger artillery pieces, 14 anti-tank pieces, only 4 planes) and nearly a fifth of them started as veterans. Not only that but when I finally turned the battle in my favor, pushing the frontlines forward, The enemies spawned behind my troops and hit the few artillery pieces I had left. The combonation of this ended with a early defeat for me. This could easily be fixed if the order of the campaign  was in the order shown in the scenario list. Instead it was a massacre with no way to win, since I could barely buy one tank per turn, which didn't do anything to change it in the long run as the AT guns murdered them as soon as they got to the scene( and sometimes before that).

**Comment by salexgit** [comment]
Hi

Maybe you are referring to the same issue as #207. 
The main developer told me that the fix is already available for the online beta, so you can consider trying online beta for the correct order of scenarios.

Regards, Alex

**Comment by Themaginotlineww2** [comment]
Thank you.
