### ISSUE TITLE
Operation Marita

### ISSUE THREAD

**Issue by GavinLiam** [nicupavel/openpanzer#219]
why are all the units in operation marita turned into flak?is there any way fo fix this? thanks

**Comment by salexgit** [comment]
Hi

It seems that you have same issue as the one reported in #199. Can you please tell us:
- whether you play the online game or locally?
- if you play it locally, then is it Android or IOS?
- can you reproduce the problem every time you start the Operation Marita scenario?

Regards, Alex

**Comment by salexgit** [comment]
Closed because the same issue is reported in #199.
