### ISSUE TITLE
Russian Campaign issues

### ISSUE THREAD

**Issue by MansteinlovesGuns** [nicupavel/openpanzer#221]
I just played through the Russian campaign and noticed some issues that has made the last level of taking Berlin quite a challenge.

On a few maps there are artillery units and anti tank units you destroy and then the reappear each enemy turn. I had my artillery units completely wiped out twice because of this which wasnt too large of a fact9r until Berlin where it happens again these units appear each turn and it slowly wears you down

**Comment by kommandoren** [comment]
Russian engineers, bridge, paratroopers issue.
