### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#222]
So I've just started playing again I'm on the 4 battle of kharkov

I've seen a weird bug where many of my units which have 2000+ experience attack a unit or are attacked and suddenly the experience drops to 1000 even if they take zero damage. 

Other issues are:
The app will not load saves from disk, instead if you load from disk it just stays exactly where you are. 
Cloud works but that's limited and also means you have to have the Internet 
The app is also unstable, crashing multiple times per hour

The browser version is far worse and crashes within minutes of launch. 

Additionally the browser version never remembers the cloud code which takes a while to type in.

**Comment by RymarPM** [comment]
On the iOS version i never had any load save issues

( except saves are all jumbled up and not in date or alphabet order)

In relation to experience, again on the IOS version, non on my units ever increased passed 1,000 exp

**Comment by ImperialCheese** [comment]
As of the 3.2.0 release, maximum experience for units has been capped to 1000, so that may be the reason why your units are losing experience.

**Comment by LaughtersGrave** [comment]
So all of my units are going to become worse?

How come experience is capped? Surely it would be better to just cap over strength at 18 or 16?
