### ISSUE TITLE
Reinforcement “mafia”

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#228]

**Comment by campaignbuff** [comment]
This problem has always been an annoyance tipical of single scenarios, but with the recent beta it has turned into a real problem...
The reinforcement feature is being overused by the computer, with continued reinforcement following one after the other.
This is becoming really frustrating as it takes 3 times as much time and resources to kill a single unit.
This is especially problematic in the Italian campaign as the troops are inferior in stats and the continue spam of reinforcement makes the gameplay dreadful...
I don’t really need to underline this, but the feature (and the spam of it) is obviously not realistic nor historical.
The feature could be limited or straight up denied (to the computer) as it is in the app version.
Thanks in advance

**Comment by salexgit** [comment]
Hi

This is not a feature of the game but rather a particular design of a particular scenario. In other words, game engine will not instantiate "reinforcement" units unless the scenario tells to do so.
Can you please indicate the most frustrating cases?

As a side comment, "reinforcements" can be viewed as a general mechanism to prevent you from having a large army straight in the beginning of the scenario and/or to help AI (which is not as smart as you are). However, I also agree that some scenarios become somewhat unrealistic.

**Comment by campaignbuff** [comment]
Hi Alex,
I was delighted that my request and the one of many others of adding an Italian campaign was implemented, so the immediate course of action was to immediately play it.
I made it as far as the 3rd scenario trying to be as historically realistic as possible but I was prevented by fore mentioned feature, which added strength to every unit...
So I skipped forward playing single scenarios and this is present in everyone of them but at least is more manageable.
Then to finally answer your question I would say the first 4-5 Italian scenarios 
As a bonus in the 3rd scenario there is a British cruiser stranded in the middle of the  desert 😂
Thanks again

**Comment by salexgit** [comment]
Hi

As for the British cruiser in the middle of the desert, that has been already fixed :)
If we have time, we will take a look at other scenarios, however we would not promise any big changes in the near future. Some campaigns are just designed (not by us) to be more challenging.

Regards, Alex
