### ISSUE TITLE
AI spamming cheap unit in Campaign Mode

### ISSUE THREAD

**Issue by Flo1221** [nicupavel/openpanzer#232]
I don't know if it is already fixed internally, but in some Campaign missions the AI spams cheap units (not as scripted reinforcements, but through buying them) - i think it is this feature:

"AI: Now AI will buy and deploy  units if it has enough prestige after resupply/reinforce."

For example in the US Big red one campaign in the "El Guettar" Scenario i ended up with 30+ cheap italian units, all clustered up near the italian deployment hexes - i noticed this behavior in other missions as well. I played on Android with operational difficulty, version 3.2.1 according to the main menu.

**Comment by salexgit** [comment]
Hi

Thanks for reporting these observations. 
I assume that buying 30+ cheap units is not wrong, even though you might argue that AI should have bought 5 expensive and powerful units instead. So, if I got your point right, the concern is that AI does not behave in the most optimal way, right?

Regards, Alex

**Comment by Flo1221** [comment]
Hi,

right - also those were kind of "ahistorical units" additionally as they were all clustered up around the last victory hex, it was pretty difficult to reach it (it was like 4-5 hexes of units in each direction). Way more than in any other scenario of the american campaign so far - although because of the prestige boost of the operational difficulty i could counter-spam with stronger units, but it somehow felt not right playing that way. But as i am not a very good player, thats probably not such a big point.

Flo

**Comment by PanzerWolf** [comment]
This happens still in the Russian World Campaign (Great Patriotic War).
