### ISSUE TITLE
Operation Brevity Italian campaign

### ISSUE THREAD

**Issue by bvdpbvdp** [nicupavel/openpanzer#235]
Hi,
playing via panzermarshal.com/beta 
version 3.2.3
Win hex is hidden or am I just blind?

**Comment by salexgit** [comment]
Hi

Can you please check the discussion thread #225? If there is no answer on that thread, let me know.

**Comment by bvdpbvdp** [comment]
Hi again,
no,I could not find it there.

**Comment by campaignbuff** [comment]
I also came across this problem, another case of this happening is in the bardia scenario... I was able to pass to the next only by letting the brits win.
The concerning fact is that there is virtually no turn limit, consequently I’m stuck in brevity searching for an hidden hex that probably doesn’t even exist.
I can’t understand why this is the case, as in “a dance with the queen” scenario there is an inaccessible escarpment with a victory hex that can be conquered by reinforcements at a certain stage...
This is very annoying indeed

**Comment by nicupavel** [comment]
There are several scenarios with hidden hexes. The Italian campaign makes heavy uses of hidden hexes but I'm not sure how the author actually intended these to work.
For next version I'm implementing 2 things:
1. Option to show this hidden hexes (although it can make gameplay a joke on certain campaigns)
2. Option to win by destroying all enemy units without requiring to capture objectives.

Attached the log from conversion tool for all campaigns with Hidden Victory warnings.

[log.txt](https://github.com/nicupavel/openpanzer/files/3573572/log.txt)

**Comment by nicupavel** [comment]
Fixed in 3.2.5 either win by destroying all enemy units or turn on "view hidden hexes" from settings to see the hidden hexes.

**Comment by bvdpbvdp** [comment]
thank you!
