### ISSUE TITLE
Das Reich campaign issue - 4th Karkov

### ISSUE THREAD

**Issue by Fahnjim** [nicupavel/openpanzer#236]
Hi, 

I am stuck on 4th Karkov.
There are two objectives and the island in the bottom right corner cannot be taken. 

For some reason my units cannot enter the hexes around this objective. They can reach the island, as you can see from the screenshot. My planes can enter the hex over the objective, but my units cannot enter. This prevents me from moving on with the campaign. 

A fix would be awesome.
  
See screen shot 
<img width="473" alt="Panzer 4th Karkov - fahnjim" src="https://user-images.githubusercontent.com/54872403/64217922-b8debc80-cf02-11e9-8471-f0c1cfa23d82.png">

Cloud save ID
58564392c1b0e1e2391e753af739db19
<img width="728" alt="Panzer 4th Karkov - fahnjim cloud save" src="https://user-images.githubusercontent.com/54872403/64217964-f5aab380-cf02-11e9-8f7b-794de0674d97.png">

best
James

**Comment by nicupavel** [comment]
In current beta should be fine (panzermarshal.com/beta/)
![4thkharkov](https://user-images.githubusercontent.com/1650801/64240093-06125c80-cf0a-11e9-87b3-7479fde22e8a.png)

**Comment by Fahnjim** [comment]
Thanks Nicu
I downloaded the OSX version last week, so I think this is the lastest version. Perhaps this is an issue with the OSX version??
The game is awesome, thank you. I can't stop playing :]
best 
James

**Comment by Fahnjim** [comment]
Thanks Nicu, it worked on android.
