### ISSUE TITLE
gibraltar scenario stuck in 'computer turn' on web, mac, and linux

### ISSUE THREAD

**Issue by cmayer68** [nicupavel/openpanzer#237]
cloud save: a27dd2e7babf556322cbd984c431d603

**Comment by nicupavel** [comment]
Managed to finish it just fine: bfb04a3d68f9376895bd0e5fc75271f2 but I also found the situation that you report by just not moving anything on left side of map (where the British carrier/planes are). Going to debug further, thanks for letting me know.

**Comment by nicupavel** [comment]
Good news I was able to constantly replicate this issue thanks to your save ! There was a race condition which I fixed. I will have to release 3.2.6.

**Comment by cmayer68** [comment]
i also got this to complete by editing the save file and changing the
carrier to a destroyer (!)
cheers and thanks.

--curt

On Sat, Sep 21, 2019 at 11:44 PM Nicu Pavel <notifications@github.com>
wrote:

> Closed #237
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nicupavel_openpanzer_issues_237&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=4kkoCdrqAWiTSrKpqwsyp70eTl7DXWZSslHydnvvGAw&s=sL1eNnJDM9JY0iCTBf-xfTkxsHJId6-97c_wINZxxS0&e=>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nicupavel_openpanzer_issues_237-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADZV4TFG2TCDZNM2ATFTPXDQK4H3ZA5CNFSM4IYPGOJ2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOTYM4UKY-23event-2D2652490283&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=4kkoCdrqAWiTSrKpqwsyp70eTl7DXWZSslHydnvvGAw&s=SeagoCNcREKFetqIIzZ3eY74omNsBa8tN0BQWWj2hGg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADZV4TAULZHYPUT5RU6F453QK4H3ZANCNFSM4IYPGOJQ&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=4kkoCdrqAWiTSrKpqwsyp70eTl7DXWZSslHydnvvGAw&s=vBkDKsD7hq1ZUumW3Pbcf8AJGB0e0nephEm1aTItYgc&e=>
> .
>


-- 
*Curt Mayer* | Senior Architect, Customer Success
Office 707.540.3441 | Mobile 707.540.3441
<http://appdynamics.com/>
Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>
