### ISSUE TITLE
Carrier units crashing the game

### ISSUE THREAD

**Issue by jackomago61** [nicupavel/openpanzer#239]
So. This is a issue that i stumbled upon several times. If a friendly carrier gets destroyed by the enemy the AI will refuse to continue it's turn, Making me unable to keep playing. I haven't tested that on 3.2.6 but i think it's worth mentioning

**Comment by nicupavel** [comment]
Please test on 3.2.6 this has been theoretically fixed.

**Comment by Newcastle2** [comment]
Was an issue for me but not on 3.2.6; all ok
