### ISSUE TITLE
Air Defense Hard/Soft attack values  --Question

### ISSUE THREAD

**Issue by robwebbjr** [nicupavel/openpanzer#241]
Why do all Air Defense units show attack values for both hard and soft targets when it seems that some AD units are only able to engage air targets (and not ground targets)?
Is there a trick to using AD units against ground targets?
Thanks.

**Comment by nicupavel** [comment]
They can't initiate attack but they can strike back.
The combat happens like this (simplified to maximum):
Attacker attack value vs Defender defense value -> Defender loses
Defender attack value vs Attacker defense value -> Attacker loses

**Comment by robwebbjr** [comment]
Hey, thanks a lot for the answer.
And thank you for making an awesome game; it is by far my favorite game!
