### ISSUE TITLE
No core army

### ISSUE THREAD

**Issue by hottassmess** [nicupavel/openpanzer#242]
I'm doing operational mode campaign and I get to the Normandy hedge rows it won't load my core army.were they should be is nothing there the box below were you buy units is but above just empty space

**Comment by SovietArmyakaRedArmy** [comment]
it a bug and it can fix by reload you game ( if you play beta ) or exit you game and re enters it

**Comment by hottassmess** [comment]
Tried that it's on Android that I play on
