### ISSUE TITLE
desktop version on windows 10

### ISSUE THREAD

**Issue by Andyc43** [nicupavel/openpanzer#244]
game sticking at crossing the dnepr, have only recently purchased desktop version so first time have done campaign this far. once have taken last objective game wont go to next level, if i leave game and go back it opens in spainish tuition.  i openened saved file with webversion and it went to next scenario ok after taking objective

**Comment by Andyc43** [comment]
i have been doing bit off investigation, have tried check as many files as possible and they seem to be there, however have found you cannot run the drive to yelna as a stand alone scenario either it opens the spain tutorial, i have changed the campaign json so that a brilliant win takes you to kiev encirclement and then game continues at end of dnepr scenario. obviously there is some flaw in the dryeln09.xml file, if have time will try go through it line by line and see where problem lies, if can fix will be happy post for others

**Comment by Andyc43** [comment]
hi have found error, it is in dryeln09.xml which is in Panzer Marshall directory (user/appdata/local - you will have set broswer to show hidden files) in resources/scenarios/data
edit the xml file and change the support to "0, 0, 0, 0" in file it is set to "255, 255, 255, 255" for both players. scenario will then play as stand alone and also after brilliant victory on Smolensk - Dnepr crossing.

**Comment by nicupavel** [comment]
Thank you for looking and finding a fix for this issue. I'll integrate the fix in the next version.

**Comment by Andyc43** [comment]
hi pavel many thanks, if you have anything that needs testing or think is an issue i could look at let me know, my background is software although then moved into hw and sw support, am not working so much now as slowing down towards retiring so have some spare time on my hands and play your game a lot

**Comment by jonh64** [comment]
Game sticking for me now at same point on Das Reich campaign. Can’t seem to achieve brilliant victory in this scenario. ‘Continue game’ takes me to Spain too. I’m on latest IPad.

**Comment by Andyc43** [comment]
hi you need find the dryelno9 file and  edit it as my comment above 4 above, this will then fix, however i have no idea where on ipad this file maybe, location on a pc is also 4 comments above
