### ISSUE TITLE
Aircraft ranged attack?

### ISSUE THREAD

**Issue by jonh64** [nicupavel/openpanzer#245]
I've noticed on a couple of scenarios that sometimes when i protect my high strength artillery with decent fighter aircraft, enemy bombers still cause damage on my precious guns from an adjacent hex.  Anyone else encountered this issue pls?

**Comment by nicupavel** [comment]
Looking at the game rules implementation looks like this is possible, must check if original game rules allowed this or not. As far as I remember this is not correct.
