### ISSUE TITLE
German Barbarossa campaign: Brest Litovsk (scenario error?) 

### ISSUE THREAD

**Issue by RymarPM** [nicupavel/openpanzer#248]
Is there an issue with this scenario when played on German side ?

When I try to play as either part of campaign it won’t let me attack with my core units.

As a single scenario only has the supporting 5/6 German units and not the main (core) army

(Playing on iPad 2018)

**Comment by salexgit** [comment]
Hi RymarPM

Can you please upload here a saved game with the problem you described? If you cannot upload the saved game, then you can post the ID of the cloud save.

Regards, Alex

**Comment by RymarPM** [comment]
Her is the code for (one of) the games that is stuck.  All units are deployed but I can’t attack

Code - e092f36538997b52c075215f4f847e54

**Comment by RymarPM** [comment]
And here is the code for a brand new single scenario.   When played from the German side you only get the basic starting 5-6 units

Code.    e092f36538997b52c075215f4f847e54


(Issue on 2018 iPad)

**Comment by salexgit** [comment]
Hi RymarPM 

It seems that you posted same saved game ID for both cases, which points to a brand new scenario. 
Nevertheless, I can answer at least the question concerning the brand new scenario and why there is no "core army". When a scenario designer makes a new scenario, there are basically two options: a) pre-allocate units for the core army catering e.g. for historical accuracy; or b) do not pre-allocate any core army units (whereupon the game will allocate higher prestige to buy more units). There is no strict rule which option should be followed - it is up to the scenario and campaign designer. In this particular case, the campaign/scenario has no core army, but instead you have 24,000 prestige to buy units you want.

Regards, Alex

**Comment by RymarPM** [comment]
Here is the correct, non working campaign scenario

e092f36538997b52c075215f4f847e54


I’ve (badly) deployed all my units but then can’t attack.

It’s like the 1st turn has not really started as if I had not deployed all my units.

I can’t attack
The highlighted ‘move’ hexes don’t appear

I tried re finishing the previous scenario (Windsor BV) a few times just incase it was a 1 off bug but each time this senario flaw crops up.

In the end, I went back to a previous senario (Dunkirk) and only took a Victory and the following senario were fine.

**Comment by salexgit** [comment]
Hi

I loaded the saved game on a desktop computer - it works fine at least there. I can try to load the same game on a mobile device to see whether the issue emerges on a mobile platform.

**Comment by liuyomi** [comment]
Hello, I'm facing the same problem of RymarPM.
I played German World Campaign on Mac (download, not on browser),
cloud save code: 383f9cf7bf1772f01eab1c81489045ce

in Windsor Turn 8, when I occupied the final helix, the campaign go to Brest-Litovsk,
I can deploy my unit but can't attack any enemy.
The highlighted ‘move’ hexes don’t appear.

**Comment by nicupavel** [comment]
I loaded the game on the browser version and it works ok. Does this happen even if you save and reload after deployment ?

**Comment by liuyomi** [comment]
Hi, Nicu, thanks for reply. I tried in Mac download version, iOS app, and Browser version in Safari and Chrome, and even borrowed another Mac from my friend, S/L several times, but the situation was the same.
I even re-played Windsor Scenario from the beginning (round 1, because I don't have earlier save file in Dunkirk scenario). And in the final turn, occupied final hex, then in Brest-Litovsk scenario I just can't attack enemy, airplanes also can't fly on ground enemy's hex.
Maybe it only happened in Mac OS / iOS ?
