### ISSUE TITLE
Save to Cloud games time out or disappear

### ISSUE THREAD

**Issue by Matimbo** [nicupavel/openpanzer#251]
Awesome game, great campaigns and play.  One major issue.  I play on an iPad and save my campaigns to the cloud.  I carefully hit save, look to confirm that the game is saved at the new point in the scenario, and leave the app open and move on to the next one.  If I play regularly, every day or so, the saved game is almost always there to resume.  However, if I wait four or five days, which happens with work or weekends, the saved game will disappear and there is nothing to load or continue.  This is very frustrating as I'm at Kursk for Das Reich or Sedan44 for the Americans and after investing hours and hours with ten or more previous campaigns and building up a powerful force it suddenly vanishes.  
Is there a feature that causes campaigns to time out after a designated time interval when saved to the cloud?  For devices for which you cannot save to a drive, like a phone or tablet, this is an issue.  I'm not sure if other users experience this, but it has happened a half dozen times to me.

**Comment by salexgit** [comment]
Hi

Thanks a lot for your feedback. At least on Android there is a way to save a game "locally" on a phone, but I have no clue whether it works in the same for iOS. If I have time I can check iOS devices.

@nicupavel: Can you comment on purging saved games from the cloud?

**Comment by nicupavel** [comment]
Local save is available on iOS too. On cloud only the save games that are older than 6 months are purged.

**Comment by salexgit** [comment]
I guess we can close the issue.
