### ISSUE TITLE
Unit deployment

### ISSUE THREAD

**Issue by geomanv** [nicupavel/openpanzer#253]
Quite possible that I am doing something wrong but in all three platforms I have tried (iPad, Win 10 downloaded, Chrome - running in the browser) I get to a point where the units in my core set are more than the available deployment hexes and I am basically stuck; i did save a case scenario in the cloud

0f928354d7d14184cfc3810839ce82ce

Thanks for the help

**Comment by nicupavel** [comment]
Yes this is intended. The original game was using a limited number deployment hexes to increase difficulty and it was only possible to deploy at the start of the game or after conquering a supply hex. In Panzer Marshal you could deploy all units by deploying in the hex, closing the deploy window, moving unit from that hex and deploying again.
