### ISSUE TITLE
Pacific Campaign Minor Comments

### ISSUE THREAD

**Issue by PanzerWolf** [nicupavel/openpanzer#254]
Hi,

First off, great job on the Pacific Campaigns they're great! You really get the feeling of slashing your way through the jungle at times. Also good to remember the army, it wasn't always marines in the Pacific. 

Some issues:

- wherever the scenario speaks of a Port you can use to embark your units, it doesn't work (or I can't find the right button).
- Also whenever a DUKW is present in any scenario (as a support unit) it is always labeled with "No Fuel" and is practically useless.
- I noticed in playing through the Marines campaign that there are (sometimes large) concentrations of enemy units that do nothing. I can't remember which scenario it was, but I discovered a group of enemy battalions lurking in my flank and honestly I thought I was about to lose, but they didn't move a muscle. This seems odd. Also the "Bloody Ridge" scenario, didn't really feel as Bloody Ridge. After skipping turn after turn I decided to go scouting and discovered a large enemy force in the South, doing nothing. I suppose they were normally used to attack, but it didn't happen.
- Very Important in the Army Campaign: It suddenly stops in 1944 and then restarts in 1942 in the Philippines. Which is fine for me, but the only problem is that I still have my 1944 units, plus several prototypes... which makes the rest of the campaign a walk in the (jungle) park. I suggest splitting them op and using them as two separate mini-campaigns. 

Some suggestions:
- I think it would be cool if UDT units could sweep mines (they did sometimes)
- Maybe Raiders could have a bonus when attacking directly after disembarking (to reflect their specialty)
- I missed Tarawa and Midway somewhat as scenarios. :)

That's it!
Great work!

Grtz,

Rolf

**Comment by nicupavel** [comment]
Thanks for the feedback, I'll take a look, probably I messed up the scenarios order in campaign.
