### ISSUE TITLE
Capturing the objectives

### ISSUE THREAD

**Issue by peterlevine23** [nicupavel/openpanzer#255]
I am a new player.  I just played “Oran” and “D-Day” several times until I had captured Oran itself and all the objectives for D-Day, meaning that I had occupied the named hexes and the flags had turned to my country’s.  Yet the computer tells me I lost because I failed to capture the targets.  I assume I am doing something wrong—but what is it?

(I’d like to figure this out because this is my favorite WWII wargame, otherwise. I like the interface, look, and scale.)

**Comment by nicupavel** [comment]
Could you give us a cloud save game id with all objectives captured ?
For example in Oran there are 6 objectives to capture when you start. Make sure you get all those 6 and AI doesn't capture one of yours. If you click on top bar it would tell you how many objectives are left to conquer.

**Comment by peterlevine23** [comment]
Thanks very much for replying. I think I just misunderstood which were objectives. I believe it’s working fine—and is a very good game.

Peter
