### ISSUE TITLE
New 3.2.7 problems 

### ISSUE THREAD

**Issue by Feldmarshalruge** [nicupavel/openpanzer#258]
Hi guys over weekend my apple 11 received the new 3.2.7 and has completely screwed my campaign I was playing and will not let me restart any games.  The campaign scenario pop ups don’t work.  Need help!

**Comment by LudiCane** [comment]
Litteraly it is impossible to play. Whenever i save the game, playing is over. When i load saved game, i find myself in the beggining of tuttorial campagin

**Comment by salexgit** [comment]
Hi

I saw a similar issue in the past when new campaigns were added. The problem is that campaigns are just referenced by an index value, not by a unique ID. So if you have a saved game from 3.2.6, you might unfortunately experience the same problem if you open/load the saved game in a newer version that have more campaigns. 
Maybe the main developer can comment more...

Regards, Alex

**Comment by LudiCane** [comment]
I loaded some of the old (3.2.6) saved games. Most of them do not work properly, some of them does. When it does not work, this is the issue:
- map is loaded, bu ther is no units
- everything is here (maps, units, objectives) but it's not possible to move units.
- there is a missing icons of some units, on rooster, and on the map also.

I hope that you will resolve these problems as soon as possible. 

thanks in advance.

**Comment by nicupavel** [comment]
I had to optimize game save data. It should work with saves from older version, but I can see there are issues. Best advice would be to attach here a save that doesn't load and until I fix it play the previous version until you finish the campaign (http://panzermarshal.com/prev/ or 3.2.6 offline version download)

**Comment by LudiCane** [comment]
[Archive.zip](https://github.com/nicupavel/openpanzer/files/4388180/Archive.zip)
Hi @nicupavel,
here you can find attached 3 saved games from both USA Pacific campaign that doesn't load.

Regards, Igor

**Comment by salexgit** [comment]
Hi Nicu

@nicupavel: The link you posted earlier, http://panzermarshal.com/prev/,  does not work. It seems you have to enable permissions to get an access to it.

**Comment by nicupavel** [comment]
I fixed the /prev/ version on web. I'm looking into save game. Thanks @LudiCane, @salexgit

**Comment by Feldmarshalruge** [comment]
Tried again and tutorial scenario keeps replacing my campaign turn.
