### ISSUE TITLE
Game sadness

### ISSUE THREAD

**Issue by Feldmarshalruge** [nicupavel/openpanzer#260]
Guys I still can not play.  It seems as the game saves everything then freezes when I return.  The game throws me back at times to the tutorial.  3.2.6 was smooth 7 is rough.  Can’t save more than one campaign too.  Please advise. You said enable permission but my phone is set to accept all?

**Comment by nicupavel** [comment]
The size reduction changes for the save game now takes a while to complete. Are you playing on a phone with Android ? Did you try the desktop versions on https://openpanzer.itch.io/panzermarshal/ ?

**Comment by SherDG** [comment]
Hi. I have the same problem (desktop(3.2.7 version), browser(Firefox,Chrome)) for cloud and JSON saved game - http://i.imgur.com/4DDWJoZ.png
Every time game returns me to the tutorial.
What else can I try to do to fix this problem?
Where can I download previous game versions and would they compatible with saved game from 3.2.7?

**Comment by SherDG** [comment]
Today I tried http://panzermarshal.com/prev/ for my saved games and it also doesn't work for cloud and JSON - http://i.imgur.com/Tj27EMo.png

**Comment by nicupavel** [comment]
Should be fixed in 3.2.8

**Comment by Philip799** [comment]
better browser for PM is opera in full screen mode.
