### ISSUE TITLE
Loading issue from cloud

### ISSUE THREAD

**Issue by Mishca1** [nicupavel/openpanzer#264]
Hello.
When I try to load from cloud, the drive to Smolensk mission, I get to th Tutorial. Is there something to do with this?
Cloud save number is : 3949472cd9196c646af7b2c0b25d905f

**Comment by nicupavel** [comment]
Should be fixed in 3.2.8

**Comment by Mishca1** [comment]
Thank you. 
And thanks for a super game.

**Comment by layssi** [comment]
This fix is not working on android
