### ISSUE TITLE
No Tank attack sounds on iOS

### ISSUE THREAD

**Issue by uncleJBJ** [nicupavel/openpanzer#266]
Just started playing the new German world map campaign. I noticed the Tanks don’t make a sound when attacking.

**Comment by salexgit** [comment]
Hi

Can you please let us know where you play the game, e.g. desktop, Web, Android, iOS? I played recently several scenarios and I clearly heard tank attack sound.

**Comment by uncleJBJ** [comment]
The IOS app on my IPhone 7. I have to exit the app and then Reopen it and
it works again

**Comment by uncleJBJ** [comment]
Also, I’m noticing it a lot when I’m playing the new Italian Campaign

**Comment by salexgit** [comment]
Hi

Does it happen on iOS app for iPhone? I am trying to narrow down the scope of the issue.

**Comment by uncleJBJ** [comment]
That’s the one.  I have a iPhone 7.
