### ISSUE TITLE
Embarking at port

### ISSUE THREAD

**Issue by vbaronpg** [nicupavel/openpanzer#269]
Hi:

I'm playing the Marine Corps campaign and I cannot embark units at the port in the Linga Linga hex in the Talasea scenario.  I have tried it with Safari on an IPAD and Firefox on a PC laptop.  Pressing "E"  does not do anything.  I get no response of any kind when I press any key.  Am I missing something?

Thanks,
Vin

**Comment by vbaronpg** [comment]
I tried the scenario by itself and get the same result for embarking, but the keyboard responds to other key presses (H, O, Z, etc).  Here's the Cloud save of the campaign  
da79ee24a5f55574894fe158d4f1eb2b

**Comment by salexgit** [comment]
Hi all

If I got the question right, embarking i.e. loading a unit on the sea transport, requires presence of the sea transport units, which is the scenario design parameter. If there are no transports, you cannot embark; and you cannot buy transports either.

Regards, Alex

**Comment by salexgit** [comment]
Hi again

I checked one scenario which has sea transports, but I cannot embark units either. This is really strange. I will check it with the main developer.

**Comment by vbaronpg** [comment]
In this particular scenario, the only way to get to the objectives is to embark.  The Port hex (marked with the anchor?) should allow you to do that, but that's what I am having difficulty doing.

**Comment by salexgit** [comment]
Hi

The issue is much more fundamental - it is not possible to embark at all, in any scenario. It seems that this functionality was broken in some version because you still can embark in 3.1.x releases.
I contacted the main developer so we will try to fix it asap.

Regards, Alex

**Comment by nicupavel** [comment]
Fixed this internally and will deploy next week for beta.

**Comment by vbaronpg** [comment]
Thanks!

**Comment by salexgit** [comment]
Hi

@nicupavel Thanks for your efforts. Let me know that the fix is in the online beta, and I will do additional testing to ensure that it works properly.
