### ISSUE TITLE
Loading Big Red One 

### ISSUE THREAD

**Issue by jdduff99** [nicupavel/openpanzer#275]
I have started the Big Red One campaign twice and had to abandon it. I can play for while like a few days but something happens to the saved files (locally). If I click "Continue" when I start the game, I can play the next turn but if I try to load a previously saved campaign file (json file), it throws me into the tutorial scenario. Once that happens, I can never get back to any of the saved files of the campaign, no matter what file I try to load it only will load the tutorial. Help, what am I doing wrong?

I run the installed game under Windows 10.

**Comment by salexgit** [comment]
Hi

Which version do you play? If I recall right, several players complained about the same or similar problem, but I thought that it was fixed in the latest release. 
Do you have a saved game, opening which always causes this problem? If so, can you please send it to us and we will take a look.

Regards, Alex

**Comment by jdduff99** [comment]
Thank you so much for following up on this issue. I currently run  it on Windows and use version 3.2.7. I have two campaigns that I see the issue with so I include a link to download the files below. Thanks again.

[https://drive.google.com/file/d/171LNvIT7u3AuIFQ9ivMkW-3O0eLmNVQx/view?usp=sharing](url)

**Comment by salexgit** [comment]
Hi 

Can you try the online version 3.2.8? Here is the link: http://panzermarshal.com/

Regards, Alex

**Comment by salexgit** [comment]
Hi again

I tried to open saved game, link for which you had sent earlier, but it does not work. Can you please zip saved game and upload it here?

Regards, Alex

**Comment by jdduff99** [comment]
Here try this zip. Sorry about that. I played the online version 3 times so far and I don't seem to have the issue there so far. I will update my local game to v3.2.8 and test it there next. Thanks!!

[Campaign files with problem.zip](https://github.com/nicupavel/openpanzer/files/4914983/Campaign.files.with.problem.zip)

**Comment by jdduff99** [comment]
The online version has been working for me so far so I can continue playing it that way. At some point I will try upgrading my local copy and see but for now I will close this issue. Thank you so much for following up.
