### ISSUE TITLE
Tobruk scenario - German Campaign

### ISSUE THREAD

**Issue by cmack1** [nicupavel/openpanzer#276]
Great game! However when I deploy units in the above scenario/ campaign the deployment mode never leaves and my units cannot attack. They can move but not attack. Using Apple IPad. Please help me resolve this issue. Also I just contribute five dollars but can’t get the downloaded new version into the app. Thanks for your help.

**Comment by salexgit** [comment]
Hi

Can you please upload the saved game here?

Regards, Alex
