### ISSUE TITLE
List of Equipment

### ISSUE THREAD

**Issue by Domas2016** [nicupavel/openpanzer#277]
Is it possible to get the list of equipment in xls. format? I assume that file can be found in soem folders after installing the game but I play only WWW version

**Comment by salexgit** [comment]
Hi

A similar question has been asked several times, i.e. why the game does not provide a way to show all units with their characteristics. As for me it would be a great enhancement, but I will forward this question to the main developer.

What we can do - I can think about it more - is to convert equipment files into some form of TXT/table format, and publish it on the WIKI page. You can also find the corresponding files in the equipment folder once you install the game, but they are in the JSON format and it is not easy to read them.

Regards, Alex

**Comment by nicupavel** [comment]
To get the CSV file you can follow the directions here: https://github.com/nicupavel/openpanzer-tools/tree/8dbc86e79021be6530241ecbea0d78650ef3a491/equipment
