### ISSUE TITLE
Hong Kong - Japanese Campaign

### ISSUE THREAD

**Issue by spengler17** [nicupavel/openpanzer#279]
In the Hong Kong scenario there are no naval transports to embark your units to the island, which is necessary to complete the battle and win.

**Comment by salexgit** [comment]
Hi

Can you please check whether it is the same issue as what reported in #269? In short, there is a bug in the latest version(s): you cannot embark even if you have transports.

**Comment by spengler17** [comment]
There are no transports present in the scenario during the campaign, however when brought up as an independent scenario there are, which do work. This still means the campaign is unfinishable, however.

**Comment by salexgit** [comment]
Hi

This is really strange. Transports should be available irrespective of the fact whether you play it as a campaign or a scenario? Do you have a saved game before you move to the Hong Kong scenario? Maybe it help us to understand where the problem is coming from.

**Comment by spengler17** [comment]
9eb06b076c2a1593e5b8af17173c67f1

**Comment by MansteinlovesGuns** [comment]
> In the Hong Kong scenario there are no naval transports to embark your units to the island, which is necessary to complete the battle and win.

Where do I find the japanese campaign

**Comment by LudiCane** [comment]
I tried to play beta version online, and installed version. There is no naval transport on both versions. I finished the battle, lost, and sent on last scenario in campaign. Help!

**Comment by LudiCane** [comment]
And I just checked. There is 6 naval transport and 2 air transports in scenario, which does not exist in campaign

**Comment by Philip799** [comment]
sorry for my eng 

I think the open panzer has already been completely refined, in terms of bugs etc.
 When removing errors from the Panzer Marshal, it is enough to follow the open Panzer and possibly add technical solutions.

**Comment by salexgit** [comment]
Hi

@LudiCane: It is really strange - if you have transports in the standalone scenario, you should also have them in the campaign mode. I suspect that something is still broken in the game mechanics. I will try to re-produce the problem so that the main developer can take a look at it. 

Regards, Alex

**Comment by LudiCane** [comment]
> Hi
> 
> @LudiCane: It is really strange - if you have transports in the standalone scenario, you should also have them in the campaign mode. I suspect that something is still broken in the game mechanics. I will try to re-produce the problem so that the main developer can take a look at it.
> 
> Regards, Alex

I've opened save file, and both NavalTransport and AirTransport values for all ports and airfields were set to 0. I Changed that to some reasonable numbers and i finished this stage of campaign.

**Comment by Philip799** [comment]
agreed, there is no port or other transport place. I Have even killed units on other side of the shore, this is no working... as a port or some like ferry. Hong Kong. Someone finished this scenario in camp mode?

**Comment by salexgit** [comment]
Hi

I did not have time to look into the details of the problem and why it appears only in the campaign mode. As a quick&dirty workaround I can suggest the following:
- save the game locally on your computer;
- open the saved game file in any text editor;
- locate "navalTransports" and "airTransports" fields, and change them from 0 to the corresponding number of transports;

Regards, Alex

**Comment by LudiCane** [comment]
> Hi
> 
> I did not have time to look into the details of the problem and why it appears only in the campaign mode. As a quick&dirty workaround I can suggest the following:
> 
> * save the game locally on your computer;
> * open the saved game file in any text editor;
> * locate "navalTransports" and "airTransports" fields, and change them from 0 to the corresponding number of transports;
> 
> Regards, Alex

Dear Alex, 

I have already did that and passed this battle in campaign mode. 

Thank you, anyway 👍 

@Philip799 this is the answer on your Q. Edit saved game, and go forward.

Regards

Igor

**Comment by nicupavel** [comment]
Identified and fixed for 3.2.10

**Comment by Philip799** [comment]
> Identified and fixed for 3.2.10

on Android platform too?
