### ISSUE TITLE
Can buy disallowed units

### ISSUE THREAD

**Issue by Bluepanzer1943** [nicupavel/openpanzer#281]
If you enter a scenario, even in campaign mode, and select a non-core unpurchasable unit (such as a ship) in the unit menu, you can press Buy and get a ship/flak/etc as a core unit. The same goes for prototype units, you can just buy more of them by selecting them. Fortifications work as intended (can't buy them) but so far all other units seem like fair game, regardless of year restriction or being an unpurchasable unit.

**Comment by salexgit** [comment]
Hi

Nice catch.. I checked and am confirming that the bug is indeed there. I wonder why nobody has noticed it before.
I informed the main developer, so let's see how fast we can fix it.

Regards, Alex

**Comment by Philip799** [comment]
> If you enter a scenario, even in campaign mode, and select a non-core unpurchasable unit (such as a ship) in the unit menu, you can press Buy and get a ship/flak/etc as a core unit. The same goes for prototype units, you can just buy more of them by selecting them. Fortifications work as intended (can't buy them) but so far all other units seem like fair game, regardless of year restriction or being an unpurchasable unit.


There should also be blocked units not recommended and their improvement in historical campaign mode.

**Comment by nicupavel** [comment]
Identified and fixed for 3.2.10
