### ISSUE TITLE
Is it possible to add new equipment/scenarios/campaigns?

### ISSUE THREAD

**Issue by Bluepanzer1943** [nicupavel/openpanzer#283]
I have quite an interest in modding (and way too much free time). I've been playing around in the files for a bit, but any change to the scenarios seems to break them. What am I missing?

**Comment by Philip799** [comment]
> I have quite an interest in modding (and way too much free time). I've been playing around in the files for a bit, but any change to the scenarios seems to break them. What am I missing?

I think, there is no bigger chance to mod this game :(  both: mechanical and graphic. This is old game. On PC panzer general I'm trying to change a photo realistic and historical icons, and maps from old plane photos and have problems. sry 4 my eng.
