### ISSUE TITLE
HQ infantry units 

### ISSUE THREAD

**Issue by Philip799** [nicupavel/openpanzer#284]
Where can I find information on infantry HQ units?  What are their additional attributes, influence on other units and range of influence and do HQ units affect all unit types?
Please all info about this units.

**Comment by salexgit** [comment]
Hi

What is the infantry HQ unit? I am not sure I got the question...

**Comment by Philip799** [comment]
not sure, in open general HQ gives boost of statistics other units, but I don't know what is range and which Stat is boosted, maybe it's only exp.

**Comment by salexgit** [comment]
Hi

I am still not getting the essence of the question. This game is not Open General, so you should not expect to have exactly the same features as in Open General if your question is about that. However, it is always to nice to hear which new features you would like to have :)

Regards, Alex

**Comment by Philip799** [comment]
Yes, I know. I thinking that some addons are physically possible. Like a more preferences to units who is so many and only different is price. Artillery fire and mortar possible fire on mountains or obstacles. more specializations for different infantry units. This give a game more dynamics and tactics. On Android can do that?
