### ISSUE TITLE
Entry of the Bear_ Bandar-e Torkeman problem

### ISSUE THREAD

**Issue by LudiCane** [nicupavel/openpanzer#285]
![Screenshot 2020-10-13 at 20 40 09](https://user-images.githubusercontent.com/62623789/95902224-c8cb0000-0d94-11eb-8252-2060f17a7675.png)
As you can see, on the beginning of this stage of Japanese campaign, a have whole auxiliary fleet deep in the desert. It would be a cool stuff if I should move them. But, unfortunately, all of them drop their anchors permanently

**Comment by salexgit** [comment]
Hi

That is clearly a bug. I saw something similar in one of the African scenarios. We will need some time to investigate whether it is a wrong location of ships or whether it is a wrong unit ID.

**Comment by LudiCane** [comment]
> Hi
> 
> That is clearly a bug. I saw something similar in one of the African scenarios. We will need some time to investigate whether it is a wrong location of ships or whether it is a wrong unit ID.

There is also small German fleet in upper pat of map. All Naval units are in the sea, but they can shoot like they are ground units - only on range 1.

**Comment by nicupavel** [comment]
Identified and fixed for 3.2.10
