### ISSUE TITLE
LSSDAH campaign Load from disc button does not work

### ISSUE THREAD

**Issue by LudiCane** [nicupavel/openpanzer#289]
I can save the game, but load from disk button does not work, so i can't load saved gam. Safari on iMac

https://user-images.githubusercontent.com/62623789/103011355-0d63dc00-453a-11eb-8e68-f99e4af2c5a5.mov

**Comment by salexgit** [comment]
Hi

I tested with MacOS and Safari, it works for me. Could it be due to your local security settings? 
As a workaround, try to use another browser. 

Regards, Alex
