### ISSUE TITLE
Cloud saves no longer work as of 4/7/2022?

### ISSUE THREAD

**Issue by bubbadogslaw** [nicupavel/openpanzer#301]
I am playing on 3.2.10, and on the web client when I access from my PC and the iOS app, I can load cloud saves but I cannot overwrite existing ones or create new ones - I get a “cannot create save!” error no matter what. Cloud saves were made in 3.2.10, I haven’t had a problem in the past. Thanks for looking into this! 

Here’s a couple of my cloud saves for reference:
8b03b8b6664f36896c9ec94c9c726a4c
748b6f149186cbdfe06cc5bf9e0802e7

**Comment by CCMM2** [comment]
The same here. No longer possible to save in the cloud on iPhone , iPad  and Mac. 

Any help please?

Thank you.

**Comment by FastPlayer1234** [comment]
doesn’t work on web version as well.

**Comment by nicupavel** [comment]
Cloud Save/Load fixed in 3.2.11

**Comment by barsoom1717** [comment]
Where do I go to download the latest version?  Its been a few years since I played last.
Stephen Craig
    On Sunday, January 28, 2024 at 11:18:44 AM CST, Nicu Pavel ***@***.***> wrote:  
 
 


Closed #301 as completed.
