### ISSUE TITLE
experience balancing

### ISSUE THREAD

**Issue by campaignbuff** [nicupavel/openpanzer#304]
I've been thinking about this for a while so I'll trow it out there.
Would you consider a system to balance a unit's experience?

It's not a problem really, just the old panzer general mechanics I guess, but especially in long campaigns (lssah/mak for example) you end up with units that reach 800-1000 exp relatively quickly even in historical setting (400-500 are considered elite by the pm guide for reference), these start mopping the floor even with entrenched units that are superior in stats...
I think it would make sense for a unit to lose some exp when suffering losses, as well as every time it gets reinforced (reinforce button/start of a new scenario).
You could even spice it up a little bit more by having a chance to lose a units's leader, maybe when suffering particularly heavy losses.
It could be a feature of the hardest difficulty or an option in the settings, like fog of war.

I feel it would be a good way to balance the reinforcement and to make the playtrough generally more challenging, also more ""historical"" if that's how one's trying to play.
I'd really like to hear your opinions on this one @salexgit @nicupavel 

All the best

**Comment by CCMM2** [comment]
I don't think that reinforcing a unit leads automatically to experience loss, you can also reinforce with skilled units...
But I agreee on a system to balance the unit's experience.

**Comment by nicupavel** [comment]
3.2.11 Reduced max experience to 600 instead of 1000.

**Comment by campaignbuff** [comment]
Thanks, a simple solution but I can already see it works tbh
