### ISSUE TITLE
Save doesn't save but defaults to last action

### ISSUE THREAD

**Issue by LaughtersGrave** [nicupavel/openpanzer#307]
I don't know exactly how to describe this.

I win a battle onto the next, I deploy units. I miss click and then load..
Nothing changes, the unit is still where I miss clicked.

I close the app. Saves work fine in the last mission but on the new one I can click save as much as I like, but when I click load on any of them it simply stays exactly where it was before I loaded.

In short while the buttons can be clicked, in the new mission no saves or loads can be made.

It makes no sense.

**Comment by nicupavel** [comment]
Fixed in 3.2.11
