### ISSUE TITLE
Bug since new sound update

### ISSUE THREAD

**Issue by mfrassl1975** [nicupavel/openpanzer#309]
Campain - Sevastopol

Game freezes in round 2 when naval units (AI) engage with following error: (see pics)

cheers m
![e1](https://github.com/nicupavel/openpanzer/assets/101089337/c4b7527a-6539-40d8-9f5d-bdd5f8efb67f)
![e2](https://github.com/nicupavel/openpanzer/assets/101089337/7641c188-4a2c-4806-b223-f3201e3497c3)

**Comment by nicupavel** [comment]
Fixed. Will be released in 3.2.14. Thank you.
