### ISSUE TITLE
End of campaign message

### ISSUE THREAD

**Issue by flyingfisch** [nicupavel/openpanzer#54]
There is no message when you end a campaign that lets you know it's over. This makes it a little confusing when the campaign ends because you are expecting another scenario to load and it doesn't.

**Comment by nicupavel** [comment]
There should be a Campaign Finished window popup at the end. Looks the same with scenario briefing window when a scenario starts. But I'm considering to make it nicer for v3.0

**Comment by flyingfisch** [comment]
Sounds good :)

**Comment by barsoom1717** [comment]
You start with no prestige, you don't get any prestige after each tiun, and the American forces are way too reactive and overwhelming from the very start.  It appears to me this scenario and campaign are unwinnable.

**Comment by nicupavel** [comment]
Implemented 3.2.8
