### ISSUE TITLE
Luttich redoux - Russian campign stalls at the transition to bagration from illisi

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#57]
Same as Luttich, won't go from the Romanian scenario to Bagration. Amother broken link. I am stalled on two campaigns. Good game could be great.

**Comment by nicupavel** [comment]
Looks like I can go fine from Iasi, to Bagration.
![op-bagration](https://cloud.githubusercontent.com/assets/1650801/10315125/0ccdc272-6c61-11e5-9af6-23c71287c4bb.png)

**Comment by Cjh1953** [comment]
Great, much appreciated, many thanks, will give it a shot.

Chris
