### ISSUE TITLE
Prohorovka/Kursk unit deployment hexes are not visible

### ISSUE THREAD

**Issue by gusevg** [nicupavel/openpanzer#58]
Prohorovka/Kursk unit deployment hexes are not visible, i can't place purchased unit on map (ipad air)

**Comment by nicupavel** [comment]
Looks fine while playing it in a campaign. For single scenario playing as germans, they don't have deployment.


![op-kursk](https://cloud.githubusercontent.com/assets/1650801/10315217/963588f6-6c61-11e5-88c4-a8601cc7bbe9.png)
