### ISSUE TITLE
Android 2.9 Version - no big german campaign?

### ISSUE THREAD

**Issue by xklikka** [nicupavel/openpanzer#60]
Hi. Played Open Panzer and finished the Fall weiß campaign. Omg. What a Fantastic game!!! I love IT instand of several crashes all the time. 
Why i cant Play the reich campaign on Android? ? I See the campaign in New campaign menu but cant choose  it. Only Fall weiß and the 1st US campaign.no german scenarios..only the poland ones... I really become sad. What Do I have to do? Is it a Bug? And Why There is no 1939-1945 campaign? Only the 1943-1945 is visible in Light Grey. But Not chooseable. PLZ help  me.  Cant sleep anymore ^^ i wanne plaaaaaaay ...this game is awesome!!

**Comment by serenity4jwr** [comment]
Do you have a general idea of when 2.9.1 might come out? I'd like to play a 1939-1945 German Campaign. It would be nice if we could spend some prestige points from say, 1935 on to try to develop some of the weapon concepts the germans had on the drawing board. If Hitler had waited until 1945 to START the war like his generals had urged him to, all of the german military would have been much better equipped.
