### ISSUE TITLE
Artillery takes casualties when enemy is surprised...

### ISSUE THREAD

**Issue by cypher27** [nicupavel/openpanzer#62]
First I would like to thank you, Mr. Nicu Pavel, and all those who worked together with you to make this awesome game. I am very happy that came across it. I first found it on android market for my galaxy s4 but then found this forum days ago and now I mostly play via my computer on openpanzer.net

It seems as though there is a complex bug involving surprised enemy units and artillery support fire. It has decimated three of my artillery units in just one game.

In detail: I had a front line of infantry in the russian campaign that just set up, waiting for the enemy to get close while I regrouped and organized my units behind. I also pulled an artillery unit forward just behind the line. This is the key: it was still mounted on transport (unable to defend) when bug did happen. Then on the enemy's turn he moved a unit which met my front line and was "surprised". But then it appears as though my (still mounted) artillery took action to fire at the enemy, and instead of damaging the enemy, the enemy unit (1 range motorcycles) fired 2 hexes away to damage my artillery pretty badly, but then a tiny little german panzer II fired 5 or 6 hexes away at my same damaged artillery and killed it. Some how supporting fire was reversed against my artillery, from units that exeeded their range, when my artillery was somehow activated to return supporting fire, even though it was mounted.

Similar event happened in the same game over a convoy of mounted units I had. Two of the mounted units were artillery and I set my yak 9 above them in case there was an enemy a fighter or bomber. Sure enough, an enemy fighter (some how automatically knowing where my convoy is) came to attack it and was surprised by my yak-9. But somehow my (mounted) artillery unit that was 2 hexes away from the enemy fighter completely died and the enemy fighter received no damage.

Something is triggering my mounted artillery to take part in combat when they shouldn't. The combat is also bugged having all damage go toward my artillery unit from enemies that are beyond the range at which they can attack my artillery.

In the first situation I had another artillery unit that was already set up that may have activated my mounted artilery unit to also return fire. Perhaps there is a relation there.

Im not a programmer, but it appears as though combat functions are calling on a mixed set of the artillery's stats. Perhaps mixing the regular range stats with special mounted stats causing not only an error in calculation but an error in the ccombat funtions. I say this because I'm 99% sure there is some kind of code that specifies and denies mounted units to defend (unless they're infantry).

Perhaps one line of code identifies it as an artillery unit that should fire back but another indefies the mounted status. But like I said im not a programmer.
All I can do is sit back and enjoy everything else about this great game and appreciate your efforts. 

Again, thank you Mr. Pavel

**Comment by nicupavel** [comment]
Confirmed: Surprised AI can still attack initial target.
