### ISSUE TITLE
No deployment hexes for core units on Operation Typhoon

### ISSUE THREAD

**Issue by johncurriv** [nicupavel/openpanzer#64]
Really enjoying Open Panzer, but I've come to Operation Typhoon in the long German campaign and I am unable to deploy core units.  Is this by design?  

If so, maybe you could add this caveat to the mission details at the beginning.  

And, if so, I foresee brilliant victory as impossible on this mission.

**Comment by lukewarrendc** [comment]
Agreed. No way to put your core units in. I ended up just using it as a way to get prestige to upgrade my core units.

**Comment by nicupavel** [comment]
I know about this issue, I'll try to find some time to fix it.

**Comment by GGB1940** [comment]
Has there been a fix to this yet. Great game

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) at http://openpanzer.net let me know if it fixes this issue. iOS/Android build should come in February 2016.

**Comment by johncurriv** [comment]
Hey man,

Glad you're still putting the time in on a great game you've developed.  Panzer General was one of my favorites as a kid (as having grown up on playing games like Axis and Allies with my grandpa or the original PG and PGII on original Playstation), and I was thrilled to see a deep war strategy game like this for iOS.  

Thanks for responding to my feedback.  Keep up the good work!

**Comment by schmaehgol** [comment]
Just wanted to note that the problem still persists in the iOs app version 2.9.5 as of Nov. 29th, 2017. I'm loving this game, so any chance of getting it fixed?
