### ISSUE TITLE
Rename Units / Leader info display

### ISSUE THREAD

**Issue by cypher27** [nicupavel/openpanzer#65]
Would it be possible to add a feature allowing the player to rename core units? Different core units over time acquire different types of leaders and its impossible, before deploying them, to see which unit has what leadership characteristics during the deployment window; which is another feature that could be added.
Renaming would greatly help the player to differentiate between two units of the same type that have different types of leaders. It also would greatly help tactical organization in general too.

Also, the standard names, for eaxample:
"136th Pz IVF1 Tank (Core Unit) (Leader)"  only appear once deployed, and even that number varies depending on which order you deploy the unit. If you deploy another first, and then deploy said tank unit, its becomes "137th" instead of "136th" which confuses me throughout scenarios.

The name is shortened even further while in the deployment screen (not yet deployed) to:
"Pz IVF1 Tank"

It excludes the fact it has a leader and even its experience level; although estimation of a units experience isn't that hard since your core units are ordered in the deployment menu according to their experience.

**Comment by nicupavel** [comment]
I plan on revamping equipment/deploy windows thanks for bringing this up.
