### ISSUE TITLE
Bzura pocket BUG

### ISSUE THREAD

**Issue by wepman** [nicupavel/openpanzer#67]
Hi, 

great game. Found one bug. In scenario Bzura pocket i am not able to finish scenario. After conquering (moving unit into city) last object  Wladislawow city - city changed flag and captured notification displayed above city. Then game showed notification about Brilliant victory and thats all. After submitting victory message, nothing happend. After clicking end turn button it says: you did't capture objectives in time.

It happends several times. Please check this cloud save: 089cb5a6fb05765374b5  

Thanks...

**Comment by nicupavel** [comment]
Your save doesn't contain the campaign data. Something happened to the save game.
