### ISSUE TITLE
fog of war and next unit

### ISSUE THREAD

**Issue by jreidinger** [nicupavel/openpanzer#68]
Hi,
Thanks for this cool game. I try it and works quite nice just observe few stuff that makes it even better and one bug:
1. missing visual indication what is already seen, so some fog of war to see what hexes are spotted and what is not, so there can be units to surprise. ( maybe I need to enable it somehow? )
2. button to select next unit that do not move or attack. For bigger battles it is easy to overlook that some unit do not move yet ( maybe I just overlook it? )
3. tutorial even after capture of the latest part cause not all objectives captured message

I have some programming skills, so do you accept pull requests with fixes?
Thanks

**Comment by nicupavel** [comment]
This are already implemented
