### ISSUE TITLE
Best iPad war game hands down, but please fix the scenario transition glitch

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#69]
Hi: this is the best war game on iPad, period: most authentic, best detail, great diversity of weapons, best aesthetics, great game mechanics. But please, please fix the transition from Hedgerow to Luttich, that's all I ask. The other issues I can live with, but please fix this. I am paying for lessor games while waiting, but I'd rather pay for this patch.

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) at http://openpanzer.net let me know if it fixes this issue. iOS/Android build should come in February 2016.
