### ISSUE TITLE
ParaTroopers can't embark in Das Reich Campaign. 

### ISSUE THREAD

**Issue by AfrikaCorps** [nicupavel/openpanzer#70]
First off Awesome Job!  

Typhoon Vyazma - Not Hex to deploy Core Units.
I read in a post from a guy that identified himself as the original developer PG 2 from SSI.                     According to him you are suppose to take the city of Spas-Demensk to the South where the re-enforcements appear and the deployment Hex for Core Unit will appear.  But that didn't happen in the IOS version.

Typhoon Called off - There is one unmarked objective.  
In the left side of the map just above the starting Hex, there is a radar station and an entrenchment inside the encirclement of mountains, turn on the terrain to see the mountains.  I suspect you need to drop Paratroopers in the mountains to take that objective.  Unfortunately in Das Reich You can't embark air troops even standing on an airfield. However I tested in the first Poland campaign you can buy paratroopers and deploy them on an airfield and they will embark onto an air transport.  Even in the the Student map, once you drop a paratrooper you can on long embark them at an airfield again.

Fourth Battle of Kharkov - Two unmarked objectives.  
Yeah the city/airfield to the north west corner needs to be take,  also mid-way down on the right side of the map a single Russian infantry will appear at the last turn for a Victory.  Need to kill him,  No Brilliant victory possible. 

March on Limoges - Yeah all no air troops are trapped in a mountain range.  
If paratroopers can be deploy this would not be a problem.  You can always air drop to take the objectives.

**Comment by nicupavel** [comment]
Thanks for rounding up all current issues, I will try to find some time to fix those.

**Comment by nicupavel** [comment]
All 3 issues fixed, they will be available once I release 3.0.

**Comment by lukewarrendc** [comment]
Any idea when 3.0 will be released.  Getting very excited for all the fixes!

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) at http://openpanzer.net let me know if it fixes this issue. iOS/Android build should come in February 2016.

**Comment by bachboy** [comment]
Absolutely love the game, was playing it with great success, but the 2.95 version all of a sudden had 2 MAJOR problems for me--1st  after a Brilliant Victory and a promised unit,  the unit did NOT show up at the next scenario??  and 2nd--even worse--the next scenario was IMPOSSIBLE to win as the number of victory hexes exceeded those possible to capture as many were ones I began the game with?? thanks for any help on this,  so frustrating I am now just play the chrome app 2.8, Dave

**Comment by bachboy** [comment]
thanks so much for "repairing" the bugs in this wonderful game, have not completed any campaigns yet, but everything seems to be working so far!! Love playing it over and over. You have done a wonderful job.
