### ISSUE TITLE
Unternehmen Seeloew Training Issue

### ISSUE THREAD

**Issue by toksuzler** [nicupavel/openpanzer#71]
The Unternehmen Seeloew Training Campaign ends premature around turn 4/5 abuptly with message that I've failed.  Not sure why.  The game was progressing fine.  There will still 3-4 turns left to achieve brilliant victory.  What's causing this bug?

**Comment by nicupavel** [comment]
Can't replicate
![op-seeloewe](https://cloud.githubusercontent.com/assets/1650801/10231865/ce1030aa-688d-11e5-9140-b4f9df53bbe3.png)

**Comment by toksuzler** [comment]
Thanks for the reply.  Not sure what is wrong with mine.
