### ISSUE TITLE
ad12.png file does not load when adblock is enabled

### ISSUE THREAD

**Issue by hahnicity** [nicupavel/openpanzer#75]
The first error I see on the console is:

```
GET http://openpanzer.net/resources/units/images/ad12.png net::ERR_BLOCKED_BY_CLIENT
```

Then afterwards when I try to advance my troops into Soviet territory I get this:

```
Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
```

This breaks many of the levels with soviet troops.

Of course the easy workaround is not to use adblock but then again perhaps the file can be a little bit more appropriately named

**Comment by nicupavel** [comment]
Thanks for bringing this up, but if I rename those units ids I will break compatibility with adlerkorps equipment file. For now I'd just disable adblock on openpanzer.net, since there will never be ads there.
