### ISSUE TITLE
Warsaw

### ISSUE THREAD

**Issue by poweroflight** [nicupavel/openpanzer#76]
Warsaw campaign will not end at the end of the scenario.   If I winunder the brilliant victory conditions it say just Victory.  When I acknowledge it then it just sits there.  
![image](https://cloud.githubusercontent.com/assets/16061082/11453162/9dffe85a-95c5-11e5-80c1-af94d39f129f.png)

**Comment by nicupavel** [comment]
It does say "Campaign Finished" which means there aren't more scenarios in this campaign. Congratulations.
