### ISSUE TITLE
Anticipation

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#77]
I have seen that many of the needed fixes are in the works. Thanks, but I am very keen to get back at it. My campaigns are stuck! Please update!

A fan.

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) at http://openpanzer.net let me know if it fixes this issue. iOS/Android build should come in February 2016.

**Comment by lukewarrendc** [comment]
Any update on when the new iOS version will come out?  I checked online and most of the buses for the German campaign seem to be fixed. 

Having problems online with operation Saturn online. I have captured every flagged Italian position and the game says I still have 3 to capture. And I am way past the 20 turns allocated for victory and yet the game will not end.
