### ISSUE TITLE
Operation Typhoon-Vyazma No deployment hexes

### ISSUE THREAD

**Issue by boberuski** [nicupavel/openpanzer#79]
In the campaign there are zero spaces for deployment. I can't deploy any of my troops.

**Comment by hahnicity** [comment]
+1 This is pretty frustrating

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) let me know if it fixes this issue.

**Comment by Superbobrik** [comment]
Hey! Just love your game! But that issue is not fixed on Ipads (Ios). Could you please check?
