### ISSUE TITLE
Typhoon called off: Capturing all victory hexes does not lead to the scenario ending

### ISSUE THREAD

**Issue by hahnicity** [nicupavel/openpanzer#80]
I am playing as the Germans in Typhoon called off and I have been able to capture all victory hexes on the map however victory is not triggered and gameplay continues. Eventually you can just run out the clock and the game results in a loss for the player

**Comment by nicupavel** [comment]
There is a new version out (2.9.5) let me know if it fixes this issue.

**Comment by Berntus** [comment]
Hello Nico! Thanks for the game dev. The above problem still exits for Android. Will the new Build be released soon? Regards, Berntus
