### ISSUE TITLE
Units won't move or attack in Bzura Counterattack 

### ISSUE THREAD

**Issue by johnjbarton** [nicupavel/openpanzer#81]
Hi, Enjoyed Lodz-Warta and sat down to move to the next battle in the Campaign.  Unfortunately I am unable to move the units or attack.

I can place units and select them. Selected units will show the expected result of attack if I hover on  enemy units. Attack will not start if I click. The movement extent hexes do not light up. It's a bit like the units have completed their move. I can reinforce units.

I tried ending my turn and the computer plays its side no problem. But I'm stuck in the same way again.

While I was trying various things I saw the movement-extent hexes one time. I thought it was unstuck! But I could not repeat this small success. 

There are no errors in the Chrome Devtools console.

My cloud save id 
16139023d850566b9556

Linux 3.13 Chrome
Version 47.0.2526.106 (64-bit)

Any suggestions?

**Comment by nicupavel** [comment]
Do you also have a game saved to disk ?

**Comment by johnjbarton** [comment]
[(Campaign) Bzura Counterattack Turn 1 Fri Dec 25 2015 9-59-03 PM.json.txt](https://github.com/nicupavel/openpanzer/files/102159/Campaign.Bzura.Counterattack.Turn.1.Fri.Dec.25.2015.9-59-03.PM.json.txt)

**Comment by johnjbarton** [comment]
Here is the save file.

**Comment by johnjbarton** [comment]
While playing a scenario I noticed that if I had a unit to place on the map, other units could not be moved,
that is they acted as I reported above.
