### ISSUE TITLE
Problem With Student

### ISSUE THREAD

**Issue by billyjoe808** [nicupavel/openpanzer#82]
The game says there are 12 objectives to conquer, but there are only 10 objectives. I love the new AI update and want to play the scenario with the new fixes to Road to Limoges and Operation Luttich but I cannot pass this level! And it wouldn't even let me lose, I went to turn 27 out of 25, and am very upset, please help as soon as possible!

**Comment by nicupavel** [comment]
Is this with the new version on openpanzer.net ? Because I see only 5 objectives.

**Comment by billyjoe808** [comment]
No sir. It is the online version, but it is different in the campaign. It starts with 10 objectives, which is the right number, but 3 of them start captured so when they capture them the amount of objectives needed to capture can go up to 13-even though there are only 10 objectives.

**Comment by billyjoe808** [comment]
And if this problem could be quickly fixed that would be great (Version 2.51)

**Comment by cypher27** [comment]
I am having a similar problem with the mission after Operation Student,
where the French counter attack. The game says I need 2 objectives, but
there is only 1. If I play just the scenario version, then it is fine. This
is on openpanzer.net

Likewise, on the second mission of the American campaign, there are only 5
objectives, but the game says I must conquer 10. It also didn't give me the
free unit from the brilliant victory on mission 1, but that's another, less
important issue.

**Comment by billyjoe808** [comment]
Please, if it is pleasing to you, confirm this issue and give the community assurance that this issue is being resolved.
Thank you,
I'm actually building the 21st Panzer division using the historical order of battle,
Billyjoe808

**Comment by nicupavel** [comment]
I can't replicate. Try loading my save game from start of Student (second scenario). See attached screenshots for primary objectives (I see 5 objectives to capture at the start). Maybe the bug is somewhere else (after the AI captures some of the initial objectives)
<img width="1276" alt="screen shot 2016-02-27 at 09 10 23" src="https://cloud.githubusercontent.com/assets/1650801/13371649/2f5caa08-dd34-11e5-895b-8b6fe462d187.png">
<img width="693" alt="screen shot 2016-02-27 at 09 10 06" src="https://cloud.githubusercontent.com/assets/1650801/13371650/2f5f6d38-dd34-11e5-88f0-2574818feb99.png">

[(Campaign) Student Turn 1 Sat Feb 27 2016 9-26-51 AM.json.zip](https://github.com/nicupavel/openpanzer/files/149247/Campaign.Student.Turn.1.Sat.Feb.27.2016.9-26-51.AM.json.zip)

**Comment by billyjoe808** [comment]
I am now having issues with the French Counterattack. I captured the objective and it says I need one more. Some more insight to the problem.... When I was playing Student everything was doubled... all the reinforcements were doubled, all the enemies reinforcements were doubled and  most importantly the Objectives were doubled. Maybe the problem is that something in a script is being doubled? It does not make a whole lot of sense, I am playing with a Google Chromebook  and google chrome.

**Comment by cypher27** [comment]
That was exactly my problem with that mission as well. I needed one more
objective, as if it were doubled, but I don't recall if other things were
doubled. Actually, I think only the objective count was doubled. I play
with Mozilla Firefox Browser.

**Comment by billyjoe808** [comment]
Are you still not able to see it? How would I be able to give you a link or download so you can get to one of my saved games with the error? Thanks

**Comment by nicupavel** [comment]
You can save the game, zip it and attach it here.

**Comment by billyjoe808** [comment]
Hopefully this helps, it is my campaign.
[(Campaign) 7th French Army rush North Turn 12 Fri Mar 04 2016 4-56-48 PM.zip](https://github.com/nicupavel/openpanzer/files/199773/Campaign.7th.French.Army.rush.North.Turn.12.Fri.Mar.04.2016.4-56-48.PM.zip)

**Comment by billyjoe808** [comment]
As you can see I already captured the 1 objective, for some reason everything is being doubled.

**Comment by DCTank** [comment]
Hi , i play campaign and in this mission there are 20+ objectives at start ... is normal ?

**Comment by nicupavel** [comment]
Load the save game in openpanzer.net/beta/
