### ISSUE TITLE
Cloud saves

### ISSUE THREAD

**Issue by Cjh1953** [nicupavel/openpanzer#84]
I have tried saving a game to the cloud from my iPad and opening it in the browser based game but it no longer works. I am very keen to move on past the hedgerows scenario and start Luttich. Any suggestions?

**Comment by billyjoe808** [comment]
id you load an old one or is this a new campaign since the update?

**Comment by Cjh1953** [comment]
The saved game is from my iPad, therefore it is the August 2014 version. If the August 2014 version won't load on the new version [2016] there are going to be a lot of disappointed gamers who want to finish their existing campaigns, not start from scratch.

**Comment by nicupavel** [comment]
Ok, I will have to do something about this to allow compatibility between saves even on different versions that don't change the save game structure (as it is now with 2.9.0 -> 2.9.5)

**Comment by Cjh1953** [comment]
Wonderful! That would be fabulous. thanks

**Comment by Cjh1953** [comment]
Thanks Nicu: I am very keen to play through the DR cycle. I am anxiously awaiting the iPad update but would play on the web if I could.

I have reviewed all the war games in the Ap store and tried a bunch of them. There is no comparison - OP is the best hands down. I am a veteran war gamer, started with Avalon Hill's Blitzkrieg and made it to Advanced Squad Leader. So I'd say I have a very broad set of experiences. Clearly the AI function has its limits, but the units, terrain, mechanics, aesthetics are all top flight. 

Thanks for many hours of fun. I am looking forward to many more. I have to say that I check every day and I am really hoping that the Ap or access to saved games from the 2.9.0 from .5 comes soon.

Chris

**Comment by lukewarrendc** [comment]
Yes, and my iPhone OP app is locked, so I am hoping the 2.9.5 upgrade will unlock the app and allow me to pick up where I left off and even retrieve old saves and play from the earlier broken scenarios.

**Comment by Cjh1953** [comment]
Hi Nicu: I must say that I  am very anxious to finish the DR campaign. I am stuck at Luttich. Is there any chance there would be a patch just for that one issue?\

 

Best regards, Chris

**Comment by Cjh1953** [comment]
Hi: I am stuck. I can't move past Hedgerows to Luttich and I can't open my existing game saves on line. If there is any way to simply patch the old iPad version to allow me to transition to Luttich it would be great. I would be willing to pay for such a patch of it was feasible. Can you help me salvage this great game? 

Chris

**Comment by Cjh1953** [comment]
Hi: I would really appreciate being able to finish the DR campaign. I am starting to despair though. All I need is to transition from Hedgerows to Luttich. Can you tell me if this is going to be possible and if so, when. It would be a real shame to see such a great game dead-ended.

Regards, Chris

**Comment by Cjh1953** [comment]
Still hoping for a fix.   am stuck at Hedgerows in 2.9.0 on my iPad and can't open existing saves in 2.9.5 or save back to 2.9.0 from 2.9.5.

 

What would it take to get a patch in 2.9.0 to allow me to continue to Luttich?  I am very keen to play the series through.

 

This is a great game.

 

Chris

**Comment by nicupavel** [comment]
Fixed in beta

**Comment by Cjh1953** [comment]
When will the fix be in effect. I tried to load an iPad game (2.9) save on the browser but no success. I really like this game and I am keen to finish the DR series that I have on my iPad.

Many thanks!

Chris

**Comment by nicupavel** [comment]
Did you load the game at http://openpanzer.net/beta/ ?

**Comment by Cjh1953** [comment]
No but will do. Many thanks!!!!

**Comment by Cjh1953** [comment]
It worked!!! Fantastic & a huge thank you.

bTW - I've been playing a WW2 game by hexwar which in comparison Open Panzer is a clumsy, ugly game. No where near as sophisticated. 

I've tried others available t the Ap store and your game is the best war game available for iPad by a very, very wide margin.

I am hoping there will be more campaigns or scenarios but regardless, I am hugely grateful for what you've accomplished.

Chris
