### ISSUE TITLE
Core Unit issue

### ISSUE THREAD

**Issue by billyjoe808** [nicupavel/openpanzer#85]
I was playing again trying to see if the error with the objectives was just loaded wrong when I saw that the Unit ( a ju88 ) was not added for my brilliant victory in Poland. There are still the wrong number of obj's, I am seeing 10 objectives for Student, which is correct if the three obj's that start as captured were Dutch obj's instead of German. The correct number should be 7 I believe.

**Comment by nicupavel** [comment]
#90
