### ISSUE TITLE
Prototype units not reliably being added

### ISSUE THREAD

**Issue by hahnicity** [nicupavel/openpanzer#89]
Thanks so much for all your work on the game! Unfortunately prototype units aren't being added to the list of core units at the end of a mission if a brilliant victory is achieved. Not sure why this is happening but if I can help fix this bug for you I'd be happy to assist!

**Comment by salexgit** [comment]
It seems that I experience the same problem. In the beginning, I did not pay much attention to the prototype units granted for a brilliant victory. However, I noticed that even though the game says that a new unit is provided, I am not able to find it on the unit list. 

I will double check this issue as I have a number of saved scenarios at the last turn.

**Comment by hahnicity** [comment]
Any update on this issue? I've come back to the game after a bit and it still seems to be occurring?

**Comment by salexgit** [comment]
I have been playing the game for almost one year (not very actively though), but I have not seen this problem. Every time I have a brilliant victory, I am always granted the unit which I can always find later on the unit list. 

Do you have a saved game in which the bug can be reproduced?

**Comment by hahnicity** [comment]
Thanks for the response, I'm not sure what was happening in my game, but I refreshed and things were working again
