### ISSUE TITLE
Battle of the hedgerows - could not create game surface

### ISSUE THREAD

**Issue by tarcsikaroly** [nicupavel/openpanzer#94]
Hi,

Thanks for resurrecting one of my all time favourite. As a developer myself I really appreciate the excellent job you did on this.

Here is my problem: I got a "could not create game surface" error at the end of Battle of the hedgerows:

Ipad 2 32BG with IOS10,
Battle of the hedgegrows,
Turn 7 - Brilliant Victory

Let me know if you need further info. Thanks for helping.

Regards,
Kar

**Comment by nicupavel** [comment]
This is usually because of low memory but I haven't yet tested on iOS 10 to make sure if they didn't change the texture size limits.

**Comment by Cjh1953** [comment]
Can load Luttich on web version, but not iOS from Hedgerows or as stand alone. Cannot open iOS 2.9 cloud saved game on web version. Still stuck! Does anybody have a fix!

**Comment by spg0177** [comment]
I have been playing Open Panzer for over a month on IOS 10. It's been fantastic. I won the  hedgerow scenario with a brilliant victory but I had the same error message as Kar above....could not create game surface....I cannot get into the game at all at this point. Main menu shows the title of the game but everything else is blank. Appreciate any help!
