### ISSUE TITLE
Panzerzug artillery unit

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#96]
Hi

There is an artillery unit called "panzerzug" which as follows from its name is an artillery system mounted on a train. Is it really playable? The matter is that once it is deployed, you cannot move it. I thought that the issue is that you have to deploy it on the rail road tile, which would make perfect sense, but that does not help either. Is it a weird bug or lack of the functionality in the the game engine?

**Comment by nicupavel** [comment]
Indeed the railroad artillery isn't implemented. This feature wasn't in original panzer general 2 it's an addition in OpenGeneral that I haven't implemented it yet in OpenPanzer.

**Comment by salexgit** [comment]
Ok. Just for my understanding, is it a lack of the game engine to support a unit of this particular type, or is it something more substantial that would require e.g. adding information on the available rail road tiles to a map? 

I would like to try this unit as there are many scenarios in which there are rail roads. If needed, I can provide some coding and testing support.

**Comment by nicupavel** [comment]
The scenarios/map information that I process (which are compatible with pg2) don't have railroad information. The equipment file has railroad restricted units. Probably in the future I will have to change to newer scenario format used by OpenGeneral and the community.

**Comment by salexgit** [comment]
Ok, got it... So it will indeed require quite substantial efforts, at least switching to the new map format.

**Comment by salexgit** [comment]
Hi

Back to this topic.... While playing the "The Kiev encirclement - Konotop" scenario, I noticed that the scenario designer has provided Soviets with the armoured train artillery unit. You can find the one right next to the Makoshino city in the attached saved game. I was a bit surprised to see it because if the game engine does not support this type of units, it means the AI cannot use it either, right? 
[(Campaign) Kiev encirclement - Konotop Turn 4 Mon Apr 24 2017 7_15_57 PM.json.zip](https://github.com/nicupavel/openpanzer/files/952415/Campaign.Kiev.encirclement.-.Konotop.Turn.4.Mon.Apr.24.2017.7_15_57.PM.json.zip)

The first step to support armoured train artillery unit would be to extend map format with an additional field indicating that a particular tile has a railroad. If so and if help is needed, I can take a look at existing scenario(s) and add the corresponding information to maps to enable game engine extensions.

**Comment by nicupavel** [comment]
Playing Great Patriotic War campaign I realised that the designers found a smart way to simulate railroads. See Vilnius offensive in stand alone scenario mode playing as Germans. You can actually move the PanzerZug because the railroad is defined as PORT on all hexes. Think I'll fix Konotop in the same way.

**Comment by salexgit** [comment]
Hi Nicu

Well, as for me it looks like a hack, even though it works :) 

As I was contemplating in #160, why not support .MAPX format that has information on railroads? Almost all the map files come in two formats - MAP and MAPX - so instead of hacking existing MAP files, we just need to enable support for MAPX. Otherwise we will need to change all the .MAP files where we have railroads, which is effectively redoing same job as what people have already done for .MAPX. In fact, we will not even need to change existing SCN files. The conversion script can look for xxx.MAPX file name first, and if it is absent then xxx.MAP file be processed. 

Regards, Alex
