### ISSUE TITLE
"Closing in on Dunkirk" is showed in the wrong place on the campaign description

### ISSUE THREAD

**Issue by salexgit** [nicupavel/openpanzer#98]
Hi

Not a bug, just a small discrepancy... 

If you check the list of scenarios comprising "Das Reich" campaign, then you will see that for some reason "Closing in on Dunkirk" scenario is showed in a wrong place, right after "Smolensk Drive To Yelnya". I suppose it should be somewhere after "7th French Army rush North".

By the way, is there a simple way to show it as a tree?

**Comment by nicupavel** [comment]
Yes, I'm considering implementing this as a tree with the new start menu style

**Comment by salexgit** [comment]
Hi

Ok, thanks for explanations.

Somewhat referring to the question I have in #101, will it be possible to add information on how much prestige you will have for next scenario in the campaign? If you know how much you will get in the next scenario, then you can plan your current expenses accordingly. Otherwise what happended to me quite often is that you play a scenario in a campaign, then you face the fact that you do not have enough money for the next scenario in the campaign to buy something specific, and then you have to replay the previous scenario again.

As an off-topic qiestion, where do we keep information on the scenarios in the campaign and related prestige information? I was trying to find on the github, but failed.
